nestjs/nest

src/microservices/test/server/server-redis.spec.ts
src/microservices/test/server/server-tcp.spec.ts

replace sinon.stub(instance, 'method', function) by sinon.stub(instance, 'method').callsFake(function) to avoid sinon warning

fix sinon deprecated warnings

---

package.json

Noticed that your License file says MIT but package.json said ISC. Just a quick change to sync those up.

Change package.json to reflect project license

---

Readme.md

Small fix. This typo occurs on https://docs.nestjs.com as well.

Fixed typo in Readme

---

src/core/router/router-execution-context.ts
src/core/router/router-explorer.ts
src/core/test/router/router-execution-context.spec.ts

I was trying out the @Param() decorator with the latest code @nestjs/core@4.1.3 and found it wasn't working. Its not mentioned in your documentation at https://docs.nestjs.com/components but there is a reference to it in `cats.controller.ts` in the `01-cats-app` example:
```
@Get(':id')
findOne(@Param('id', new ParseIntPipe()) id) {
// logic
}
```
In any case, I tracked the issue down to code in `router-execution-context.ts` and `router-explorer.ts` where `callback.name` was not defined for the follow two ReflectMetadata calls: 
`return Reflect.getMetadata(ROUTE_ARGS_METADATA, instance, callback.name);`
and
`return Reflect.getMetadata(PARAMTYPES_METADATA, instance, callback.name);`.
This PR fixes it by passing the `methodName` from `router-explorer.ts` to the `create` function in …

Fix for @Param() decorator

---

src/core/nest-application-context.ts

Update application context to support retrieving a module using a symbol. The injector already supports the use of symbols when declaring modules for DI.

fix(@nestjs/core) application context, support symbol

---

examples/13-mongo-typeorm/src/modules/photo/photo.entity.ts

`PrimaryGeneratedColumn` is not  being used in `photo.entity.ts` because the example uses mongodb.

Removed unused import

---

src/common/utils/shared.utils.ts
src/core/injector/module.ts
src/core/test/injector/module.spec.ts

Support for the use of symbols as the `provide` in module exports was
broken as a result of
`https://github.com/nestjs/nest/compare/v4.5.5...master#diff-f52585e35398d156c2cd41f3863d4c52R184`.
This bugfix corrects the issue by updating the changed code to test for
and support symbols.

fix(core): support symbols

---

src/common/interfaces/nest-application.interface.ts

Microsoft IIS uses strings such as "\\.\pipe\d226d7b0-64a0-4d04-96d4-a75e1278b7a9" instead of port numbers. When you create nodejs app on Azure this is problematic as nestjs would only expect a number. 
ps.
Thanks for an amazing framework!
Best regards,
Przemek

Allow providing server port as a string

---

lib/common/constants.d.ts
lib/common/constants.js
lib/core/router/interfaces/explorer.inteface.d.ts
lib/core/router/router-explorer.d.ts
lib/core/router/router-explorer.js
lib/core/router/routes-resolver.d.ts
lib/core/router/routes-resolver.js
src/common/constants.ts
src/core/router/interfaces/explorer.inteface.ts
src/core/router/router-explorer.ts
src/core/router/routes-resolver.ts
src/core/test/router/router-explorer.spec.ts
src/core/test/router/routes-resolver.spec.ts
yarn.lock

This PR will make it easy to add a `Path` Property to a Module without even editing the Public API of Nest.
the Idea, anyone needs to make a  `Routes Tree` will use an external package [nest-router](https://github.com/shekohex/nest-router).
this package is well tested and Documented.
this PR will close #255 .

feat(@nestjs/core) Nest Router, a Utility Package

---

src/common/test/decorators/route-params.decorator.spec.ts
src/core/metadata-scanner.ts
src/core/test/metadata-scanner.spec.ts

Changes to metadataScanner to enable scanning of Parent classes.
Linked to issue #228

feature(@nestjs) Enable inheritance for controllers

---

src/common/pipes/parse-int.pipe.ts
src/common/test/pipes/parse-int.pipe.spec.ts

**TLDR;** This PR improves the ParseIntPipe validation.
Take the following code base:
```typescript
// sample.controller.ts
//...
@Get(':id')
async getById(
@Param('id', new ParseIntPipe()) id: number,
) {
console.log(id);
}
//...
```
If a user sends the following HTTP request `GET http://localhost:3000/users/1abc`, the current parseIntPipe will validate the parameter. I think it's not the expected behaviour.
This PR will improve the parseIntPipe by using the `rxjs` function `isNumeric` to be sure that the input string is only composed of numbers. 
`rxjs` being already a dependency of `nestjs`, this PR doesn't add a new dependency.

Parse int pipe improvement

---

package-lock.json
package.json
src/common/pipes/validation.pipe.ts
src/common/test/pipes/validation.pipe.spec.ts

**TLDR;** This PR adds some options to the `ValidationPipe`.
Take the following code base:
```js
// pagination.dto.ts
import { IsInt, IsOptional, IsPositive } from "class-validator";
import { Type } from "class-transformer";
export class PaginationOptionsDto {
@IsInt()
@IsPositive()
@IsOptional()
@Type(() => Number)
readonly offset?: number;
@IsInt()
@IsPositive()
@IsOptional()
@Type(() => Number)
readonly limit?: number;
}
```
```js
// users.controller.ts
// ...
/**
* A `GET` request against the `/users?name=James&offset=20&limit=10` endpoint
* should return a paginated list of the users named James.
*/
@Get('users')
async getUsers(
@Query(new ValidationPipe()) pagination?: PaginationOptionsDto,
@Query('name') nameFilter?: string
) {
console.log(pagination instanceof …
```

feat(@nestjs/common) improve the ValidationPipe

---

src/common/http/http.service.ts

Currently, on the `request` method of the HttpService is generic. This PR makes all methods of the HttpService generic.

fix(common): making http service methods generic

---

lib/core/package.json

According to node security project
534 - Regular Expression Denial of Service
Vulnerable: <= 2.6.8 || >= 3.0.0 <= 3.0.1 - Patched: >= 2.6.9 < 3.0.0 || >= 3.1.0 - Path: @nestjs/core@4.6.4 > body-parser@1.17.2 > debug@2.6.7
How to fix
Upgrade to version 2.6.9 or greater if you are on the 2.6.x series or 3.1.0 or greater.

chore(@nestjs/core) update debug dependency due to security flaw

---

.travis.yml
package-lock.json

`npm ci` is much faster and is meant for CI. This PR is meant for evaluating the new ci command and testig the performance and compare the logs of Travis CI.
https://docs.npmjs.com/cli/ci
http://blog.npmjs.org/post/171556855892/introducing-npm-ci-for-faster-more-reliable

chore: use npm ci

---

.travis.yml

By default the last 50 commits are cloned. Cloning much less also decreases the time needed for each build.

chore: clone only the last 5 commits

---

package.json

Currently there is a bug with Nodejs 10 in grpc which is fixed in the latest release.
> npm ERR! grpc@1.10.0 install: `node-pre-gyp install --fallback-to-build --library=static_library`

chore: upgrade grpc

---

packages/microservices/server/server.ts
packages/microservices/test/server/server.spec.ts

- [V] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [V] Tests for the changes have been added (for bug fixes / features)
```
[V] Bugfix
[ ] Feature
```
`@MessagePattern("cmd")
testPath(): void {
}
`
Will cause the Server not to find the handler, because the string key was stringified resulting with extra parentheses.
Before adding the handler, Server will verify if pattern is a string before JSON.stringifiy
```
[ ] Yes
[V] No …
```

bugfix(@nestjs/microservices): messagePattern string key

---

bundle/common/interceptors/file-fields.interceptor.d.ts
bundle/common/interceptors/file-fields.interceptor.js
packages/common/interceptors/file-fields.interceptor.ts
packages/common/test/interceptors/file-fields.interceptor.spec.ts

usage will be like:
```import {FileFieldsInterceptor} from '@nest/common';
@UseInterceptors(FileFieldsInterceptor([{name: 'avatar', maxCount: 1},
{name: 'passport', maxCount: 1}]))
```
- [] Docs have been added / updated (for bug fixes / features)
```
[ ] Bugfix
[X] Feature
```
there are two interceptors FileInterceptor and FilesInterceptor based on multer.uploadSingle and multer.uploadArray. they allow uploading a single file, or multiple files with same field name. however if say there is a form with …

feature(@nestjs/common) add file-fields interceptor

---

packages/core/helpers/external-context-creator.ts
packages/core/router/router-execution-context.ts

Two modified files are the only places in the whole framework where HttpException specifically is used
and used to be used wrong. It's easier to handle and catch ForbiddenException (and other HttpException
child) rather than having to compare HttpStatus to catch it. As ForbiddenException extends HttpException
and provides same HttpStatus, old code catching HttpException still works.
```
[X] Bugfix
[ ] Feature
```
Two guards throw HttpException with "Forbidden resource" message and FORBIDDEN http …

bugfix(@nestjs/core): use ForbiddenException instead of HttpException

---

packages/core/errors/messages.ts

Fixes typo, clarifies what actions are expected.
- ~~Tests for the changes have been added (for bug fixes / features)~~
- ~~Docs have been added / updated (for bug fixes / features)~~
```
[ ] Bugfix
[ ] Feature
[x] Other: Error messages refactor
```
There was a typo in an error message (["proccessed"](https://github.com/nestjs/nest/blob/master/packages/core/errors/messages.ts#L24) instead of "processed").
Some messages did not clearly state what do check for (["verify whether"](https://github.com/nestjs/nest/blob/master/packages/cor …

refactor(core) rephrase error messages

---

packages/common/exceptions/im-a-teapot.exception.ts
packages/common/exceptions/index.ts

```
[ ] Bugfix
[x] Feature
```
It does not support any "I'm a teapot" exceptions :(
It adds a "ImATeapotException"
```
[ ] Yes
[x] No
```
It’s a reminder that the underlying processes of computers are still made by humans. It'd be a real shame to see 418 go.
http://save418.com/

feature(@nestjs/common) add im a teapot exception

---

packages/websockets/adapters/ws-adapter.ts

bugfix(websockets) need to handle ws unexpected connection error and log it
Fixed unhandled ws connection error in ws-adapter
No breaking changes
- [+] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [-] Tests for the changes have been added (for bug fixes / features)
- [-] Docs have been added / updated (for bug fixes / features)
```
[+] Bugfix
[ ] Feature
```
```
[ ] Yes
[+] No
```

bugfix(websockets) need to handle ws unexpected connection error and log it

---

integration/injector/e2e/circular-structure-dynamic-modules.spec.ts
integration/injector/src/circular-structure-dynamic-module/circular.module.ts
integration/injector/src/circular-structure-dynamic-module/input.service.ts
packages/core/injector/module-token-factory.ts
packages/core/test/injector/module-token-factory.spec.ts

```
[x Bugfix
[ ] Feature
```
It does not support circular structures for dynamic modules
Issue Number: #678 
Supports circular structures for dynamic modules by replacing JSON.stringify with fast-safe-stringify which allows to stringify circular structures.
```
[ ] Yes
[x] No
```

bugfix(core): Allow circular structures for dynamic module #678

---

packages/core/helpers/context-utils.ts
packages/core/test/helpers/context-utils.spec.ts
packages/core/test/router/router-execution-context.spec.ts

fix nestjs/nest#1182
```
[x] Bugfix
[ ] Feature
```
Issue Number: #1182
```
[ ] Yes
[x] No
```

bugfix(core) change initial context arguments from null to undefined

---

packages/websockets/adapters/ws-adapter.ts

sending messages to ws client only if it in open state
no breaking changes
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

websockets(bug) send message to client only in open state

---

packages/common/services/logger.service.ts
packages/core/exceptions/exceptions-handler.ts
packages/core/injector/injector.ts
packages/core/injector/module-ref.ts
packages/websockets/exceptions/ws-exceptions-handler.ts

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

refactor: remove void 0 not necessary

---

packages/core/errors/exceptions/undefined-dependency.exception.ts
packages/core/errors/exceptions/unknown-dependencies.exception.ts
packages/core/errors/messages.ts
packages/core/injector/injector.ts
packages/core/test/errors/test/messages.spec.ts

```
[ ] Bugfix
[x] Feature
```
The error when a injection dependency is missing does not show from which Module it is talking about
It tries to parse the current module context name and shows the error message (note the `CatsModule` in the message):
```
[Nest] 20205   - 2018-10-2 11:56:51   [ExceptionHandler] Nest can't resolve dependencies of the CatsController (?). Please make sure that the argument at index [0] is available in the CatsModule context. +27ms
```
In case the module …

feature(core): Add module context name to UnknownDependenciesMessage

---

CONTRIBUTING.md

```
[x] Bugfix
[ ] Feature
```
Current version of contributing was broken. There is no way (I think) to use comments inside of lists in markdown. The old version is the one on the left. Also I've commented out Code of Conduct from list because it is not ready yet.
```
[ ] Yes
[x] No
```
I wasn't able to run integration tests because of this problem:
Node version: v8.12.0
I've tried to run tests using scripts (prepare, test, run-integration).
By the way - great work Kamil 🚀

docs(contributing) fix comments issues in lists

---

packages/core/errors/messages.ts

Fixes the url in INVALID_MODULE_MESSAGE.
This closes #1369
```
[x] Bugfix
[ ] Feature
```
Message links to https://docs.nestjs.com/advanced/circular-dependency, redirecting to docs homepage
Issue Number: #1369 
Message correctly links to https://docs.nestjs.com/fundamentals/circular-dependency
```
[ ] Yes
[x] No
```

bugfix(core) update url for circular dependency in error message

---

package-lock.json
package.json
packages/common/pipes/validation.pipe.ts
packages/common/test/pipes/validation.pipe.spec.ts
sample/01-cats-app/src/cats/cats.controller.ts

allows plainToClass to expose class properties to defined groups as per issue #1374
- [ x ] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [ x ] Tests for the changes have been added (for bug fixes / features)
```
[ ] Bugfix
[ x ] Feature
```
plainToClass has no facility for following rules in Expose decorators regarding groups
Issue Number: 1374
a new property "transformOptions" on the ValidationPipeOptions class is passed into plainToClass so …

feature(common): add transformOptions to ValidationPipeOptions

---

packages/common/interfaces/http/http-server.interface.ts
packages/common/interfaces/nest-express-application.interface.ts
packages/core/adapters/express-adapter.ts
packages/core/nest-application.ts

In Express, you can set a string or an array of string as
base view paths. The views are looked up in the order they occur in
the array. The ExpressAdapter only allowed for a single string, now it
accepts an array of strings as well.
closes #1513
Since this was just a typing issue, I'm not sure if this has to be tested. There was no unit test for it and since it is an express library feature it does not need to be integration tested IMO.
code docs only though
```
[ ] Bugfix
[x] Feature
```
Issue …

feature(core): allow for multiple view dirs in Express

---

packages/microservices/server/server-grpc.ts

```
[x] Bugfix
[ ] Feature
```
The proto definition produced by @grpc/proto-loader may have null value field, which will cause error.
```
syntax = "proto3";
message ProtoMessage {
string param = 0x1;
}
```
The above message will generate following proto definition, which has null value field `options`.
```
{
ProtoMessage: {
format: 'Protocol Buffer 3 DescriptorProto',
type: {
field: [{
name: 'param',
extendee: '',
number: 1,
label: 'LABEL_OPTIONAL',
type: 'TYPE_STRING',
typeName: '',
defaultValue: '', …
```

bugfix(grpc) Handle null value in proto definition

---

packages/common/decorators/http/request-mapping.decorator.ts
packages/common/interfaces/request-mapping-metadata.interface.ts
packages/common/test/decorators/request-mapping.decorator.spec.ts
packages/common/test/decorators/route-params.decorator.spec.ts
packages/core/middleware/routes-mapper.ts
packages/core/router/router-explorer.ts
packages/core/test/router/router-explorer.spec.ts

This feature was requested in the issue #1343. When routing, besides using a single string, you can
now use an array of strings in the Post, Get, ... decorators.
```
[ ] Bugfix
[X] Feature
```
Issue Number: #1343
When routing, besides using a single string, you can now use an array of strings in the Post, Get, ... decorators.
```
[ ] Yes
[X] No
```

feature(core): allow Array in request mapping decorator

---

packages/core/errors/exceptions/unknown-dependencies.exception.ts
packages/core/errors/messages.ts
packages/core/injector/injector.ts
packages/core/test/errors/test/messages.spec.ts

```
[x] Bugfix
[ ] Feature
```
When using a `Symbol` as provide it won't print the `UnknownDependencyException` message correctly
e.g.
```
[Nest] 31114   - 2019-2-13 17:08:35   [ExceptionHandler] Cannot convert a Symbol value to a string +1ms
TypeError: Cannot convert a Symbol value to a string
at Object.exports.UNKNOWN_DEPENDENCIES_MESSAGE (/home/user/project/node_modules/@nestjs/core/errors/messages.js:25:61)
```
Issue Number: #1551
Will print the error like this:
```
Nest can't resolve dependencies …
```

fix(@nestjs/core): Display Symbol in UnknownDependencyException

---

integration/hooks/e2e/on-app-shutdown.spec.ts
integration/hooks/src/main.ts
packages/common/enums/index.ts
packages/common/enums/shutdown-signal.enum.ts
packages/common/interfaces/nest-application-context.interface.ts
packages/core/constants.ts
packages/core/nest-application-context.ts
packages/core/nest-application.ts

```
[x] Bugfix
[ ] Feature
```
Gets a memory leak error message when running Nest in e2e tests because it is listening to too many `process.on`
Added the following function to `NestApplicationContext`:
```ts
/**
* Enables the usage of shutdown hooks. Will call the
* `onApplicationShutdown` function of a provider if the
* process receives a shutdown signal.
*
* @returns {this} The Nest application context instance
*/
enableShutdownHooks(signals?: ShutdownSignal[] | string[]): this;
```
```
[ ] Yes
[x] …
```

[6.0.0-next] fix(@nestjs/core) process memory leak on application shutdown in e2e tests

---

sample/23-type-graphql/src/recipes/dto/new-recipe.input.ts

It is a simple improvement of the sample-23.
As discussed in #1616, there should be `isOptional()` decorator so GraphQL and ClassValidator validations will be in line.

Add missing isOptional() on optional field in Sample-23

---

packages/core/router/routes-resolver.ts
packages/core/test/router/routes-resolver.spec.ts

```
[x] Bugfix
[ ] Feature
```
The path is being composed by appending `basePath` to `path`. `basePath` is set through the  `setGlobalPrefix` method, therefore path should be `path = path ? basePath + path : basePath`
```
[ ] Yes
[x] No
```

bugfix(core): fixed basePath issue with routes-resolver

---

integration/hooks/e2e/lifecycle-hook-order.spec.ts

```
[ ] Bugfix
[x] Feature
```
The order of the lifecycle events is not backed by any test
Added e2e test which checks which hook gets called in which order.
`OnModuleInit -> OnApplicationBootstrap -> OnModuleClose -> OnApplicationShutdown`.
If this is not the expected behavior, we would have to change the order.
Related pr: [docs.nestjs.com#267](https://github.com/nestjs/docs.nestjs.com/pull/267)
```
[ ] Yes
[x] No
```

test(@nestjs/core): Check lifecycle hook order

---

sample/22-graphql-prisma/src/posts/posts.resolver.ts

```
[ ] Bugfix
[ ] Feature
```
As the title said, this PR is to rename the method in posts resolver to match the context in sample/22-graphql-prisma
```typescript
// Before
@Subscription('post')
onUserMutation(@Args() args, @Info() info) {
return this.prisma.subscription.post(args, info);
}
```
```typescript
// After
@Subscription('post')
onPostMutation(@Args() args, @Info() info) {
return this.prisma.subscription.post(args, info);
}
```
```
[ ] Yes
[x] No
```

refactor(sample/22): Update the method name in posts resolver to match the context

---

integration/microservices/e2e/sum-rmq.spec.ts
integration/microservices/src/rmq/rmq-broadcast.controller.ts
integration/microservices/src/rmq/rmq.controller.ts
packages/common/interfaces/microservices/microservice-configuration.interface.ts
packages/microservices/client/client-rmq.ts
packages/microservices/constants.ts
packages/microservices/interfaces/microservice-configuration.interface.ts
packages/microservices/server/server-rmq.ts

```
[ ] Bugfix
[x] Feature
```
You cannot specify the socket (connection) options detailed in https://www.squaremobius.net/amqp.node/channel_api.html#connect
You will now be able to specify the socket options (i.e. adding noDelay)
```
[ ] Yes
[x] No
```
I came across this not being possible when I was looking at tuning our system, so decided to add it!

Add socketOptions to RMQ connection for client and server

---

packages/common/pipes/validation.pipe.ts
packages/common/test/pipes/validation.pipe.spec.ts

If an optional property has an allowed null value it is now considered when stripping proto props.
```
[X] Bugfix
[ ] Feature
```
Issue Number: #2238
```
[ ] Yes
[X] No
```

bugfix(common) Stripping proto properties works with null values

---

sample/19-auth/src/auth/auth.module.ts

```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: remove deprecation warning
```
Nest prints the following warning when signing a token
[JwtService] "secretOrPrivateKey" has been deprecated, please use the new explicit "secretOrKeyProvider" or use "privateKey"/"publicKey" exclusively.
No warning is printed
```
[ ] Yes
[x] No
```

fix(sample): Update sample to avoid deprecated secretOrPrivateKey

---

integration/microservices/e2e/orders-grpc.spec.ts
integration/microservices/src/grpc-advanced/advanced.grpc.controller.ts
integration/microservices/src/grpc-advanced/proto/common/item_types.proto
integration/microservices/src/grpc-advanced/proto/common/shipment_types.proto
integration/microservices/src/grpc-advanced/proto/orders/message.proto
integration/microservices/src/grpc-advanced/proto/orders/service.proto
integration/microservices/src/grpc-advanced/proto/root.proto

```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe:
```
Tests added for protobuf namespaced case:
- loading with a single root file
- namespaced dependencies in proto
- `@Client` configuration load with namespace extension
- Stream handlers
Currently only simplified proto loading and tests introduced.
A little bit more tests for advanced protobuf conception introduced, along with proto examples.
```
[ ] Yes
[X] No
```

gRPC Advanced protobuf related tests added to match documentation update coming for microservices/gRPC

---

packages/microservices/client/client-proxy-factory.ts

```
[ ] Bugfix
[x] Feature
```
At the moment `ClientProxyFactory.create` will always return the type `ClientProxy & Closeable`. Therefore it will not take the given `transport` option into consideration, even though we would know what type should be returned.   
```ts
const client = ClientProxyFactory.create({ transport: Transport.GRPC, options: { ... }); // The type is `ClientProxy & Closeable`
// To get the correct type you have to use this workaround
const grpcClient = (client as any) as ClientGrpc; …
```

feature(microservices): Return correct client type in ClientProxyFactory

---

packages/common/pipes/validation.pipe.ts

No matter what the reason is to not validate custom decorators, you should be able to at least provide an option
```
[ ] Bugfix
[X] Feature
```
Issue Number: #2010
You are required to create a new validation pipe for custom decorators. You cannot use the build in one.
You have the option to allow the validation of custom decorators.
```
[ ] Yes
[X] No
```

feature(common): add option to allow validation of custom decorators

---

.github/FUNDING.yml

chore() Fixes broken funding link for open collective
```
[ ] Bugfix
[ ] Feature
```
The "Sponsor" github link doesn't go to the open collective page for nest.
Should go to the https://opencollective.com/nest page now!
```
[ ] Yes
[x] No
```

Fixes Github Sponsor/Funding Link

---

packages/microservices/client/client-grpc.ts

Passing down credentials options into grpc-client lead to crash of the server.
Issue Number: no issue
Everything works well.
Reproduction here: https://github.com/tychota/grpc-docker-envoy
Try to do: `make`
- works with patch-packages hotfix: https://github.com/tychota/grpc-docker-envoy/commit/69ad72ab4d3f0887a9c831270d2caa856d2f5138#diff-5713bb8c26392aacc0319825d4344daa
- does not works without

Fix "Channel options must be an object with (...) string values"

---

packages/microservices/client/client-proxy.ts
packages/microservices/interfaces/index.ts
packages/microservices/interfaces/pattern.interface.ts
packages/microservices/server/server.ts
packages/microservices/test/client/client-proxy.spec.ts
packages/microservices/test/server/server.spec.ts
packages/microservices/test/utils/msvc.util.spec.ts
packages/microservices/utils/index.ts
packages/microservices/utils/msvc.util.ts

- [ x ] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [ x ] Tests for the changes have been added (for bug fixes / features)
```
[ x ] Bugfix
[ x ] Feature
```
When we `send`/`emit` request according to some `object` pattern, pattern doesn’t sort pattern’s fields . Pattern:
```
{ controller: `main`, service: `users`, use: `addUser` }
```
doesn’t equal:
```
{ service: `users`, controller: `main`, use: `addUser` }
```
Thus, if we try to catch a …

Microservices: Order of pattern fields

---

packages/platform-express/multer/interceptors/any-files.interceptor.ts
packages/platform-express/test/multer/interceptors/any-files.interceptor.spec.ts

```
[ ] Bugfix
[x] Feature
```
If you receive a multipart request with random names of your files (e.g. uuid) you cannot gather all of them. But Multer allows it with [any](https://github.com/expressjs/multer#any).
An interceptor for the multer [any](https://github.com/expressjs/multer#any) is now available.
```
[ ] Yes
[x] No
```

feat(Multer): Add any file interceptor

---

packages/common/exceptions/http.exception.ts
packages/common/test/exceptions/http.exception.spec.ts
packages/microservices/exceptions/rpc-exception.ts
packages/microservices/test/exceptions/rpc-exception.spec.ts
packages/websockets/errors/ws-exception.ts
packages/websockets/test/exceptions/ws-exception.spec.ts

- [ X ] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [ X ] Tests for the changes have been added (for bug fixes / features)
```
[ X ] Bugfix
[ ] Feature
```
When trying to print the error it resolves to 'Error: [object Object]' which is unhelpful and means that the error objects are not serializable.
This adds a toString() function to HttpException that will serialize only when the message is an object. It does not modify anything other than …

Bugfix: Make errors serializable by default

---

packages/core/nest-application.ts

NestApplication.close() was not always closing the port after promise resolve, because of the missing `await` in implementation. This commit fixes the problem.
```
[x] Bugfix
[ ] Feature
```
`NestApplication.close()` is not always closing the port after promise resolve, because of the missing `await` in implementation.
This causes sequential application create-close cycles in E2E tests to fail with "Address already in use" error, because currently `await app.close()` does not guarantee that the port …

bugfix(core): fix missing await in NestApplication.close()

---

packages/platform-express/multer/interceptors/index.ts

This interceptor is referenced in the doc, it should be exported properly
```
[X] Bugfix
[ ] Feature
```
This code fails with `@nestjs/platform-express"' has no exported member 'AnyFilesInterceptor'.`:
```ts
import { AnyFilesInterceptor } from '@nestjs/platform-express';
```
This code succeeds
```ts
import { AnyFilesInterceptor } from '@nestjs/platform-express';
```
```
[ ] Yes
[X] No
```

bugfix(Multer) export AnyFilesInterceptor

---

integration/hooks/e2e/on-app-boostrap.spec.ts
integration/hooks/e2e/on-module-destroy.spec.ts
integration/hooks/e2e/on-module-init.spec.ts
packages/core/hooks/on-app-bootstrap.hook.ts
packages/core/hooks/on-app-shutdown.hook.ts
packages/core/hooks/on-module-destroy.hook.ts
packages/core/hooks/on-module-init.hook.ts

Fixes #1252
```
[x] Bugfix
[ ] Feature
```
See issue
Issue Number: #1252 
It does not call `onModuleInit`, `onApplicationBootstrap`, `onApplicationShutdown` or `onModuleDestroy` if it is of type `null`.
```
[ ] Yes
[x] No
```

fix(core): Do not call onModuleInit if is null

---

packages/microservices/nest-microservice.ts

```
[X] Bugfix
[ ] Feature
```
Issue Number: #1364 
- isTerminated value is updated during close
```
[ ] Yes
[X] No
```

bugfix(microservices): update isTerminated during close

---

integration/hooks/e2e/before-app-shutdown.spec.ts
integration/hooks/e2e/enable-shutdown-hook.spec.ts
integration/hooks/e2e/lifecycle-hook-order.spec.ts
integration/hooks/e2e/on-app-shutdown.spec.ts
integration/hooks/src/enable-shutdown-hooks-main.ts
packages/common/index.ts
packages/common/interfaces/before-application-shutdown.interface.ts
packages/common/interfaces/index.ts
packages/core/constants.ts
packages/core/hooks/before-app-shutdown.hook.ts
packages/core/hooks/index.ts
packages/core/nest-application-context.ts
packages/core/nest-application.ts

```
[ ] Bugfix
[x] Feature
```
At the moment only `OnApplicationShutdown` exists, which gets called once the server stops taking any requests.
`BeforeApplicationShutdown` gets called once an e.g. system signal got sent to the process, but the app still **accepts any requests**, as long as all `BeforeApplicationShutdown`-Promises have been resolved.
```
[ ] Yes
[x] No
```
The shutdown order
```
- OnModuleDestroy: Use to clean up an injectable (unsubscribe Observables, etc.)
- BeforeApplicationShutdown: …
```

feat(core): Add beforeApplicationShutdown hook

---

packages/common/services/logger.service.ts

At the moment only hours and minutes are logged in the default Logger implementation.
This pull request add seconds to default logger format.
Note that I don't want to override the whole logger service. It's pretty nice, I just want another timestamp format
```
[ ] Bugfix
[x] Feature
```
The logger now shows seconds
```
[ ] Yes
[x] No
```

Added seconds to logger timestamp

---

packages/common/decorators/http/index.ts
packages/common/decorators/http/redirect.decorator.ts
packages/common/interfaces/http/http-server.interface.ts
packages/common/test/decorators/redirect.decorator.spec.ts
packages/core/adapters/http-adapter.ts
packages/core/helpers/handler-metadata-storage.ts
packages/core/router/router-execution-context.ts
packages/core/router/router-response-controller.ts
packages/core/test/router/router-execution-context.spec.ts
packages/core/test/utils/noop-adapter.spec.ts
packages/platform-express/adapters/express-adapter.ts
packages/platform-fastify/adapters/fastify-adapter.ts

No docs yet
Exposes `@Redirect()` decorator
```typescript
@Redirect(url: string, statusCode?: number)
```
Redirects to the specified `url`
If no `statusCode`, sends `TEMPORARY_REDIRECT` (307)
Method can return an object like 
`{
statusCode: 302,
url: 'http://nestjs.com'
}`
which will override the decorator parameters.
```
```
[ ] Bugfix
[X] Feature
```
```
[ ] Yes
[X] No
```
Need help with two failing unit tests:
```
1) RouterExecutionContext createHandleResponseFn when …

feature(redirect decorator) add redirect decorator

---

integration/hello-world/e2e/middleware-execute-order.spec.ts
packages/core/injector/module.ts
packages/core/middleware/middleware-module.ts
packages/core/test/injector/module.spec.ts

```
[ ] Bugfix
[x] Feature
```
Issue Number: 1451
```
[ ] Yes
[x] No
```

feat(@nestjs/core): execute middleware of dependent modules first. #1451

---

packages/common/decorators/core/controller.decorator.ts

This results in properly generated d.ts files, from which tslint won't complain about no-unsafe-any in controllers.
```
[ ] Bugfix
[ ] Feature
```
Applying ```@Controller()``` or ```@Controller(prefix)``` results in "no-unsafe-any" warning from tslint.
The warnings should be gone, now that the return type is explicitly not any.
```
[ ] Yes
[x] No
```
There is an issue on tslint's side about this:
https://github.com/palantir/tslint/issues/3784
As you can see there, Angular was also …

style(common): Added return types to Controller decorator overloads

---

packages/common/pipes/parse-int.pipe.ts

handle `number` as `string` instead of throw an error
values may be parsed by other global pipes provided by other modules
we expect `ParseIntPipe` to return int value. it's doesn't break the logic.
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

fix(common): `ParseIntPipe` handle number value

---

packages/microservices/server/server-rmq.ts

socketOptions are currently being ignored when creating
a rabbitMQ microservice and client. This PR correctly passes
socketOptions to external libraries.
Fixes #2887
```
[x] Bugfix
[ ] Feature
```
Issue Number: #2887 
socketOptions are correctly passed to external libraries.
```
[ ] Yes
[x] No
```

bugfix(microservices) respect socketOptions for rabbitmq tls

---

packages/microservices/client/client-rmq.ts

socketOptions are currently being ignored when creating
a rabbitMQ client (server was fixed in #2889). This PR correctly passes
socketOptions to external libraries.
Fixes #2887
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

bugfix(microservices) fix rmq client socketOptions

---

packages/core/helpers/optional-require.ts
packages/core/nest-application.ts
packages/core/package.json
packages/microservices/nest-microservice.ts
packages/microservices/package.json

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

refactor() remove optional package

---

packages/common/interfaces/external/validator-options.interface.ts

```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

fix(common): class-validator interface v0.10.1

---

sample/13-mongo-typeorm/src/app.module.ts

The entity should be imported manually, as the manual states.
```
[x] Bugfix
[ ] Feature
```
The entity cannot be loaded using the import syntax.
The entities are loaded.
```
[ ] Yes
[ x] No
```

Fix entity import

---

sample/12-graphql-apollo/src/cats/cats.service.ts

create cat having property named id
```
[x] Bugfix
[ ] Feature
```
Issue Number: #3237 
Bugfix in graphql sample. Added id property using length of cats array when create cat.
```
[ ] Yes
[x] No
```

bugfix(sample): fix graphql sample bug (#3237)

---

CONTRIBUTING.md

```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: contributing guide changes.
```
When following the contribution guide (CONTRIBUTING.md), attempts to commit with type `bugfix` (e.g. `bugfix(): foo`) will be rejected by commitlint.
Update commit type in CONTRIBUTING.md from `bugfix` to `fix`. Since `bugfix` is not included in commitlint rule, and get rejected upon trying to commit.
```
[ ] Yes
[x] No
```

docs(): update commit type "bugfix" to "fix"

---

packages/core/errors/messages.ts

```
[ ] Bugfix
[ ] Feature
```
If `INVALID_MODULE_MESSAGE` is displayed, the editor will display the following:
If developers click on a link in the code editor, the wrong link with a period show in browsers.
If developers click on a link in the code editor, the correct link with a period show in browsers.
```
[ ] Yes
[x] No
```
I use VSCode.

Fix: Delete disuse period

---

packages/common/cache/cache.constants.ts
packages/common/cache/decorators/cache-ttl.decorator.ts
packages/common/cache/decorators/index.ts
packages/common/cache/interceptors/cache.interceptor.ts
packages/common/package-lock.json
packages/common/test/decorators/cache.decorator.spec.ts

- [✓] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [✓] Tests for the changes have been added (for bug fixes / features)
- [   ] Docs have been added / updated (for bug fixes / features)
The `CacheTTL` decorator has been added to controller methods for adding additional cache features. This allows the user to set the Cache TTL before it's set in it's cache store.
Additionally, `@CacheKey()` and `@CacheTTL()` decorator usage with `@CacheInterceptor()` take priority over global Cache configuration defaults. This allows for sensible Global Caching defaults, with controller specific cache overrides.
```
[ ] Bugfix
[✓] Feature
[ ] …
```

feature(common) Add CacheTTL decorator. Cache decorators priority over global defaults.

---

packages/common/decorators/core/apply-decorators.ts
packages/common/decorators/core/index.ts
packages/common/test/decorators/apply-decorators.spec.ts

A new helper method.
```
[ ] Bugfix
[X] Feature
```
Issue Number: #3104
Could use helper method to combine multiple decorators at once.
For example:
```ts
// auth.decorator.ts
import { applyDecorators, NestCustomDecorator } from '@nestjs/core';
export function Auth(
roles: UserRole | UserRole[],
): NestCustomDecorator {
return applyDecorators(
SetMetadata('roles', Array.isArray(roles) ? roles : [roles]),
UseGuards(AuthGuard),
ApiBearerAuth(),
ApiUnauthorizedResponse({ description: 'Unauthorized' }),
); …
```

feat(apply-decorators)

---

integration/nest-application/get-url/.gitignore
integration/nest-application/get-url/e2e/express.spec.ts
integration/nest-application/get-url/e2e/fastify.spec.ts
integration/nest-application/get-url/e2e/utils.ts
integration/nest-application/get-url/package-lock.json
integration/nest-application/get-url/package.json
integration/nest-application/get-url/src/app.controller.ts
integration/nest-application/get-url/src/app.module.ts
integration/nest-application/get-url/src/app.service.ts
integration/nest-application/get-url/tsconfig.json
integration/nest-application/get-url/tslint.json
packages/common/interfaces/nest-application.interface.ts
packages/core/constants.ts
packages/core/nest-application.ts

```
[ ] Bugfix
[x] Feature
```
Currently, there is no default behavior for consistently getting the server's url.
Issue Number: #3010 
After running `await app.listen(<port>)` you can add `const url = await app.getUrl()` and you will receive back a server address in the form of `http(s)://[::1]:3000` or `http(s)://127.0.0.1:3000` depending on if the server is inherently running on IPv6 or IPv4.
By default, Express runs on IPv6 and Fastify runs on IPv4, so both methods needed to be accounted for. The …

feat(core): add getUrl method to nest-applicaiton

---

packages/microservices/server/server-rmq.ts
packages/microservices/server/server.ts

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

fix applying falsy options from config

---

packages/platform-socket.io/adapters/io-adapter.ts

```
[ ] Bugfix
[x] Feature
```
When using socket.io we can simply return some data from our `@SubscribeMessage()`-annoted method, causing the data to be automatically send back to the client using socket.io's acknowledgement feature.
However, in case an exception is thrown, for example by the `ValidationPipe`, that ack-feature isn't used at all, but instead a generic 'exception' message is emitted by the `BaseWsExceptionFilter`. That is totally fine for the default behavior, since we cannot force the …

feature(platform-socket.io): pass ack to message handler

---

packages/common/decorators/http/route-params.decorator.ts
packages/common/enums/route-paramtypes.enum.ts
packages/core/router/route-params-factory.ts
packages/core/test/router/route-params-factory.spec.ts

```
[ ] Bugfix
[x] Feature
```
Added ip param decorator for HTTP route handlers.
```
[ ] Yes
[x] No
```

feat(): add ip route param

---

packages/common/services/logger.service.ts

This fixes the issue that in PM2 (at least when running in Windows) the logging lines break at the "stdout.write() border".
```
[x] Bugfix
[ ] Feature
```
The default `LoggerService` multiple times calls `process.stdout.write()` per logging line. This seems to confuse the process manager [PM2](https://pm2.keymetrics.io/)'s logging system (the full logging message is split into 2 or more parts).
An example screenshot:
I've refactored `printMessage()` so that it concatenates the logging string first and …

fix(common): Single `stdout.write()` call per logging in default `Logger`

---

integration/scopes/e2e/inject-inquirer.spec.ts
integration/scopes/src/inject-inquirer/hello-request/hello-request.service.ts
integration/scopes/src/inject-inquirer/hello-request/request-logger.service.ts
integration/scopes/src/inject-inquirer/hello-transient/hello-transient.service.ts
integration/scopes/src/inject-inquirer/hello-transient/transient-logger.service.ts
integration/scopes/src/inject-inquirer/hello.controller.ts
integration/scopes/src/inject-inquirer/hello.module.ts
packages/core/injector/index.ts
packages/core/injector/injector.ts
packages/core/injector/inquirer/index.ts
packages/core/injector/inquirer/inquirer-constants.ts
packages/core/injector/inquirer/inquirer-providers.ts
packages/core/injector/internal-core-module.ts

```
[ ] Bugfix
[x] Feature
```
In a transient injectable, the current instance is bound to the context in which it is instanciated.
However, there is no way I am aware of to configure the behaviour of the injected injectable at the intanciation level
This PR introduce a way to achieve this intention by adding a new provider in the InternalCoreModule.
The injection of the `INQUIRER` symbol token results in the inquirer to be injected into our transient injectable.
```ts
@Inject(INQUIRER) inquirer
```
An …

feat(@nestjs/core): Add Transient Inquirer Injection

---

packages/common/cache/interfaces/cache-manager.interface.ts

- introducing the options with time to live for the set function in cache-manager
```
[ ] Bugfix
[x] Feature
```
There is no possibility to set a custom time to live on **set** if I use the types.
Possible to use TTL for set function on cache store type
```
[ ] Yes
[x] No
```

feat(cache-manager): extend cache-store interface

---

packages/core/router/router-explorer.ts

refactor to common proxy variable - RouterExplorer applyCallbackToRouter
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

refactor(core): remove duplicated code

---

packages/microservices/client/client-rmq.ts
packages/microservices/server/server-rmq.ts

#3138, #2323, #2337
```
[x] Bugfix
[ ] Feature
```
Issue Number: #3138, #2323, #2337
1. `server-rmq.js` - reconnect only one-off if RabbitMQ disconnects and connects again
2. `client-rmq.js` - set a new connection if RabbitMQ disconnects and connects again
```
[ ] Yes
[x] No
```

fix(RabbitMQ Microservice): "PRECONDITION_FAILED - reply consumer already set"

---

packages/core/hooks/before-app-shutdown.hook.ts
packages/core/hooks/on-app-bootstrap.hook.ts
packages/core/hooks/on-app-shutdown.hook.ts
packages/core/hooks/on-module-destroy.hook.ts
packages/core/hooks/on-module-init.hook.ts
packages/core/injector/instance-wrapper.ts
packages/core/injector/module.ts
packages/core/test/injector/module.spec.ts

```
[x] Bugfix
[ ] Feature
```
Issue Number: #3182 
Hook methods will not be called for providers that are registered as aliases (using the new `isAlias` flag).
```
[ ] Yes
[x] No
```

fix(core): fix hooks being called when registered as alias

---

sample/05-sql-typeorm/docker-compose.yml
sample/05-sql-typeorm/src/photo/photo.service.ts
sample/06-mongoose/src/cats/cats.service.ts
sample/07-sequelize/src/cats/cats.controller.ts
sample/07-sequelize/src/cats/cats.service.ts
sample/12-graphql-apollo/src/cats/cats.resolvers.ts
sample/13-mongo-typeorm/src/photo/photo.service.ts
sample/14-mongoose-base/src/cats/cats.service.ts
sample/22-graphql-prisma/src/posts/posts.resolver.ts

Remove redundant await in samples 05, 06, 07, 12, 13, 14, 22
Remove redundant YML key in sample 05
```
[X] Bugfix
[ ] Feature
```
1) `return await` is not a recommended pattern
2) There was a duplicate key in a YML file
1) return without await
2) there is no longer a duplicate key
```
[ ] Yes
[X] No
```

fix(sample): Address linter warnings

---

packages/common/constants.ts
packages/common/decorators/core/controller.decorator.ts
packages/core/router/router-explorer.ts

```
[ ] Bugfix
[x] Feature
```
Issue Number: #963
Add's a possible fix for enabling/disabling the use of global prefix path for controllers.
```ts
@Controller({
path: 'withoutGlobal'
useGlobalPrefix: false  // true by default
})
```
```
[ ] Yes
[x] No
```
I am not sure if this is a recommended fix, but I feel is better than `exclude: ` for each path (as suggested in that issue), since this is controller based and not based on request methods or the respective path values.
Please let me know your take …

feat(common/core): Added useGlobalPrefix option for Controllers

---

packages/platform-express/adapters/express-adapter.ts

```
[X] Bugfix
[ ] Feature
```
When closing a Nest Express application, the cleanup process does not wait the end of http server.
The Express Adapter return a promise for the close function (like the Fastify adapter) and the application waits that the http server cleanup all its connection.
```
[ ] Yes
[X] No
```

Return a promise to wait the end of express http server in close function of adapter

---

integration/hello-world/e2e/express-multiple.spec.ts
integration/hello-world/e2e/fastify-multiple.spec.ts
packages/common/interfaces/http/http-server.interface.ts
packages/common/interfaces/nest-application.interface.ts
packages/core/adapters/http-adapter.ts
packages/core/nest-application.ts
packages/core/router/routes-resolver.ts
packages/core/test/utils/noop-adapter.spec.ts
packages/platform-express/adapters/express-adapter.ts
packages/platform-fastify/adapters/fastify-adapter.ts

Added the application's global prefix to the error and not found handlers, and enabled the adapters to register one based on prefix.
- [N/A] Docs have been added / updated (for bug fixes / features) - The error handler functions and their behaviour is not documented in general.
```
[x] Bugfix
[x] Feature
```
Attempting to register two applications on the same adapter leads to an error handler conflict, even if the applications have distinct global prefixes set.
The error handler is …

feature(http-adapter) Added the application's global prefix to error handlers and global middlewares

---

packages/microservices/client/client-nats.ts
packages/microservices/server/server-nats.ts

```
[x] Bugfix
[ ] Feature
```
It's currently impossible to write a deserializer that reliably handles transforming the shape of an inbound (non-nest-conforming) NATS message to nest-conforming.
This makes it impossible to write fully interoperable NATS consumers in Nest.  For example, assume a distributed application system utilizes NATS messages to make "requests" (a NATS abstraction that publishes a message with a `replyTo` field that the message recipient uses to direct a published message …

bugfix (@nestjs/microservices) pass replyTo to deserializer

---

packages/common/http/http.service.ts

when response type stream is set, the node stream is ended early as `subscriber.complete()` -> `cancelSource.cancel()` is called in sequence.
The better approach to fix this is to wrap the stream with an observable, but that'll be a lot of code.
So a simpler approach is to ignore request cancellation on stream response type.
fixes #4014
```
[*] Bugfix
[ ] Feature
```
```
[ ] Yes
[*] No
```

fix(common): http service should not cancel when response type is stream

---

packages/common/pipes/parse-int.pipe.ts
packages/common/test/pipes/parse-int.pipe.spec.ts

```
[ ] Bugfix
[X] Feature
```
Issue Number: #3901
`ParseIntPipe` has an optional exceptionfactory (similar to `ValidationPipe` e.g.)
```
[ ] Yes
[X] No
```

feat(common): ParseIntPipe has an optional exceptionfactory

---

packages/common/exceptions/http.exception.ts
packages/common/test/exceptions/http.exception.spec.ts

Originally, the default output of `HTTPException` is `{statusCode,
message}`, but the default output for another specific exception
(e.g., `BadRequestException`) is `{statusCode, error}`. These changes
make them behave consistently.
Closes #3454
Closes #4044
All exceptions by default now return `{statusCode, message}`.
```
[x] Bugfix
[ ] Feature
```
The default output of HTTPException is `{statusCode, message}`, but the default output for another specific exception (e.g., BadRequestException) is …

fix(common): standardizes http exceptions output

---

packages/microservices/server/server-grpc.ts
packages/microservices/test/server/server-grpc.spec.ts

```
[ ] Bugfix
[x] Feature
```
Issue Number: #4158 
The metadata of the stream is now passed to the grpc method handler as a second argument.
```
[ ] Yes
[x] No
```

feat(microservices): A metadata to arguments for grpc stream method

---

packages/microservices/client/client-kafka.ts
packages/microservices/interfaces/microservice-configuration.interface.ts
packages/microservices/server/server-kafka.ts
packages/microservices/test/client/client-kafka.spec.ts
packages/microservices/test/server/server-kafka.spec.ts

```
[ ] Bugfix
[x] Feature
```
Issue Number: https://github.com/nestjs/nest/issues/3739
KafkaOptions includes support for the [kafka.js subscribe fromBeginning option](https://kafka.js.org/docs/consuming#a-name-from-beginning-a-frombeginning).
```
[ ] Yes
[x] No
```

feat(microservices): add subscribe and from beginning to kafka options

---

packages/core/router/router-explorer.ts
packages/core/router/routes-resolver.ts

```
[ ] Bugfix
[x] Feature
```
Part 1:
Currently the logging does not prepend the basePath to the RouterExplorer on the Nest application startup, ex:
```
[RoutesResolver] TestController {/test}:
[RouterExplorer] Mapped {/, GET} route
```
Here the TestController has a basePath of `/test`, with a single `@Get()` inside. When the RouterExplorer is logged, it looks likes you could get the TestController's `@Get()` from directly calling the root get, and not on `/test`
Part 2:
If you defined a controllers …

feat(core): Update routers logging to include basePath and remove trailing slash

---

packages/common/exceptions/bad-gateway.exception.ts
packages/common/exceptions/bad-request.exception.ts
packages/common/exceptions/conflict.exception.ts
packages/common/exceptions/forbidden.exception.ts
packages/common/exceptions/gateway-timeout.exception.ts
packages/common/exceptions/gone.exception.ts
packages/common/exceptions/http-version-not-supported.exception.ts
packages/common/exceptions/http.exception.ts
packages/common/exceptions/im-a-teapot.exception.ts
packages/common/exceptions/internal-server-error.exception.ts
packages/common/exceptions/method-not-allowed.exception.ts
packages/common/exceptions/not-acceptable.exception.ts
packages/common/exceptions/not-found.exception.ts
packages/common/exceptions/not-implemented.exception.ts
packages/common/exceptions/payload-too-large.exception.ts
packages/common/exceptions/request-timeout.exception.ts
packages/common/exceptions/service-unavailable.exception.ts
packages/common/exceptions/unauthorized.exception.ts
packages/common/exceptions/unprocessable-entity.exception.ts
packages/common/exceptions/unsupported-media-type.exception.ts

Fix incorrect documentation strings for HTTP exceptions.
Closes #4042
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: incorrect documentation
```
Issue Number: #4042
Documentation strings are now correct.
```
[ ] Yes
[x] No
```
If this is merged before #4045, the documentation strings for the exceptions must be updated by #4045.
If this is merged after #4045, this PR should be updated to fix the documentation strings.

refactor(common): fix exceptions doc/var names

---

packages/microservices/client/client-grpc.ts
packages/microservices/interfaces/microservice-configuration.interface.ts
packages/microservices/server/server-grpc.ts

- [ x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
```
[ ] Bugfix
[ x] Feature
```
There is currently no way to change the default maximum metadata size for gRPC and it will always be set at the default (4KB).
Issue Number: #4237
A new `maxMetadataSize` is added on `GrpcOptions` to override the default of 4KB.
```
[ ] Yes
[ x] No
```

feat(microservices): implement server grpc max metadata size option

---

integration/microservices/e2e/sum-grpc.spec.ts
integration/microservices/src/grpc/grpc.controller.ts
packages/microservices/client/client-grpc.ts

```
[x] Bugfix
[ ] Feature
```
Calling `getService` of `ClientGrpcProxy` with multiple packages shows error  _'Channel third argument (options) must be an object with string keys and integer or string values'_. 
Which is caused by passing `ClientGrpcProxy`'s options (`GrpcOptions['options']` format) to node-grpc client's constructor. 
References:
https://github.com/grpc/grpc-node/blob/master/packages/grpc-native-core/ext/channel.cc#L226
https://github.com/grpc/grpc-node/blob/master/packages/grpc-native- …

Fix/grpc multi package client getService error

---

package.json

`-d` is not valid flag for `docker-compose down`
```
[ ] Bugfix
[ ] Feature
```
Removed invalid `-d` flag in `package.json` `test:docker:down` command
https://docs.docker.com/compose/reference/down/
Allows docker down command to work
```
[ ] Yes
[x] No
```

build(): fix invalid docker down command

---

sample/14-mongoose-base/src/cats/cats.providers.ts

```
[x] Bugfix
[ ] Feature
```
In sample 14-mongoose-base, useFactory function is declared to receive a parameter of type Connection, however the actual parameter type received is of type Mongoose. This is the type provided by databaseProviders.
This wrong code also apears in the docs: https://docs.nestjs.com/recipes/mongodb#model-injection
Issue Number: 4543
useFactory declares the correct parameter of type Mongoose.
```
[ ] Yes
[x] No
```

fix(samples):  catsProvider's useFactory param type

---

packages/common/cache/interceptors/cache.interceptor.ts

@CacheTTL(0) now sets 0 TTL on underlying cache manager. This is equivalent to a non-expiring cache key.
fixes #4447
```
[x] Bugfix
[ ] Feature
```
The CacheTTL decorator has a check for a defined TTL that returns falsey if the value is 0. This prevents the underlying cache manager accepting a TTL value of 0 which sets a non-expiring cache/no TTL.
Issue Number: #4447 
A TTL of 0 is now accepted as valid and sets the underlying cache manager TTL to 0.
```
[ ] Yes
[x] No
```

fix(common): change cache ttl decorator to set 0 value ttl

---

packages/common/test/decorators/bind.decorator.spec.ts
packages/common/test/decorators/create-param-decorator.spec.ts
packages/common/test/decorators/redirect.decorator.spec.ts
packages/core/package.json
packages/microservices/package.json
packages/microservices/test/server/server-grpc.spec.ts
packages/microservices/test/server/server-kafka.spec.ts
packages/platform-express/package.json
packages/websockets/package.json

```
[x] Bugfix
[ ] Feature
```
Issue Number: #4632 
Described in the related issue.
```
[ ] Yes
[x] No
```

test: fix tests to make them run ootb

---

packages/common/http/http.service.ts

Fix issue https://github.com/nestjs/nest/issues/4698 where a user can't provide a cancellation token to Axios through the HTTP service
.
```
[x] Bugfix
[ ] Feature
```
Issue Number: https://github.com/nestjs/nest/issues/4698
Any cancel token provided to the HTTP Service is overwritten by an internal cancel token mechanism.
The internal cancel token is created and used only when no cancel token is provided via the config object. When a user decides to handle the cancelation on its end, it should remain responsible for the cancelation and no other …

fix(common): Allow users to provide a cancellation token to http service

---

packages/common/http/http.service.ts
packages/common/test/http/http.service.spec.ts

```
[x] Bugfix
```
```
const options = {}
httpService.get('/', options).toPromise().then(() => {
// options.cancelToken is defined
})
```
Keep the old behavior and do not mutate the options object as it may cause side effects in userland. [Axios](https://github.com/axios/axios/blob/master/lib/core/Axios.js#L76) does clone the config object given.
```
[ ] Yes
[x] No
```

fix(http): remove axios config mutation

---

packages/microservices/client/client-grpc.ts

```
[x] Bugfix
[ ] Feature
```
currently the logic ignore if value grpc option is `0`
Issue Number: #4816
grpc option should be able accept `0` value
```
[ ] Yes
[ ] No
```

fix(microservices): enable grpc option value to accept 0

---

packages/common/http/http.service.ts
packages/common/test/http/http.service.spec.ts

This is a re-opening of #4803 as the code was removed in https://github.com/nestjs/nest/commit/138e2c41f0c910c77933763d6c6355bd9dd93b9a (mistake ?).
```
[x] Bugfix
```
```
const options = {}
httpService.get('/', options).toPromise().then(() => {
// options.cancelToken is defined
})
```
Keep the old behavior and do not mutate the options object as it may cause side effects in userland. [Axios](https://github.com/axios/axios/blob/master/lib/core/Axios.js#L76) does clone the config object given.
```
[ ] Yes
[x] No
```

 fix(http): remove axios config mutation #4803 

---

packages/common/serializer/class-serializer.interceptor.ts

Enable pass `ClassTransformOptions` when use `ClassSerializerInterceptor` as GlobalInterceptors.
```
const reflector = app.get<Reflector>(Reflector);
app.useGlobalInterceptors(
new ClassSerializerInterceptor(reflector, {
excludeExtraneousValues: true,
enableImplicitConversion: true
})
);
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

feat(core): add support to default  serializer options

---

packages/microservices/client/client-rmq.ts
packages/microservices/interfaces/microservice-configuration.interface.ts

```
[ ] Bugfix
[x] Feature
```
When using the AMQP service available on some cloud services, nest uses `amq. rabbitmq.reply-to` as a callback queue, and cannot be changed. However, `amq.rabbitmq.reply-to` is a feature in rabbitMq, and Not a required part of the amqp protocol, it's causing my nest app to have 404 issues,I'm coding in the to make it work, I think it should be made to work for AMQP by adding the option to make it work for the The protocol allows for better versatility. …

feat(microservices): ServerRMQ

---

packages/microservices/nest-microservice.ts

```
[x] Bugfix
[ ] Feature
```
When `NestMicroservice` app is listening to shutdown hooks via `app.enableShutdownHooks()` it does not call `server.close()` when shutdown signal is received. This causes server to still receive messages while the whole application is shutting down.
`NestMicroservice` implements `dispose()` method which is supposed to close server, same as `NestApplication`.
```
[ ] Yes
[x] No
```
ServerRMQ is heavily affected by this as it has ```noAck = true``` by default. This means it …

fix(microservices): add microservice dispose to close server on shutdown

---

packages/microservices/nest-microservice.ts

```
[x] Bugfix
[ ] Feature
```
Issue Number: #5135
Allow error inside `onModuleInit` to properly bubble up and be able to be catch inside bootstrap function.
Resolve the `UnhandledPromiseRejectionWarning` issue.
```
[ ] Yes
[x] No
```

fix(microservice): handle promise return by 'registerModules' properly

---

packages/common/pipes/validation.pipe.ts
packages/common/test/pipes/validation.pipe.spec.ts

It's possible to have multiple pipes for a single parameter, so the argument type won't necessary will be same as the original type and we need to explicitly set the type for the validation pipe
see discussion:
https://discord.com/channels/520622812742811698/520649487924985885/732209853854122055
```
[ ] Bugfix
[x] Feature
```
We can't do custom transformation and use the built-in ValidationPipe.
see discussion:
https://discord.com/channels/520622812742811698/520649487924985885/732209853854122055
Issue …

feat(common) add expected type option to validation pipe

---

packages/core/router/route-params-factory.ts

- [NA] Tests for the changes have been added (for bug fixes / features)
- [NA] Docs have been added / updated (for bug fixes / features)
```
[ ] Bugfix
[X] Feature
```
Upper case values passed to `@Header('Header-Key')` are passed to the underlying library directly (via `request.headers[data]`). This decreases usability, as developers must pass lower-case strings to the decorator -- even if their headers include upper case headers, or they prefer to for any other reason.
This single line change, …

feat(core): case insensitive headers

---

packages/microservices/client/client-kafka.ts
packages/microservices/server/server-kafka.ts

```
[x] Bugfix
[ ] Feature
```
Issue Number: https://github.com/nestjs/nest/issues/5126
The `brokers`, `clientId`, and `groupId` can now be extended from the `ClientKafka` and `ServerKafka` microservice classes.
```
[ ] Yes
[x] No
```

fix(microservices): Changed visibility of Kafka variables for extension

---

packages/common/pipes/validation.pipe.ts

```
[x] Bugfix
[ ] Feature
```
I'm using Stripe in my Nest project and for Stripe callbacks we use a raw body. The code in our codebase is like this: `async stripeCallback(@Body() rawBody: Buffer) { ... }` and because I've applied a global validation pipe, it's trying to validate a `Buffer` which should not happen.
It ignores the `Buffer` type.
```
[ ] Yes
[x] No
```

Ignore Buffer metatypes in validation pipe

---

packages/microservices/client/client-rmq.ts
packages/microservices/constants.ts
packages/microservices/interfaces/microservice-configuration.interface.ts

Add the persistent property to RmqOptions so messages do not get lost should the RabbitMQ broker restart.
```
[ ] Bugfix
[x] Feature
```
Currently when publishing or sending a message to a RabbitMQ queue the messages are not persistent, so when the RabbitMQ broker is restarted the unprocessed messages in the queue are lost.
A property is available within the `RmqOptions` to allow the persistence to be toggled.  The default value is set to false which is the current working behaviour to prevent a …

feature(microservices): Add persistent property to RmqOptions

---

packages/common/pipes/validation.pipe.ts

By having the `loadPackage` for `class-validator` and
`class-transformer` under `protected` methods, other devs can now
decide if they want to use different validation packages, like
`class-validator-multi-lang` but by default will still use the standard
`class-validator` and `class-transformer`.
fix #5542
```
[ ] Bugfix
[x] Feature
```
`ValidationPipe` loads `class-validator` and `class-transformer` in the constructor
Issue Number: #5542
`ValdiationPipe` loads `class-validator` and `class-transformer` …

feat(common): gives validation pipe protected package loads

---

packages/microservices/server/server-nats.ts
packages/microservices/test/server/server-nats.spec.ts

```
[x] Bugfix
[ ] Feature
```
Issue Number: https://github.com/nestjs/nest/issues/4874
App doesn't crash for valid request
```
[ ] Yes
[X] No
```

bugfix(microservices/nats): check replyTo channel existence

---

packages/common/interfaces/nest-application-context.interface.ts
packages/core/nest-application-context.ts

So far, the types only allowed to set the log level within the application options, and not when calling app.useLogger(), although internally they call the same method.
closes @nestjs/nest#5484
```
[x] Bugfix
```
Issue Number: #5484
Fixed types.
```
[ ] Yes
[X] No
```

fix(core): allow setting log level after app creation

---

packages/microservices/client/client-kafka.ts
packages/microservices/test/client/client-kafka.spec.ts

`producer.disconnect()` and `consumer.disconnect()` are promises.
Since they weren't being `await`ed properly, you would have Kafka code that
would attempt to execute after teardown. By waiting for the promises, those errors
go away.
Official documentation: https://kafka.js.org/docs/getting-started
Closes #4830
[Here are tests from KafkaJS showing those methods as async](https://github.com/tulios/kafkajs/blob/c025e05725a8b1badf813ea6a5231d0b8f77647a/src/consumer/__tests__/consumeMessages.spec.js#L47-L50)
```
[x] Bugfix
[ ] Feature …
```

fix(microservice/kafka): properly await disconnect promises

---

packages/common/interfaces/nest-application-context-options.interface.ts
packages/core/nest-factory.ts

```
[ ] Bugfix
[x] Feature
```
https://github.com/nestjs/nest/issues/5162
Issue Number: 5162
An abortOnError flag is added in nestApplicationContext. By default the process is aborted, but if abortOnError is set to false,
error is rethrown instead of calling process.abort() or process.exit(1)
```
[ ] Yes
[x] No
```

feat(core): Add abortOnError option in NestApplicationContextOptions

---

packages/common/pipes/validation.pipe.ts
packages/common/test/pipes/validation.pipe.spec.ts

```
[x] Bugfix
[ ] Feature
```
The `expectedType`  ignored and we use `metatype` instead.
Send the correct value to the `toValidate` method.
```
[ ] Yes
[x] No
```
n/a

fix(common): expectedType get overriden by metatype

---

sample/01-cats-app/package.json
sample/09-babel-example/package.json
sample/19-auth-jwt/package.json
sample/25-dynamic-modules/package.json
sample/26-queues/package.json
sample/27-scheduling/package.json

```
[x] Bugfix
[ ] Feature
```
The unit test file pattern includes any files containing `test` and the `ts` suffix, since `testRegex: .spec.ts` a regex and not a glob pattern.
Issue Number: #5293 
The test file pattern strictly follows the .spec.ts file suffix. This rules out .e2e-spec.ts files from unit tests. The change has been applied to all sample projects with unit tests.
```
[ ] Yes
[x] No
```

fix(test): stricten unit test file pattern

---

integration/hello-world/e2e/fastify-adapter.spec.ts
packages/platform-fastify/adapters/fastify-adapter.ts
packages/platform-fastify/interfaces/nest-fastify-application.interface.ts

```
[x] Bugfix
[ ] Feature
```
If we currently use inject() from LightMyRequest to test the application we need to call it like this:
```
const response = await app.inject({ method: 'POST', url: '/login', payload: loginPayload });
```
If we try to use the chaining API we are getting TypeScript errors like `TS2554: Expected 1 arguments, but got 0.` because of missing types.
With the chaining API (https://github.com/fastify/light-my-request#method-chaining) we can also call it in a fluent style like …

fix(platform-fastify): adds missing chaining API types for LightMyRequest inject()

---

packages/core/injector/module-token-factory.ts

Use .toString() as functions' representation.
```
[x] Bugfix
[ ] Feature
```
Issue Number:  #5140
```
[ ] Yes
[x] No
```

Use .toString() as functions' representation,  fix #5140

---

package-lock.json
packages/common/cache/decorators/cache-ttl.decorator.ts
packages/common/cache/index.ts
packages/common/cache/interceptors/cache.interceptor.ts

```
[ ] Bugfix
[x] Feature
```
In the current implementation of `@CacheTTL`, the input value is a fixed number and constant tokens of cache module are all private except `CACHE_MANAGER` so we can not set our desired value as metadata
Issue Number: #5335
1 - `@CacheTTL` decorator accept `number` or `CacheTTLHandler` as argument
```typescript
type CacheTTLHandler<T> = (ctx: T) => Promise<number> | number;
export const CacheTTL = (ttl: number | CacheTTLHandler<ExecutionContext>) => …
```

feat(common): add support for conditional cache ttl

---

packages/common/interfaces/external/kafka-options.interface.ts
packages/microservices/client/client-kafka.ts
packages/microservices/external/kafka.interface.ts
packages/microservices/server/server-kafka.ts

```
[ ] Bugfix
[X] Feature
```
Issue Number: #5633
You can add a function to set brokers.
```
[ ] Yes
[X] No
```

feat(microservices): Add BrokersFunction to KafkaConfig brokers property

---

packages/common/interfaces/external/kafka-options.interface.ts
packages/microservices/client/client-kafka.ts
packages/microservices/external/kafka.interface.ts
packages/microservices/server/server-kafka.ts

```
[ ] Bugfix
[X] Feature
```
Issue Number: #5603
You can set the clientIdPostfix for naming conventions. The default behavior steel working. ('-client', '-server')
```
[ ] Yes
[ ] No
```

feat(microservice): Add clientIdPostfix to KafkaConfig

---

packages/microservices/server/server-kafka.ts

```
[X] Bugfix
[ ] Feature
```
Issue Number: #5599
You can overwrite the KafkaServer constructor without a typescript error. 
```
[ ] Yes
[X] No
```

fix(microservice): Fix KafkaServer constructor

---

packages/common/exceptions/http.exception.ts

#5098 People relying on the message being the error and the error being the message will
see that behavior changing and this may cause some issues in their error handling. PR Checklist
Currently, while using the `createBody` static method from the `HttpException`, if the `objecOrtError` argument is not an object, then the returned object uses the `objectOrError` value in order to fill the `message` property value, and the `message` value for the `error` property value.
This feels very strange, as the signature of the method seems to not match the returned object. This behavior expands to all the Exceptions that rely on the `HttpException` class.
The changes provide consistency and …

refactor(common): change names of createBody arguments

---

integration/websockets/e2e/gateway-ack.spec.ts
packages/platform-socket.io/adapters/io-adapter.ts

Ack method is never called when no data sent to the event.
https://github.com/nestjs/nest/issues/5711
```
[x ] Bugfix
[ ] Feature
```
https://github.com/nestjs/nest/issues/5711
Issue Number: 5711
Ack method is called even if no data sent to the event.
```
[ ] Yes
[x] No
```

fix: Ack never called when no data sent

---

packages/microservices/interfaces/microservice-configuration.interface.ts

```
[x] Bugfix
[ ] Feature
```
Currently the jwt feature of NATS microservice can be used only on responder part (configured through main.ts) although the nestjs nats docs says oterwise.
Issue Number: #4356 
By adding missing options the client (requester) can use jwt too.
```
[ ] Yes
[x] No
```
Tracking [StackOverflow issue](https://stackoverflow.com/questions/64898076/jwt-auth-for-nats-in-nestjs)

Added missing options to for NATS client to use jwt

---

CONTRIBUTING.md

Update commit guideline docs based on latest commitlint configuration.
```
[ ] Bugfix
[ ] Feature
[X] Other
```
N/A
```
[ ] Yes
[X] No
```

docs(core): edit contribution guide

---

packages/common/interfaces/nest-microservice.interface.ts
packages/microservices/nest-microservice.ts

state correct return type (void) on the `NestMicroservice.listen` method
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
return type is misleading this is not a breaking-change

fix(microservices): listen method is void return type

---

packages/common/interfaces/middleware/middleware-config-proxy.interface.ts
packages/common/interfaces/middleware/middleware-consumer.interface.ts
packages/common/interfaces/nest-application.interface.ts
packages/common/interfaces/nest-microservice.interface.ts

this pr fixes some jsdoc typing in listed interfaces:
- optional parameters (see https://www.typescriptlang.org/docs/handbook/jsdoc-supported-types.html#param-and-returns)
- rest/repeatable parameters (see https://www.typescriptlang.org/docs/handbook/jsdoc-supported-types.html#more-examples and https://jsdoc.app/tags-param.html#multiple-types-and-repeatable-parameters)
- solved some type inconsistencies (type from ts definition put in jsdoc)
- removed double spaces after param keywoard
```
[ ] Bugfix
[ ] Feature
[ ] Other... Please …
```

refactor: jsdoc fixes for INestApplication, INestMicroservice, MiddlewareConsumer and MiddlewareConfigProxy

---

integration/nest-application/get-url/e2e/express.spec.ts
integration/nest-application/get-url/e2e/fastify.spec.ts
packages/core/nest-application.ts

`app.getUrl()` was throwing an error when `this.isListening`
was set to false. The value was set _after_ `this.httpServer.listen`
was called, now it is set _before_ to ensure that the `app.getUrl()`
can be called in the callback of `listen`. A regression test has
been added for this, and all tests related to the change are passing.
fix: #5798
```
[X] Bugfix
[ ] Feature
```
In the callback of `app.listen()`, `await app.getUrl()` cannot be called.
Issue Number: #5798 
In the callback of `app.listen()`, …

fix(application): makes get-url work in callback

---

packages/platform-fastify/adapters/fastify-adapter.ts
packages/platform-fastify/interfaces/nest-fastify-application.interface.ts

```
[x] Bugfix
[ ] Feature
```
Actually, [fastify](https://github.com/fastify/fastify/blob/d044549a20ddb4324f6f76c9d7f9032807cbff93/types/instance.d.ts#L50) uses port as `number | string` but we are using `parseInt(port)` to convert port to `number`. Unfortunately, Azure App service uses `pipe` name as port and it's a string (`\\.\pipe\d226d7b0-64a0-4d04-96d4-a75e1278b7a9`).
Some references:
https://richiban.uk/2019/01/09/gotchas-getting-next-js-to-run-in-azure-app-services/ …

fix: iisnode uses pipe name instead of port number

---

integration/nest-application/app-locals/e2e/express.spec.ts
integration/nest-application/app-locals/src/app.controller.ts
integration/nest-application/app-locals/src/app.module.ts
integration/nest-application/app-locals/tsconfig.json
packages/platform-express/adapters/express-adapter.ts
packages/platform-express/interfaces/nest-express-application.interface.ts

```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
Right now, there is no "convenient" way to set application-wide globals in Express-based application. We have to get the adapter first (`getHttpAdapter()`), get the underlying instance (`getInstance()`), and then set the variables there. With this change, an API has been exposed so that we can directly set them from the `app` instance. The relevant doc can be found here: https://expressjs.com/en/4x/api.html#app.locals.

feat(core): expose app.locals to express adapter

---

packages/microservices/server/server-rmq.ts

A null message is passed to callback when RabbitMQ queue is deleted.
Fixes #5683
```
[x] Bugfix
[ ] Feature
```
An exception is thrown and RMQ microservice is broken for the rest of the app's lifetime. See more details on the issue.
Issue Number: #5683
`null` message passed to callback is ignored. This part is my code fix.
Subsequently, the RMQ channel will be closed by the broker server and then rest of the existing functionality kicks in where the RMQ microservice setup is re-trigerred and it ends up …

fix(microservices): handle rmq queue deletion

---

packages/common/services/logger.service.ts

Make static property `instance`and static method `getInstance()` protected so derived classes get access to the overriden logger instance
```
[ ] Bugfix
[ ] Feature
[ x] Refactoring (no functional changes, no api changes)
```
Nest's Logger Class enables the app to override the Logger class by re-setting a static property named instance, which holds the logging instance (e.g. a winston logger instance). The static property is private by default. The access via `getInstance()` method to this instance property is also private which prevents any derived logger …

refactor(common): Make LoggerService's instance property and getInstance() method protected to allow sub-classes access to it

---

packages/common/decorators/core/controller.decorator.ts
packages/common/test/utils/shared.utils.spec.ts
packages/common/utils/shared.utils.ts
packages/core/middleware/middleware-module.ts
packages/core/middleware/routes-mapper.ts
packages/core/nest-application.ts
packages/core/router/router-explorer.ts
packages/core/router/routes-resolver.ts
packages/core/test/router/router-explorer.spec.ts
packages/core/test/router/routes-resolver.spec.ts
packages/websockets/socket-server-provider.ts

```
[ ] Bugfix
[x] Feature
```
The controller decorator doesn't support multi-path.
Issue Number: #5193
The `prefix` parameter or the `path` parameter of `ControllerOptions` both support multi-value now.
```typescript
Controller(prefix: string | string[])
interface ControllerOptions extends ScopeOptions {
path?: string | string[];
host?: string;
}
Controller({ path, host }: ControllerOptions)
```
The output log should look like the following one after provided the path alias to the controller:
``` …
```

feat(core): add support to controller path alias

---

packages/common/pipes/validation.pipe.ts
packages/common/test/pipes/validation.pipe.spec.ts

Passed the complete path of the parent property as an argument. Earlier, the information regarding the parent was getting lost due to flattening of array in case of validation of nested objects.
Closes #5380
```
[ ] Bugfix
[x] Feature
```
Issue Number: #5380 
Passed the complete path of the parent property as an argument. Earlier, the information regarding the parent was getting lost due to flattening of array in case of validation of nested objects.
```
[ ] Yes
[x] No
```

feat(common): specify parent property for validation of nested objects

---

packages/common/package.json
packages/core/package.json
packages/microservices/package.json
packages/testing/package.json
packages/websockets/package.json

```
[x] Bugfix
[ ] Feature
```
`@nestjs/platform-express` is hardcoded as the default platform, and is `require`d in various places in the code base. However, it is not an explicit dependency and thus package installers (yarn/npm/pnpm) need a hint on how to properly link them in order to be resolved.
See: https://github.com/nestjs/nest/blob/09fbc83108c8429a21c4d383b62f68037d6d2204/packages/core/nest-factory.ts#L211-L218
Without this change, Nest has problems running on stricter …

fix(core): add missing optional dependencies

---

packages/microservices/interfaces/microservice-configuration.interface.ts

```
[ ] Bugfix
[x] Feature
```
The options interface for providing a configuration for a microservices `CustomStrategy` currently indicates that the strategy *must* also implement a `Server`. While it may be desirable for a custom strategy to extend a server for leveraging common functionality it is not a requirement for all custom strategies.
A concrete example of such a strategy which allows for microservice implementations that manage their own independent registrations through Module lifecycle as …

fix(microservices): custom strategy typings

---

packages/common/interfaces/external/validation-error.interface.ts
packages/common/interfaces/external/validator-options.interface.ts

```
[ ] Bugfix
[ ] Feature
```
Issue Number: #6131
Related #6124 
bundled class-validator external interfaces are compatible with the interfaces from class-validator package.
```
[x] Yes
[ ] No
```
* `ValidatorOptions` interface is updated to match upstream interface.
* `ValidationError` interface is now a class in the upstream package and some properties of it are made optional.
Projects using `ValidationError` with `strictNullCheck` may need to add a type guard

fix(common): update class-validator interfaces

---

packages/testing/testing-module.builder.ts

Adds a method that enables to set a new custom logger (extended from the Logger class) for testing. If this method is not used (therefore the logger gets never set) it falls back to the already existing TestingLogger of the testing module.
(see https://github.com/nestjs/docs.nestjs.com/pull/1633)
```
[ ] Bugfix
[X] Feature
```
The current TestModuleBuilder uses a built-in `TestingLogger` that is applied when the TestModule gets compiled.
This `TestingLogger` is, intentionally, a minimal implementation …

feat(testing): adds builder method for optional custom logger

---

packages/common/interfaces/http/http-server.interface.ts
packages/core/adapters/http-adapter.ts
packages/core/helpers/router-method-factory.ts
packages/core/test/helpers/router-method-factory.spec.ts

```
[x] Bugfix
[ ] Feature
```
Issue Number: #1799
```
[x] Yes
[ ] No
```

fix(core): use "router.all" method when RequestMethod is set to ALL

---

packages/common/decorators/core/injectable.decorator.ts
packages/platform-express/multer/interceptors/any-files.interceptor.ts
packages/platform-express/multer/interceptors/file-fields.interceptor.ts
packages/platform-express/multer/interceptors/file.interceptor.ts
packages/platform-express/multer/interceptors/files.interceptor.ts

```
[x] Bugfix
[ ] Feature
```
`mixin` is hardcoded to `any` for its argument and its return.
`mixin` returns the proper type
```
[ ] Yes
[x] No
```
I couldn't get the project started correctly locally (this is my first contribution to nestjs _I think_):
But I believe [the second commit](https://github.com/nestjs/nest/pull/6216/commits/2f84e6e1b86bdc0a7ce06b38e81d27dca64444c4) is correct in the changes it makes.  I guess the CI will tell us.

fix(types) adds types for `mixin`

---

packages/websockets/interfaces/gateway-metadata.interface.ts

- [] Tests for the changes have been added (for bug fixes / features)
- [] Docs have been added / updated (for bug fixes / features)
```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe:
```
The websockets package proxifies types from [socket.io](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/socket.io/index.d.ts)'s, but they diverged in the `origins` metadata param. This PR just fixes it, without modifying current API, hence no docs or tests were added.
According to typings GatewayMetadata's `origins` does …

fix(websockets): fix typings for gatewaymetadata origins

---

integration/graphql-schema-first/src/cats/cats.service.ts
integration/graphql-schema-first/src/owners/owners.module.ts
integration/graphql-schema-first/src/owners/owners.service.ts
sample/12-graphql-schema-first/src/cats/cats.graphql
sample/12-graphql-schema-first/src/cats/cats.resolvers.ts
sample/12-graphql-schema-first/src/cats/cats.service.ts
sample/12-graphql-schema-first/src/graphql.schema.ts

There is no demo of `@ResolveField` in the `graphql-schema-first` sample
Adds a demo of `@ResolveField`
I love that you've added a GQL schema-first sample!  Huge help to understanding how we can jump right in to NestJS with a little structure.  One challenge my team has  been facing is figuring out the right way to translate information from the data-layer (TypeORM) to the transport-layer (the resolver).  
In the sample you've provided, it looks like the data-layer and the transport-layer are 1-to-1 (the GQL types perfectly match the data-set) so there's no need to solve this problem there.  I would love to see how you would implement an association.  The main …

sample(12): Example of how to use @ResolveField

---

integration/send-files/e2e/express.spec.ts
integration/send-files/e2e/fastify.spec.ts
integration/send-files/src/app.controller.ts
integration/send-files/src/app.module.ts
integration/send-files/src/app.service.ts
integration/send-files/src/non-file.ts
integration/send-files/tsconfig.json
packages/common/file-stream/index.ts
packages/common/file-stream/streamable-file.ts
packages/common/index.ts
packages/platform-express/adapters/express-adapter.ts
packages/platform-fastify/adapters/fastify-adapter.ts

Fastify has the built in capbility to send files without
any extra code. Express can send files via `stream.pipe(res)`
if the file is a stream, and as such, the
`Content-Type` header is set to `application/octet-stream`
in the ExpressAdapter if a stream or Buffer is detected.
fix #5263
```
[ ] Bugfix
[X] Feature
```
Files are not currently supported by Express and Fastify
Issue Number: #5263 
Fastify and Express Adapters now both support sending files via streams and Buffers.
```
[ ] Yes
[X] No
```

feat(core): add file send capability

---

packages/websockets/context/ws-context-creator.ts
packages/websockets/decorators/message-body.decorator.ts
packages/websockets/factories/ws-params-factory.ts
packages/websockets/test/factories/ws-params-factory.spec.ts
packages/websockets/utils/param.utils.ts

Add the ability to extract a paramater from the websocket's `MessageBody` decorator.
(My first time creating a PR here, might need some guidance on updating documentation.)
```
[ ] Bugfix
[x] Feature
```
The `MessageBody` websockets decorator cannot extract an object property from the body of the payload.
The `MessageBody` decorator can extract an object property like so:
```typescript
subMessage(@MessageBody('data') payload: { data: string }) {}
```
```
[ ] Yes
[x] No
```
Some …

feat(websockets): messagebody param extract

---

packages/websockets/package.json
packages/websockets/socket-module.ts

```
[x] Bugfix
[ ] Feature
```
The undeclared peer dependency `@nestjs/platform-socket.io` is required from `@nestjs/core` instead of `@nestjs/websockets`
The peer dependency is declared and required from `@nestjs/websockets`
```
[ ] Yes
[x] No
```
See https://yarnpkg.com/advanced/rulebook#packages-should-only-ever-require-what-they-formally-list-in-their-dependencies
Similar to https://github.com/nestjs/nest/pull/5477

fix(websockets): require @nestjs/platform-socket.io correctly

---

packages/common/pipes/index.ts
packages/common/pipes/parse-enum.pipe.ts
packages/common/pipes/parse-float.pipe.ts
packages/common/test/pipes/parse-enum.pipe.spec.ts
packages/common/test/pipes/parse-float.pipe.spec.ts

```
[ ] Bugfix
[x] Feature
```
Added two new pipe transformers for float and enum values
It is possible now to use new pipe transformer for float values and enum values
```
[ ] Yes
[x] No
```

feat(common): add parse float and enum pipes

---

integration/hello-world/e2e/fastify-adapter.spec.ts
integration/hello-world/e2e/hello-world.spec.ts
integration/hello-world/src/app.module.ts
integration/hello-world/src/host-array/dto/test.dto.ts
integration/hello-world/src/host-array/host-array.controller.ts
integration/hello-world/src/host-array/host-array.module.ts
integration/hello-world/src/host-array/host-array.service.ts
integration/hello-world/src/host-array/users/user-by-id.pipe.ts
integration/hello-world/src/host-array/users/users.service.ts
packages/common/decorators/core/controller.decorator.ts
packages/common/test/decorators/controller.decorator.spec.ts
packages/core/router/router-explorer.ts
packages/core/router/routes-resolver.ts

```
[ ] Bugfix
[x] Feature
```
Currently only one host pattern can be specified. Some complicated expressions can be written in [`path-to-regexp`](https://github.com/pillarjs/path-to-regexp) syntax to accept multiple hosts, but not all combinations are possible.
For example, there's currently no way (as far as I can tell) to accept hosts `foo.org` and `:param.bar.com` without also accepting `:param.foo.org` and `bar.com`: 
```ts
@Controller({ host: ':param?(foo.org|bar.com)' })
```
With this change, an …

feat(): accept array of host filters

---

integration/nest-application/global-prefix/e2e/global-prefix.spec.ts
integration/nest-application/global-prefix/src/app.controller.ts
integration/nest-application/global-prefix/src/app.module.ts
integration/nest-application/global-prefix/tsconfig.json
packages/common/interfaces/global-prefix-options.interface.ts
packages/common/interfaces/index.ts
packages/common/interfaces/nest-application.interface.ts
packages/core/application-config.ts
packages/core/nest-application.ts
packages/core/router/router-explorer.ts
packages/core/test/application-config.spec.ts
packages/core/test/router/router-explorer.spec.ts

New global prefix option to exclude some routes as a string or a RouteInfo
```
[ ] Bugfix
[x] Feature
```
You can specify a global route prefix but you can't exclude some routes
```ts
app.setGlobalPrefix('v1');
```
Issue Number: #963 
It add a new option object for the global prefix. You can exclude routes based on the path and the request method
```ts
app.setGlobalPrefix('v1', { exclude: [
{ path: '/health', method: RequestMethod.GET }
]});
```
You can also specify route as a string (it apply on every …

feat(core): exclude route from global prefix

---

packages/common/decorators/http/route-params.decorator.ts

https://github.com/nestjs/nest/issues/4752
There does not seem to be a test for these particular decorators. 
```
[ ] Bugfix
[X] Feature
```
The current file interceptor does not allow for pipes that will get executed upon the uploaded file. According to the issue this leaves user of Nest with having to run validation on the file inside their controller itself which is different from the approach Nest uses with the `@Param` decorator for instance. 
Issue Number: …

feat(common): Allowing pipes for UploadedFile / UploadedFiles

---

packages/common/interfaces/external/class-transform-options.interface.ts

```
[ ] Bugfix
[ ] Feature
```
Issue Number: #6443
Add property `exposeUnsetFields` to `ClassTransformOptions`.
When `exposeUnsetFields` set to true, fields with `undefined` as value will be included in class to plain transformation. Otherwise those fields will be omitted from the result,  the default `exposeUnsetFields` property is true.
```
[ ] Yes
[x] No
```
This PR, updated transform options interface
P.s. NestJS ♥️

chore(): updated transform options interface

---

packages/common/cache/interceptors/cache.interceptor.ts

When used, @CacheTTL(0) will set non expiring value on endpoint.
```
[x] Bugfix
[ ] Feature
```
The CacheTTL decorator use reflector to get cache ttl metadata.
When that data equals to 0, ttl value is settled to null. Because 0 is falsy value!
Same PR was created(#4506), but still different to expected behavior.
Issue Number: #4447
When set ttl value 0 to CacheTTL decorator, it's not expired.
```
[ ] Yes
[x] No
```

fix(common): change cache ttl decorator to apply non expiring ttl

---

packages/common/interfaces/external/cors-options.interface.ts

```
[x] Bugfix
[ ] Feature
```
The second argument of the origin callback is not a boolean, but the "non-function value of the origin option".
NB: Passing `false` doesn't reject the origin, it evaluates to nothing, and then the library interpreters that as `*`, which allows everything.
Since this is only a typescript type update there's not really much to test, but correct me if I'm wrong.
```
[ ] Yes
[x] No
```

fix: update CORS origin type

---

packages/core/middleware/utils.ts
packages/core/test/middleware/utils.spec.ts

throws following error when using class middleware with babel
```
TypeError: Cannot call a class as a function
```
Issue Number: #6586
detects middleware class after it has been transformed by babel
It checks for a conventional class by detecting if the function starts with a capitol letter.
https://github.com/nestjs/nest/pull/6587/files#diff-121f827f94f0efc4a83805b785189f67d64b8a4e06d814a38e8ca7e0b42aa2e9R70
This is how the `typechecker` library checks for conventional classes.
https://github.com/bevry/typechecker/blob/master/source/index.ts#L5
To prevent edge cases, I use duck typing to check if it's a middleware class with the `use` method. …

fix(core): detect conventional middleware class #6586

---

packages/core/router/router-explorer.ts
packages/core/test/router/router-explorer.spec.ts

```
[ ] Bugfix
[x] Feature
```
summary \:
Currently, even if the router implementation changed, the new impl is ignored. 
Due to the above reasons, the following e2e test fail \:
```ts
import { Controller, Get, INestApplication, Query } from "@nestjs/common";
import { Test, TestingModule } from "@nestjs/testing";
import supertest from "supertest";
@Controller("api")
class TestController {
@Get("hello")
getHello(@Query("userName") userName: string) {
return `Hello, ${userName}!`;
}
} …
```

feat(core): support route injection

---

packages/common/cache/interceptors/cache.interceptor.ts

With the `CacheIntercetpor` now using a `protected` array of allowed methods
it will be easier to allow for adding new methods to be cached without having to
rewrite the entire `trackBy` method. This will allow for users to add methods
like `HEAD` to be cached.
fix: #6427
```
[ ] Bugfix
[X] Feature
```
Adding a new method to trackBy for the `CacheInterceptor` due to needing to re-write the `trackBy` method.
Issue Number: #6427 
Now a simple array can be overwritten which is much easier.
```
[ ] Yes
[X] …
```

feat(cache): allow for cache interceptor to be more easily extended

---

sample/04-grpc/package-lock.json
sample/04-grpc/package.json

```
[ ] Bugfix
[ ] Feature
```
added dependecy `@nestjs/platform-express` in sample `04-grpc`
```
[ ] Yes
[x] No
```
This PR, added dependecy `@nestjs/platform-express` in sample `04-grpc`, since it was not possible to start and use the sample, due to the following error: (see screeshot)
to generate the error I did the following steps:
- ```npm i ```
- ```npm run start:dev```

fix(deps): added dependecy @nestjs/platform-express in sample 04-grpc

---

packages/core/router/router-execution-context.ts
packages/core/test/router/router-execution-context.spec.ts

The two decorators @UploadedFile and @UploadedFiles have been marked as pipeable,
however this had no affect as this method was preventing their execution.
```
[X] Bugfix
[ ] Feature
```
Currently, the interface for `@UploadedFile` and `@UploadedFiles` describes the possibility of adding pipes to somehow transform the file object. However, this does not work at the moment since the `isPipeable` method does not accept `FILE` and `FILES` as "pipeable". 
Issue Number: …

fix(core): marking files as pipeable

---

packages/platform-express/multer/interfaces/files-upload-module.interface.ts

```
[ ] Bugfix
[ ] Feature
[X] Refactoring (no functional changes, no api changes)
```
file `files-upload-module.interface.ts` is importing file `multer-options.interface.ts` from the same directory, referencing parent directory unnecessary (i.e. it goes ./FILE instead of ../CURRENT_DIR/FILE)
file `files-upload-module.interface.ts` is importing file `multer-options.interface.ts` from the same directory without referencing parent directory
```
[ ] Yes
[X] No
```

unnecessary referencing parent directory in import

---

packages/common/enums/http-status.enum.ts

`const enum`s are inlined at compile-time in TypeScript, while regular `enum`s use array and object lookups.  This should provide minor performance and size improvements
```
[ ] Bugfix
[ ] Feature
```
Not totally a refactor, because there are features with regular `enum`s you cannot do with `const enum`s
```
[x] barely
[ ] No
```
If any Nest.js users use reverse mappings, they will need to find another way to get that behavior.  I'd imagine for HTTP status codes, that would be a very …

perf(core): use const enum for `HttpStatus`

---

packages/tsconfig.base.json

```
[x] Bugfix
[ ] Feature
```
The `vinyl-fs` types are being referenced in a triple-slash directive in `core/router/sse-stream.d.ts` because `@types/vinyl-fs` includes a global change to the `NodeJS.WritableStream` interface. This can cause problems in packages using nest, as `@types/vinyl-fs` is not included as a dependency (nor should it be) so typescript may not be able to resolve the reference. I've seen this issue locally and in CI, but it may not always appear with `tsc`
Issue Number: #7247 
The …

fix(packaging): limit global types to "node"

---

packages/core/router/sse-stream.ts

As of RFC 7230, "identity" is no longer a valid transfer-encoding,
setting the header will cause errors.
Closes #6882
```
[x] Bugfix
[ ] Feature
```
SSE decorated responses fail behind certain reverse proxies
Issue Number: #6882
SSE response will work correctly
```
[ ] Yes
[x] No
```

fix(core): remove transfer-encoding header in sse response

---

packages/core/router/router-response-controller.ts
packages/core/router/sse-stream.ts
packages/core/test/router/router-response-controller.spec.ts

If we want to stop sending data (for example user logged out), the server-sent events endpoint should send a 204 telling the client not to reconnect. For now this will throw an `Headers already sent` error. This patch allows to do so. 
For example: 
```typescript
import { Controller, Get, MessageEvent, Res, Sse, Post } from '@nestjs/common';
import { Response } from 'express';
import { join } from 'path';
import { interval, Observable, timer, empty, fromEvent } from 'rxjs';
import { map, takeUntil, timeout } from 'rxjs/operators';
@Controller()
export class AppController {
private abortController: AbortController
@Post()
post(@Res() response: Response) {
this.abortController.abort()
response.sendStatus(202)
}
@Sse('sse') …
```

fix(core): sse end response when observable completes

---

packages/platform-fastify/interfaces/external/fastify-static-options.interface.ts
packages/platform-fastify/interfaces/external/point-of-view-options.interface.ts

Both the fastify-static and point-of-view packages interface.ts files are updated to match the
versions used in the package.json file. The point-of-view package added support for eta, liquid
and dot engine.
```
[x] Bugfix
[ ] Feature
```
My problem was that I couldn't use the Eta engine for Fastify, but the latest point-of-view package did support it. The changes I made are just copies of the latest linked files.
Issue Number: I did not open an issue, I just tried to help en fix it myself.
Eta engine …

fix(platform-fastify): update fastify-static and point-of-view interface.ts files

---

packages/microservices/client/client-kafka.ts
packages/microservices/test/client/client-kafka.spec.ts

```
[x] Bugfix
[ ] Feature
```
Issue Number: https://github.com/nestjs/nest/issues/6797
Users may not pass a `logCreator` option into their `KafkaClient` implementations.
```
[ ] Yes
[x] No
```
Users will not have been passing in `logCreator` functions to this method. If they were, they are likely already correctly typed.
There's a few different variations on this change, which I'm going to comment on inline!

fix: reorder kafka config assignment to pass down a custom log creator

---

packages/common/decorators/core/controller.decorator.ts
packages/core/router/router-explorer.ts

```
[ ] Bugfix
[ ] Feature
```
Non-functional update to type definition to match the definition in a dependency
Issue Number: https://github.com/nestjs/nest/issues/7120
The type definition for hosts now matches the one defined in [path-to-regexp](https://github.com/pillarjs/path-to-regexp/blob/master/src/index.ts#L601). Using `// @ts-ignore` is no longer required to pass regex in
```
[ ] Yes
[x] No
```
This does not provide a code path for providing keys to path-to-regexp. When using regex hosts, the …

fix(core): update hosts definition to match path-to-regexp

---

packages/microservices/helpers/kafka-parser.ts
packages/microservices/test/helpers/kafka-parser.spec.ts

When using the kafka schema registry values with a zero byte preamble indicate a schema message. The following four bytes contain the schema id, followed by a possibly binary message. The binary message must not be decoded to string, as this will possibly mutate the original bytes to comply with utf-8, thus breaking the message and making it unreadable.
```
[x] Bugfix
[ ] Feature
```
All values are converted to utf-8 strings, regardless of their binary or not nature.
value is checked …

fix(microservices): do not parse kafka schema messages

---

sample/28-sse/src/app.controller.ts

Fix: Type 'Observable<{ data: { hello: string; }; }>' is not assignable to type 'Observable<MessageEvent<any>>'.   Type '{ data: { hello: string; }; }' is missing the following properties from type 'MessageEvent<any>': lastEventId, origin, ports, source, and 22 more.

Observable is not assignable to type Observable

---

packages/microservices/client/client-nats.ts

When a message is published via NATS as the reply subject is the packet ID used
Now the method `createInbox` is used to create the response subject like in this [example](https://docs.nats.io/developing-with-nats/sending/replyto)
Now you can set the prefix of the reply subject using the `inboxPrefix` option. The prefix allows you a better control who is allowed to reply via the [configuration](https://docs.nats.io/nats-server/configuration/securing_nats/authorization#examples).

feat(microservices): use createInbox method

---

packages/common/services/console-logger.service.ts
packages/common/test/services/logger.service.spec.ts

For the default `ConsoleLogger`, the context can now be resetted to the value given in the constructor. This allows for temporarily changing the context and then returning back to the original context without calling `setContext()` and having to store the original value.

feat(common): add `resetContext()` to `ConsoleLogger`

---

packages/microservices/client/client-kafka.ts
packages/microservices/client/client-mqtt.ts
packages/microservices/client/client-nats.ts
packages/microservices/client/client-redis.ts
packages/microservices/client/client-rmq.ts
packages/microservices/client/client-tcp.ts
packages/microservices/interfaces/deserializer.interface.ts
packages/microservices/server/server-kafka.ts
packages/microservices/server/server-mqtt.ts
packages/microservices/server/server-nats.ts
packages/microservices/server/server-redis.ts
packages/microservices/server/server-rmq.ts
packages/microservices/server/server-tcp.ts
packages/microservices/test/client/client-redis.spec.ts
packages/microservices/test/client/client-rmq.spec.ts
packages/microservices/test/client/client-tcp.spec.ts
packages/microservices/test/server/server-kafka.spec.ts
packages/microservices/test/server/server-mqtt.spec.ts
packages/microservices/test/server/server-redis.spec.ts
packages/microservices/test/server/server-rmq.spec.ts
packages/microservices/test/server/server-tcp.spec.ts

Linked Issue #7657.
```
[ ] Bugfix
[X] Feature
```
kafka transport (and other transports) allow configuration of a deserializer via options.
The deserializer cannot be async.
deserializers may be async and the deserialization result is awaited
```
[ ] Yes
[X] No
```
I'm trying to integrate a deserializer that allows kafka messages with schema registry. This requires the deserializer to fetch the schema from the registry if it isn't cached yet. Currently the deserializer has to be …

feature(microservices): allow deserializers to be async and await result

---

integration/hello-world/e2e/exclude-middleware-fastify.spec.ts
integration/hello-world/e2e/middleware-class.spec.ts
integration/hello-world/e2e/middleware-fastify.spec.ts
packages/common/interfaces/http/http-server.interface.ts
packages/core/adapters/http-adapter.ts
packages/core/middleware/middleware-module.ts
packages/core/middleware/utils.ts
packages/core/test/middleware/utils.spec.ts
packages/core/test/utils/noop-adapter.spec.ts
packages/platform-express/adapters/express-adapter.ts
packages/platform-fastify/adapters/fastify-adapter.ts

Issue Number: #7511 #7564 
in order to the same wildcard(*) be used in express and fastify
http /test/a
FastifyAdapter Middleware forRoutes('*') 
before:
req.url === /test/a
after:
req.url === / (the same as express)

fix: FastifyAdapter Middleware no run, ExpressAdapter createMiddlewareFactory

---

packages/microservices/client/client-grpc.ts
packages/microservices/test/client/client-grpc.spec.ts

The current behavior does not cleanup the upstream subscription. With the new `@grpc/grpc-js` library, this means when providing a `Subject` as the upstream to a client-side streaming call. When the call errors, the upstream subject may still receive events that publish to its subscriber. Resulting in `call.write()` being called after the gRPC call has errored, yielding a runtime error of 
```
Error [ERR_STREAM_WRITE_AFTER_END] [ERR_STREAM_WRITE_AFTER_END]: write after end
at ClientHttp2Stream.Writable.write (_stream_writable.js:292:11)
at private/var/tmp/_bazel_ss/df20b1cf05bc3804fe8b0280e866dcbb/execroot/unity/node_modules/@grpc/grpc-js/src/call-stream.ts:765:26
at …
```

fix(microservices): cleanup subscription in client-side streaming gRPC calls

---

packages/microservices/server/server-kafka.ts
packages/microservices/test/server/server-kafka.spec.ts

KafkaServer don't respects `logCreator` options for `client` configuration
Logs example:
```
[14:03:33.066] INFO (NestFactory): Starting Nest application...
[14:03:33.074] INFO (InstanceLoader): AppModule dependencies initialized
[14:03:33.074] INFO (InstanceLoader): EnvironmentModule dependencies initialized
[14:03:33.074] INFO (InstanceLoader): EnvironmentModule dependencies initialized
[14:03:33.076] INFO (InstanceLoader): LoggerModule dependencies initialized
[14:03:33.076] INFO (InstanceLoader): ConsumerModule dependencies initialized
[14:03:33.091] INFO (InstanceLoader): PostgresModule dependencies initialized
[14:03:34.133] INFO (ServerKafka): INFO [Consumer] Starting …
```

fix(microservices): reorder kafka config assigment

---

packages/common/serializer/class-serializer.interceptor.ts

Issue Number: #7909
We can use `return new StreamableFile(readStream)` (in some controller) along with the built-in serializer `ClassSerializerInterceptor`
I didn't write any tests because this change is pretty straightforward. But let me know if I should do

fix(common): serializer must ignore `StreamableFile` responses

---

packages/common/pipes/parse-int.pipe.ts
packages/common/test/pipes/parse-int.pipe.spec.ts

ParseIntPipe allows numbers with encoding such as 0x, 0b and e.t.c.
ParseIntPipe will allow only integer numbers with 10 base

fix(common): catch number encoding in ParseIntPipe

---

packages/microservices/client/client-mqtt.ts
packages/microservices/client/client-nats.ts
packages/microservices/client/client-rmq.ts
packages/microservices/interfaces/microservice-configuration.interface.ts
packages/microservices/record-builders/rmq.record-builder.ts
packages/microservices/test/client/client-mqtt.spec.ts
packages/microservices/test/client/client-nats.spec.ts
packages/microservices/test/client/client-rmq.spec.ts

It's currently only possible to send request-specific headers for NATS, RabbitMQ and MQTT
This PR allows the developer to add static headers to a client for NATS, RabbitMQ and MQTT. Aside from adding fully static values, it also allows developers to do something like:
```ts
providers: [{
provide: 'CLIENT_NATS',
scope: Scope.REQUEST,
inject: REQUEST,
useFactory: (req) => new ClientNats({
headers: {
requestId: req.header('request-id'),
}
})
}]
```
I don't know what the public interface on ClientProxy will be for sending request-specific headers, but I tried to deduce it from the changes in `feat/msvc-message-builder` and based the tests on that.

feat(microservices): add static headers

---

integration/send-files/e2e/express.spec.ts
integration/send-files/src/app.controller.ts
integration/send-files/src/app.service.ts
packages/common/file-stream/streamable-file.ts
packages/common/file-stream/streamable-options.interface.ts
packages/platform-express/adapters/express-adapter.ts
packages/platform-fastify/adapters/fastify-adapter.ts

Right now, we can just return a file and have to inject `@Res({ passthrough: true })` to update the content-type and disposition
We can pass these options to the `StreamableFile` constructor and let Nest take care of the work for devs

feat(common): add the ability to set some extra metadata about returned files

---

packages/common/cache/cache.module.ts
packages/common/cache/interfaces/cache-module.interface.ts

Issue Number: #8579
Notice that those type args on `CacheModule#register` and `CacheModule#registerAsync` and so on are optional. The default is still `Record<string, any>`

feat(common): add an optional type arg to `register` and `registerAsync` of `CacheModule`

---

packages/microservices/client/client-grpc.ts
packages/microservices/server/server-grpc.ts

A well-performed nestjs standard project, which transport is `Transport.GRPC` and  protoLoader is `@grpc/proto-loader`, is not compatible with  npm package `@vercel/ncc`. The reason is - ncc compiling js file use static analysation. Therefore, `require(someVar)` is not supported by ncc, but `require("some-string")` works well.
- Step1: run `nest build` in a standard nestjs project that its transport is `Transport.GRPC` and its protoLoader is `@grpc/proto-loader`
- Step2: run `npm i -g @vercel/ncc && ncc build dist/main.js -m -o out`
- Step3: run `node out/index.js` to bootstrap, but fail
- Step1: run `nest build` in a standard nestjs project that its transport is `Transport.GRPC` and …

feat(microservices): support ncc when using grpc

---

packages/core/injector/injector.ts

Issue Number: #8560
`NEST_DEBUG=true` prints providers token properly when `Symbol` is used, as well when any other kind object is used if they implement `.toString()` method
Also, instead of using `instanceWrapper.name` (which is `any`), we use `instanceWrapper.name.name` and `instanceWrapper.name.toString()` as a fallback. Let me know if this is fine. [Here's the JS code with tests](https://www.typescriptlang.org/play?removeComments=true&pretty=true#code/JYOwLgpgTgZghgYwgAgGIHt3IN4ChkHIhwC2EAXMnCAJ4DcuAvrjAK4gJjDojIyYAKAB4B+ShnQBKSgGcwUUAHMc+QlAhhWUXsJEA6YmWQAyY8mEHSES0YA+t5EJvWw6AMryl+gZN-IRIsgA5OwA1iDoAO4gQUy4CDwy6AA21snoigKqBPzoPgA0yAD0RchhEdHZfILYxaVCQlWERFaUQQ2xzYyS+VW5ArUlLWRNhI …

fix(core): use `toString()` as a fallback for dependent's name

---

integration/auto-mock/src/bar.service.ts
integration/auto-mock/src/foo.service.ts
integration/auto-mock/test/bar.service.spec.ts
integration/auto-mock/tsconfig.json
packages/core/injector/injector.ts
packages/core/injector/instance-loader.ts
packages/testing/interfaces/index.ts
packages/testing/interfaces/mock-factory.ts
packages/testing/testing-injector.ts
packages/testing/testing-instance-loader.ts
packages/testing/testing-module.builder.ts

In the current `Test` module there isn't an easy way to say "If this
dependency doesn't exist use this mock function instead." With this new
`useMocker` fluent function it becomes possible to tell the `TestingInjector`
to replace the undefined dependency with the automocking function. In doing so
classes that have a large number of dependencies no longer must be mocked one-by-one
. This is especially great when it comes to packages like `@golevelup/ts-jest`
which can create mocked dependencies of interfaces and classes with a single function.
I'm sure I've probably missed an edge case in here, so please let me know if you have
any major concerns.
```
[ ] Bugfix
[X] Feature
[ ] Code …
```

feat(testing): add auto-mocking capabilities

---

packages/core/router/router-execution-context.ts
packages/core/router/router-response-controller.ts
packages/core/router/sse-stream.ts
packages/core/test/router/router-execution-context.spec.ts
packages/core/test/router/sse-stream.spec.ts

When sending an sse response with fastify no headers applied to the fastify reply would be applied to the headers of the sse response
Issue Number: #8717
Any headers from the express `response` or fastify `reply` will be read and then applied to the sse response.
This has been tested with `express` and `fastify` with `app.enableCors()`

fix(core): apply existing headers to sse responses

---

packages/core/errors/messages.ts

Taking the following set up
```ts
// a.module.ts
import { Module } from '@nestjs/common'
import { B } from './b.module'
@Module({ imports: [B] })
export class A {}
import { Module } from '@nestjs/common'
import { A } from './a.module'
// b.module.ts
@Module({ imports: [A] })
export class B {}
// app.module.ts
import { Module, DynamicModule, Injectable, Inject } from '@nestjs/common'
import { A } from './a.module'
const dynamicModule: DynamicModule = {
module: class Foo {},
imports: [A], // <--------
}
@Module({
imports: [dynamicModule],
})
export class AppModule {}
```
when Nest can't resolve the module imported from within a dynamic module, the error shown is the following:
the name …

fix(core): `getInstanceName` wrong return when passing a dynamic module

---

integration/microservices/e2e/orders-grpc.spec.ts
integration/microservices/e2e/sum-grpc.spec.ts
packages/common/pipes/parse-enum.pipe.ts
packages/microservices/server/server-mqtt.ts

refactor(): replace `indexOf` with `includes`

---

packages/common/file-stream/streamable-file.ts
packages/common/pipes/parse-array.pipe.ts
packages/common/pipes/validation.pipe.ts
packages/common/services/console-logger.service.ts
packages/common/utils/is-uuid.ts
packages/core/injector/module-token-factory.ts
packages/core/middleware/utils.ts
packages/core/nest-application.ts
packages/core/router/router-execution-context.ts
packages/core/router/sse-stream.ts
packages/core/router/utils/flatten-route-paths.util.ts
packages/microservices/client/client-nats.ts
packages/microservices/serializers/mqtt-record.serializer.ts
packages/microservices/serializers/rmq-record.serializer.ts
packages/microservices/server/server-grpc.ts
packages/microservices/server/server-nats.ts
packages/platform-fastify/adapters/fastify-adapter.ts

In several places, utilities functions declared at https://github.com/nestjs/nest/blob/939f2d56d1c9ec25108ada7053dfc51cbc6be7c2/packages/common/utils/shared.utils.ts are not used when they could be used
Every `typeof x === y` and `typeof x !== y` was replaced with some method from `@nestjs/common/utils/shared.utils.ts` file
The only line I didn't change was the following:
https://github.com/nestjs/nest/blob/259b6fb46c98c9ae72824af5472ab13852b35837/packages/core/router/router-module.ts#L45
for whatever reason, using `isFunction(routeOrType)` introduces a compile error:
```
packages/core/router/router-module.ts(49,23): error TS2339: Property 'children' does not exist on type 'Type<any> | …
```

refactor(common,core): use shared utils whenever possible

---

packages/common/interfaces/nest-application-context.interface.ts
packages/core/nest-application-context.ts
packages/core/nest-factory.ts

Issue Number: closes #8733
I tested it locally with the following usages -- assuming that there was a call to `app.useLogger`:
```js
NestFactory.createApplicationContext(AppModule)
```
flushes (even tho the aren't logs buffered).
```js
NestFactory.createApplicationContext(AppModule, { bufferLogs: true })
```
flushes.
```js
NestFactory.createApplicationContext(AppModule, { bufferLogs: true, autoFlushLogs: true })
```
flushes.
```js
NestFactory.createApplicationContext(AppModule, { bufferLogs: true, autoFlushLogs: false })
```
do not flushes.
When using `NestApplicationContext` app and `autoFlushLogs` is on, invoking `useLogger` method on it will flushes its logs.
A naive attempt to …

fix(common,core): auto flush logs after `useLogger` call

---

packages/common/decorators/core/controller.decorator.ts
packages/common/decorators/core/version.decorator.ts
packages/common/interfaces/version-options.interface.ts
packages/common/test/decorators/controller.decorator.spec.ts
packages/common/test/decorators/version.decorator.spec.ts
packages/core/application-config.ts
packages/core/helpers/messages.ts
packages/core/router/route-path-factory.ts
packages/core/test/application-config.spec.ts
packages/core/test/router/route-path-factory.spec.ts

When using the [versioning feature](https://docs.nestjs.com/techniques/versioning), wf we pass an array of versions that contains duplicated values 
---
Issue Number: closes #8734
Duplicated values are removed before defining the final version value
---
Users can pass an array containing the `VERSION_NEUTRAL`
I've chose to mutate the supplied object instead of creating a new one. Let me know if this isn't good.
my tests didn't cover the `VERSION_NEUTRAL` symbol because we cannot pass an array containing `VERSION_NEUTRAL`, but I did tested that `Array.from(new Set([Symbol()]))` locally.

feat(core,common): fix ignore duplicated versions and support an array containing VERSION_NEUTRAL 

---

packages/core/router/router-execution-context.ts
packages/core/router/router-response-controller.ts
packages/core/test/router/router-response-controller.spec.ts

Previously when an error was thrown in an observable as part of an SSE request the server would crash.
Issue Number: #8730
Now errors are properly handled within SSE request so that if an error occurs then an error message event is sent and the connection is closed.
- [] Yes
Breaking changes have been removed from scope

feat(core): handle errors in observable streams

---

integration/microservices/src/grpc-advanced/advanced.grpc.controller.ts
integration/microservices/src/grpc/grpc.controller.ts
packages/common/pipes/default-value.pipe.ts
packages/common/test/utils/shared.utils.spec.ts
packages/common/utils/shared.utils.ts
packages/core/helpers/external-context-creator.ts
packages/microservices/context/rpc-proxy.ts
packages/microservices/exceptions/base-rpc-exception-filter.ts
packages/microservices/serializers/nats-record.serializer.ts
packages/microservices/server/server-grpc.ts
packages/microservices/server/server-kafka.ts
packages/microservices/server/server-mqtt.ts
packages/microservices/server/server-nats.ts
packages/microservices/server/server-redis.ts
packages/microservices/server/server-rmq.ts
packages/microservices/server/server-tcp.ts
packages/microservices/server/server.ts
packages/microservices/test/client/client-grpc.spec.ts
packages/microservices/test/client/client-mqtt.spec.ts
packages/microservices/test/client/client-proxy.spec.ts
packages/microservices/test/client/client-rmq.spec.ts
packages/microservices/test/context/rpc-proxy.spec.ts
packages/microservices/test/exceptions/rpc-exceptions-handler.spec.ts
packages/microservices/test/server/server-mqtt.spec.ts
packages/microservices/test/server/server.spec.ts
packages/microservices/utils/transform-pattern.utils.ts
packages/platform-express/adapters/express-adapter.ts
packages/platform-ws/adapters/ws-adapter.ts
packages/websockets/context/ws-proxy.ts
packages/websockets/test/context/ws-proxy.spec.ts

Issue Number: closes #8595
As you can see here: https://cs.github.com/nestjs/nest?&q=isObservable there are few versions of `isObservable` on this codebase. Which are implemented as follow:
```ts
function isObservable(input): input is Observable<any> {
return input && isFunction(input.subscribe)
}
```
I'm under assumption that all of them are supposed to return true when the input is an `Observable` object created by `rxjs` lib.
Using `isObservable` type guard from `rxjs` instead (introduced in `rxjs@6`)
which is implemented as follows [here](
https://github.com/ReactiveX/rxjs/blob/e06a472979ed29e163ad095db0125b2d82bec2f0/src/internal/util/isObservable.ts#L12):
```ts
function …
```

Use `isObervable` from `rxjs` instead of our own implementation. Drop few deprecated APIs from 3rd-party libs. And other minor refactorings

---

packages/core/middleware/container.ts

refactor(): remove duplicate function `getClassScope`

---

packages/core/router/sse-stream.ts
packages/core/test/router/router-response-controller.spec.ts
packages/core/test/router/sse-stream.spec.ts

closes nestjs/nest#8877
- [N/A] Docs have been added / updated (for bug fixes / features)
When using SSE feature, the first message received by client contains only colons (":").
Issue Number: #8877
When using SSE feature, the first message received by client contains only newline character ("\n").
N/A
I chose to keep the newline character as suggested by @jpineaufr. I **think** it was added to pretty print the message. Also, we could improve tests readability with some utility functions to encapsulate parts of the code and make use of "give", "when" and "then", like so:
```typescript
const { sse, sink } = givenANewSseWithSink()
whenMessageIs({
type: 'tea-time',
id: 'the-id',
retry: …
```

fix(sse): stream sink content

---

integration/microservices/e2e/sum-grpc.spec.ts
integration/microservices/src/grpc/grpc.controller.ts
packages/microservices/client/client-grpc.ts

Issue Number: #9047 
`gRPCClientProxy.GetService` now generates service methods both in uppercase and lowercase instead of forcing it to lowercase.

fix(microservices): generate service method in lower and uppercase

---

packages/core/router/routes-resolver.ts
packages/core/test/router/routes-resolver.spec.ts

Issue Number: #8915
When given a path parameter with an invalid percent encoding, Express throws a `URIError` with the `statusCode` field set to `400` (bad request):  
https://github.com/expressjs/express/blob/4.17.1/lib/router/layer.js#L166
Convert this `URIError` to a `BadRequestException` before providing it to the exception filters. Therefore the exception filters will handle this error in the same way as other bad requests.
Note that this only applies to errors thrown directly from Express or Fastify. A `URIError` thrown from a NestJS construct such as a controller or validation pipe will continue to be provided to the exception filters as is.
Closes #8915

fix(core): convert URIError thrown by the HTTP platform to BadRequestException

---

packages/microservices/constants.ts
packages/microservices/decorators/event-pattern.decorator.ts
packages/microservices/decorators/message-pattern.decorator.ts
packages/microservices/interfaces/message-handler.interface.ts
packages/microservices/listener-metadata-explorer.ts
packages/microservices/listeners-controller.ts
packages/microservices/server/server.ts
packages/microservices/test/decorators/event-pattern.decorator.spec.ts
packages/microservices/test/decorators/message-pattern.decorator.spec.ts
packages/microservices/test/listeners-controller.spec.ts
packages/microservices/test/listeners-metadata-explorer.spec.ts

The current implementation allows passing only `pattern` and `transport` to the microservice transport. No way to attach any handler-specific rich types.
The new implementation adds optional "extras" parameter for `MessagePattern` and `EventPattern` decorators that allows embedding any extra params into each message handler method and improves the experience of creating custom microservice transports.

feat(microservices): add new `extras` param to `MessagePattern` and `EventPattern` decorators

---

sample/02-gateways/src/adapters/redis-io.adapter.ts
sample/02-gateways/src/main.ts

---
**Issue 1:** The Redis adapter is not used in the sample app
**Repro steps:**
- Run a redis server at `redis://localhost:6379`
- Change the redis URL in `RedisIoAdapter` to a non-existent redis URL (for example: `redis://localhost:6380`)
- Run `yarn start`
**Current behavior**: App runs normally because the `RedisIoAdapter` is not used anywhere in the app.
**Expected behavior**: App should crash with `ECONNREFUSED 127.0.0.1:6380`
---
**Issue 2:** The Redis adapter is not initialized correctly in the sample app
Following #9158, the `redis` and `@socket.io/redis-adapter` dependencies were updated, but the new changes do not reflect the new API.  See: …

sample(02-gateways): Fix Redis adapter

---

packages/websockets/interfaces/gateway-metadata.interface.ts

In the documentation for websockets, the default value for pingTimeout property of GatewayMetadata interface is set to 5000 ms.
After setting the DEBUG env variable (i.e. DEBUG=*), the default value for pingTimeout property is actually logged as 20000 ms (and not 5000 ms as mentioned in the docs).

docs(websockets): update GatewayMetadata pingTimeout default value to 20000 ms

---

packages/microservices/client/client-kafka.ts
packages/microservices/interfaces/serializer.interface.ts

Currently the Kafka Client/Server calls the serializer passing only the packet/message value as parameter.
From now the Kafka Client is calling the serializer passing the packet value and also an options object containing the pattern (topic name) as parameters. 
With the optional options parameter the Serializer interface is now matching the Deserializer interface. 
This change doesn't introduce a breaking change because the options parameter is optional.    
I'm deserializing/serializing messages using Avro Schemas with the Schema Registry, in order to do that the custom serializer needs to be aware of the topic/pattern name of each message.
Since this is an issue …

feat(microservices): Add options param to serializer

---

packages/common/decorators/core/catch.decorator.ts

This PR makes `@Catch` decorator to accept Abstract class with any class.
In my project, there are custom error classes implemented by inheriting one abstract class.
In order to handle these errors in the Exception Filter, I wanted to put an abstract class, the top class of custom errors, in `@Catch` decorator.
However, since `@Catch` decorator only allows `Type<any>` class, abstract class cannot be added.
The `@Catch` decorator is catching errors internally using the `instanceof` keyword.
Therefore, if nestjs allow the abstract class to be caught, it is natural for custom error classes that inherit the abstract class to be caught.
```ts
// custom errors
abstract …
```

feat(common): add abstract type to catch decorator

---

packages/microservices/client/client-kafka.ts

This commit closes issue #9258.
Issue Number: #9258
`ClientKafka` provides access to `commitOffsets` function from `kafkajs`.

feat(microservices): add commit-offsets function to clientkafka

---

integration/injector/e2e/injector.spec.ts
integration/injector/src/inject/inject-same-name.module.ts
integration/injector/src/self-injection/self-injection-provider.module.ts
packages/core/injector/injector.ts

Issue Number: closes #9245 _(bugfix)_
This also closes #8894 _(feature)_ in some sort as of now self-injections will raise the `UnknownDependenciesException` error. This might not be the right error but at least now nestjs won't get stuck nor crashes silently. We could improve that later if needed.
Now this pattern is allowed:
```ts
class Foo {
constructor(@Inject('Foo') private foo: string) {}
}
@Module({
providers: [
{
provide: Foo, // This token isn't the same as the one in the provider below
useClasss: Foo,
},
{
provide: 'Foo',
useValue: 'bar',
},
],
})
class AppModule {}
```
and it wasn't prior to v8.
To see it in action, play with this repo: …

fix(core): use class refs as keys (container)

---

integration/versioning/e2e/custom-versioning-fastify.spec.ts
integration/versioning/e2e/custom-versioning.spec.ts
packages/common/enums/version-type.enum.ts
packages/common/interfaces/version-options.interface.ts
packages/core/router/router-explorer.ts
packages/core/test/router/router-explorer.spec.ts
packages/platform-express/adapters/express-adapter.ts
packages/platform-fastify/adapters/fastify-adapter.ts

Specifically, addes a 'Custom' VersioningType that allows for an
extractor function to be provided that receives the Request object
(either Express or Fastify) and returns a string or array of strings
pulled from said request. Examples include extracting custom header
values, URL params, POST request bodies, and more.
Fixes #8441
Issue Number: #8441 
As the commit message says, this allows users to provide a custom 'extractor' function, from which they can pull out any information and provide it to the Express/Fastify adapters for further routing.

feat(common): Add custom versioning support.

---

packages/microservices/client/client-tcp.ts
packages/microservices/ctx-host/tcp.context.ts
packages/microservices/helpers/index.ts
packages/microservices/helpers/json-socket.ts
packages/microservices/helpers/tcp-socket.ts
packages/microservices/interfaces/client-metadata.interface.ts
packages/microservices/interfaces/microservice-configuration.interface.ts
packages/microservices/server/server-tcp.ts

Issue Number: https://github.com/nestjs/nest/issues/7288
Current Microservices implementation of TCP server and client does not allow to process raw TCP packets.
Incoming data are processed by the `JsonSocket` helper which requires a specific format for incoming data in order to emit messages.
The new behavior moves the core TCP logic from `JsonSocket` into the abstract `TcpSocket`.
`TcpSocket` is extensible and allows NestJS users to define their own socket class in order to parse and send data using a custom format.
In order to implement their custom socket class, NestJS users have to:
- implement the abstract `TcpSocket.prototype.handleSend` method to write data to the underlying …

feat(microservices): add tcp raw data processing capabilities

---

packages/common/services/console-logger.service.ts
packages/common/test/services/logger.service.spec.ts

Implements option to have custom log formatters as discussed here:
https://github.com/nestjs/nest/issues/9281
Custom log message formaters aren't supported.
Issue Number: https://github.com/nestjs/nest/issues/9281
Custom log message formaters are supported

feat: allow custom log msg formatters

---

packages/microservices/server/server-kafka.ts
packages/microservices/test/server/server-kafka.spec.ts

When listening to messages from Kafka using EventPattern the message should not be replied to even if it contains correlation id and reply topic.
BREAKING CHANGE: existing methods where EventPattern is used instead of MessagePattern do not send message to a reply topic anymore which might cause bugs.
```ts
@EventPattern('event.pattern.test')
async eventPattern(
@Payload() message: any,
): Promise<any> {
return
}
```
This method sends a message to the reply topic with empty key and content. 
```ts
@EventPattern('event.pattern.test')
async eventPattern(
@Payload() message: any,
): Promise<any> {
return
}
```
This method no longer sends a message to the reply topic.

fix(microservices): fix event pattern behavior

---

packages/common/utils/cli-colors.util.ts

`isColorAllowed()` will return `true` even when the terminal can't support colors.
Colors will be enabled if the `NO_COLOR` environment variable is not an empty string and `tty.WriteStream.prototype.hasColors()` returns `true`.
Requires Node.js v10.16.0 or newer.
This means that users of the default NestJS logger can avoid having broken ANSI escape codes in their logs without any extra configuration.
On the off chance someone is logging to a TTY that supports color, but `tty.WriteStream.prototype.hasColors()` says it doesn't, users can use [the built-in `FORCE_COLOR` environment variable](https://nodejs.org/dist/latest-v16.x/docs/api/tty.html#writestreamgetcolordepthen …

feat(common): do not use colors in CLI if not supported

---

integration/nest-application/global-prefix/e2e/global-prefix.spec.ts
integration/nest-application/global-prefix/src/app.controller.ts
integration/nest-application/global-prefix/src/app.module.ts
packages/core/middleware/middleware-module.ts

Issue Number: https://github.com/nestjs/nest/issues/9124

fix(core): apply global middleware to routes excluded from prefix

---

packages/microservices/decorators/event-pattern.decorator.ts
packages/microservices/decorators/message-pattern.decorator.ts
packages/microservices/interfaces/custom-transport-strategy.interface.ts
packages/microservices/test/listeners-controller.spec.ts

Issue Number:https://github.com/nestjs/nest/issues/9341
A self-defined Symbol from a custom transpoter can be set for EventPattern & MessagePattern decorator to avoid binding patterns to wrong microservices in multiple microservices circumstances.

feat(microservices): allow to set custom transport to decorators

---

.github/dependabot.yml

At the moment there isn't a dependabot config for githubactions. With
this it includes for GitHub actions.
The GitHub actions aren't getting updates. The codeql github action has release of
2.8.3 and the one that is running right now is at 1.x.x. The codeql
plays a critical role in identifying vulnerabilities.

Included dependabot for GitHub actions

---

integration/microservices/e2e/sum-rmq.spec.ts
integration/microservices/src/rmq/rmq.controller.ts
packages/microservices/client/client-rmq.ts

Issue Number: https://github.com/nestjs/nest/issues/9364

fix(microservices): multiple rmq client urls issue #9364

---

packages/common/file-stream/streamable-file.ts

Users must always explicitly provide `options.length` when constructing a `StreamableFile`.
When a `Uint8Array` is provided to the constructor of `StreamableFile`, `options.length` will be `??=` to the `Uint8Array`'s length.

feat(common): set default StreamableFile length automatically when possible

---

packages/common/pipes/default-value.pipe.ts
packages/common/pipes/parse-array.pipe.ts

Due to TSC error, we cannot extend the built-in pipe `ParseArrayPipe` nor the `DefaultValuePipe` one if we want to add more options to them because their `constructor` has a `private` member
I don't know if the usage of `private` was intentional tho.
Now we can write a custom pipe that inherit from `ParseArrayPipe` like so:
```ts
interface MyParseArrayOptions extends ParseArrayOptions {
minItems?: number;
}
@Injectable()
class MyParseArrayPipe extends ParseArrayPipe {
constructor(@Optional() protected readonly options: MyParseArrayOptions = {}) {
super(options)
}
}
```

feat(common): change `private` modifer on built-in pipes to `protected`

---

sample/30-event-emitter/test/app.e2e-spec.ts

After the test is run, jest will hang telling
```
Jest did not exit one second after the test run has completed.
This usually means that there are asynchronous operations that weren't stopped in your tests. Consider running Jest with `--detectOpenHandles` to troubleshoot this issue.
```
It closes the app so the Jest can exit.

fix: prevent handle leak in default e2e test

---

packages/core/injector/container.ts

when trying to insert an undefined provider (due to a circular dependency), you get this message
`A circular dependency has been detected. Please, make sure that each side of a bidirectional relationships are decorated with "forwardRef()".`,
if the module you are inserting the provider into is defined, you get the module name in the error (hinting where to look for to find the circular dependency)
`A circular dependency has been detected in TheModule. Please, make sure that each side of a bidirectional relationships are decorated with "forwardRef()".`,

feat(core): enhance circular dependency error message

---

packages/common/pipes/parse-bool.pipe.ts
packages/common/pipes/parse-float.pipe.ts
packages/common/pipes/parse-int.pipe.ts

The built-in `ParseEnumPipe` has a protected method (`isEnum`) that would help devs on considering if a value is a valid enum, see:
https://github.com/nestjs/nest/blob/85bda838f7da649877c6973d34ed672ca286dba4/packages/common/pipes/parse-enum.pipe.ts#L51-L63
but `ParseBoolPipe`, `ParseFloatPipe` and `ParseIntPipe` doesn't has such capability
By implemeting the [Template Method](https://refactoring.guru/design-patterns/template-method) pattern, when extending some of those pipes listed above, one could define how they want to evaluate some value as a valid value to proceed the transformation.
For instance, currently, `ParseBoolPipe` will transform `"true"` to `true`, but what if we want …

feat(common): improve extensibility on few built-in pipes

---

.mocharc.js
package.json
rootHook.ts

Before this diff, running the test `./node_modules/.bin/mocha packages/common/test/decorators/set-metadata.decorator.spec.ts --reporter spec --require 'node_modules/reflect-metadata/Reflect.js' --exit`, produced error
```
TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for /Users/saurabh/Desktop/Project-Repos/nest/packages/common/test/decorators/set-metadata.decorator.spec.ts
at Loader.defaultGetFormat [as _getFormat] (internal/modules/esm/get_format.js:71:15)
at Loader.getFormat (internal/modules/esm/loader.js:104:42)
at Loader.getModuleJob (internal/modules/esm/loader.js:242:31)
at async Loader.import (internal/modules/esm/loader.js:176:17)
at async …
```

fix(): individual test run

---

packages/core/router/router-explorer.ts
packages/core/test/router/router-explorer.spec.ts
packages/platform-express/adapters/express-adapter.ts
packages/platform-fastify/adapters/fastify-adapter.ts

Issue Number: closes #9581
now having `version: [VERSION_NEUTRAL]` will behave the same as `version: VERSION_NEUTRAL`
I've tested those changes with both adapters in a local project of mine

fix: when version is an array with neutral version

---

packages/common/pipes/parse-uuid.pipe.ts

Validation error message has an unnecessary double space when no version is provided:
`Validation failed (uuid  is expected)`
Double space removed when no version is provided:
`Validation failed (uuid is expected)`

Improve ParseUUIDPipe error message

---

packages/common/interfaces/modules/provider.interface.ts

According to this [document](https://docs.nestjs.com/fundamentals/async-providers), if factory provider's `useFactory` function is async, `useFactory` function should return `Promise<T>`.

fix: fix factory provider definition

---

packages/common/interfaces/modules/provider.interface.ts

Issue Number: closes #9357
At build time, we can no longer have the option `inject` when writing a class or value providers
The TS error would be like this:
```
Type '{ provide: string; useValue: number; inject: never[]; }' is not assignable to type 'Provider<any>'.
Object literal may only specify known properties, and 'useValue' does not exist in type 'FactoryProvider<any>'.
```
This will break the build step of projects that are using the `inject` value when defining a class or a value provider even tho this option does nothing on these providers.

feat(common)!: disallow usage of `inject` on class and value providers at type level

---

packages/core/router/router-response-controller.ts
packages/core/test/router/router-response-controller.spec.ts
packages/websockets/test/web-sockets-controller.spec.ts
packages/websockets/web-sockets-controller.ts

Here's the full code: https://gitlab.com/micalevisk/nestjs-observable-issue
If we return a literal object that has the `subscribe` method on it, the application gets stuck
```ts
import { Controller, Get, Req } from '@nestjs/common'
import { of, Observable } from 'rxjs'
@Controller()
export class AppController {
@Get()
getHello(): any {
return { subscribe(){} }
}
}
```
If we return `req.route` (from Express), we got the following error (and `500` as a response)
```
Error: Route.subscribe() requires a callback function but got a [object Object]
at Route.<computed> [as subscribe] (/x/node_modules/express/lib/router/route.js:202:15)
at …
```

Use rxjs when checking if the value is an observable

---

packages/microservices/client/client-kafka.ts
packages/microservices/interfaces/microservice-configuration.interface.ts
packages/microservices/test/client/client-kafka.spec.ts

This feature flag enables users to skip the consumer group creation and
rebalancing and allows to only act as a producer on Kafka.
Resolves: #7259
PR for nestjs-docs: https://github.com/nestjs/docs.nestjs.com/pull/2280
A client will always create a consumer with a default group id on kafka, which leads to rebalancing the consumer group and delaying the application. Even if we don't really want to consume any messages, this requires us to create a new consumer group on Kafka.
Issue Number: #7259
This change introduces a feature flag to ClientKafka for only using a producer and skipping the consumer group registration
kafkajs-docs: https://kafka.js.org/docs/consuming
confluent-docs: …

feat(microservices): Introduce producerOnlyMode to ClientKafka

---

integration/nest-application/raw-body/e2e/express.spec.ts
integration/nest-application/raw-body/e2e/fastify.spec.ts
integration/nest-application/raw-body/src/express.controller.ts
integration/nest-application/raw-body/src/express.module.ts
integration/nest-application/raw-body/src/fastify.controller.ts
integration/nest-application/raw-body/src/fastify.module.ts
integration/nest-application/raw-body/tsconfig.json
packages/common/http/interfaces/index.ts
packages/common/http/interfaces/raw-body-request.interface.ts
packages/common/interfaces/http/http-server.interface.ts
packages/common/interfaces/nest-application-options.interface.ts
packages/core/adapters/http-adapter.ts
packages/core/nest-application.ts
packages/platform-express/adapters/express-adapter.ts
packages/platform-fastify/adapters/fastify-adapter.ts

Optionally provide the raw request body in the `Request` object of `express`. Relevant usecase: webhooks.
Many webhook solutions use HMAC signing of the `POST` body. But having the `bodyParser` enabled for NestJS makes this a no-go. The current workaround: disable `bodyParser` in its entirety, and add a middleware to your application that turns it back on, except for the route(s) you want it disabled for.
I think this is a non-NestJS way of doing it. Hence this PR.
This PR introduces a `rawBody` option when creating your NestJS application. When enabled, it adds the raw body to `req.rawBody`.
Relevant messaging with @jmcdo29 in Discord: …

feat(platform): add option to register raw body to request

---

packages/core/scanner.ts

i saw reflectMetadata public method in scanner.ts use params backwards
same level methods in scanner.ts like insertInjectable,
insertExportedProvider, insertController use pararms forward
i think this params order should be fixed
and only params reversed order in reflectMetadata can get hard to read
- [v] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [v] Tests for the changes have been added (for bug fixes / features)
- [] Docs have been added / updated (for bug fixes / features)
- [v] Code style update (formatting, local variables)
- [v] No

Refactoring(core): Change ReflectMetadata Params Order

---

packages/core/errors/messages.ts
packages/core/scanner.ts
packages/core/test/scanner.spec.ts

if the `imports` prop of `@Module()` has any class annotated with `@Controller()`, `@Catch()` or `@Injectable()`, we'll get an warning message like the following:
```
[DependenciesScanner] In the next major version, Nest will not allow classes annotated with @Injectable(), @Catch(), and @Controller() decorators to appear in the "imports" array of a module.
Please remove "AppController" (including forwarded occurrences, if any) from all of the "imports" arrays.
Scope [AppModule]
```
as this is not allowed in v9, the app now exits with an error:

feat(core)!: throw an exception instead of logging due to module import misusage

---

packages/microservices/package-lock.json
packages/microservices/package.json
packages/testing/package-lock.json
packages/testing/package.json

I didn't find any ocurrences of `import ... from 'json-socket'` on this codebase. See: https://cs.github.com/nestjs/nest?q=json-socket
The commit 9c3e15a added our own version of that package (which looks abandoned), so I believe there's no reason to keep this dependency under `@nestjs/microservices`
Same for the package [`optional`](https://www.npmjs.com/package/optional) under `@nestjs/testing`. See: https://cs.github.com/nestjs/nest?q=%22%27optional%27%22
now `@nestjs/microservices` has only 2 hard dependency: `iterare` and `tslib`
now `@nestjs/testing` has only 1 hard dep: `tslib`
```
$ npm ls json-socket
@nestjs/microservices@8.4.5 /x/packages/microservices
└── (empty)
$  npm ls …
```

chore(microservices,testing): drop `json-socket` and `optional` hard dependencies

---

.commitlintrc.json
CONTRIBUTING.md

Just a suggestion to improve the contribution workflow somehow :smile_cat: 
4 new scopes to use on commit messages to cover changes made on `@nestjs/platform-express`, `@nestjs/platform-fastify`, `@nestjs/platform-socket.io` and `@nestjs/platform-ws`. I ommited the prefix `platform-` because I want to have more space to write commit's subject
Now we'll get the following warnning line after `git commit` if the commit message has an scope other than those listed in the contribuiting guide:
```
⚠   scope must be one of [common, core, sample, microservices, express, fastify, socket.io, ws, testing, websockets] [scope-enum]
```

docs: add more commit scopes on contributing guide

---

packages/testing/testing-module.ts

when creating a testing app with `Test.createTestingModule` and `createNestApplication()`, if we pass `false` to `logger` option, the logs aren't disable as stated in the `NestApplicationContextOptions` docs:
https://github.com/nestjs/nest/blob/df2dab4fccc5e9a32e2305929e09c7392b3daf78/packages/common/interfaces/nest-application-context-options.interface.ts#L6-L10
and is pretty easy to understand why:
https://github.com/nestjs/nest/blob/6aeb3258ac55f442913cf447d7e64ef83eb5496f/packages/testing/testing-module.ts#L74-L78
as L78 above is never called, there's no way to disable logs easily. Which isn't the same as the `NestFactory` version one: …

fix(testing): disable logs when `logger` is `false` on `TestingModule`

---

packages/platform-express/adapters/express-adapter.ts

The current version of `ExpressAdapter#applyVersionFilter` return a route handler that does too much even tho the versioning type isn't dynamic per handler
Now `ExpressAdapter#applyVersionFilter` will evaluate and return a request handler that just deals with one configured versioning type.
Also, the type defs are improved (a bit), to make that method more type-safe.

refactor(express): improve `applyVersioning` handler selector code

---

.prettierignore
package.json

there's a mismatch between the `format` npm-script and the files that lint-staged will watch against
https://github.com/nestjs/nest/blob/f765e2c8c9e3f0d1d1426e962dcab380bb960d85/package.json#L26
https://github.com/nestjs/nest/blob/f765e2c8c9e3f0d1d1426e962dcab380bb960d85/package.json#L47
now both are following the same patterns

chore: cover `integration` dir on lint-staged config

---

sample/31-graphql-federation-code-first/posts-application/src/posts/posts.resolver.ts

graphql federation sample does not work when query
```
{
post(id: 1) {
id
user {
name
}
}
}
```
graphql federation works

fix(sample): id param is string type

---

integration/scopes/e2e/durable-providers.spec.ts
integration/scopes/src/durable/durable-context-id.strategy.ts
integration/scopes/src/durable/durable.controller.ts
integration/scopes/src/durable/durable.module.ts
integration/scopes/src/durable/durable.service.ts
packages/common/decorators/core/controller.decorator.ts
packages/common/interfaces/modules/provider.interface.ts
packages/common/interfaces/scope-options.interface.ts
packages/core/helpers/context-id-factory.ts
packages/core/helpers/is-durable.ts
packages/core/injector/index.ts
packages/core/injector/injector.ts
packages/core/injector/instance-wrapper.ts
packages/core/injector/module-ref.ts
packages/core/injector/module.ts
packages/core/middleware/container.ts
packages/core/test/injector/instance-wrapper.spec.ts
packages/core/test/injector/module.spec.ts

feat(core): add durable providers feature

---

sample/05-sql-typeorm/package-lock.json
sample/05-sql-typeorm/package.json
sample/05-sql-typeorm/src/users/users.controller.ts
sample/05-sql-typeorm/src/users/users.service.spec.ts
sample/05-sql-typeorm/src/users/users.service.ts

Updated the `05-sql-typeorm` example, following the new version of `@nestjs/typeorm` v8.1.0 which supports `typeorm v0.3.x`

sample(05-sql-typeorm): update version typeorm

---

integration/repl/e2e/repl.spec.ts
packages/core/repl/repl.ts

when `NO_COLOR` env. var. is defined, the prompt indicator remains colored

fix(core): prompt respects `NO_COLOR` config

---

sample/05-sql-typeorm/src/users/users.controller.spec.ts
sample/05-sql-typeorm/src/users/users.controller.ts
sample/05-sql-typeorm/src/users/users.service.spec.ts
sample/05-sql-typeorm/src/users/users.service.ts

Updated the 05-sql-typeorm example. Fixed types for findOne and id param is number now

sample(sample/5): sample(sample/5): change types for id param in findone

---

packages/microservices/constants.ts
packages/microservices/server/server-rmq.ts
packages/microservices/test/server/server-rmq.spec.ts

Issue Number: #9749
If a RabbitMQ connection fails, NestJS keeps trying to reconnect but no log message is dispatched. So, the user thinks the server frozen and it is not doing anything else.
Upon a failed connection on the RabbitMQ server, I've added an error log to show what happened to the user.
At first we were considering that #9726 was also impacted by this issue, but it isn't, since this is specific to how RabbitMQ handles failed connection attempts.

fix(microservices): adds feedback message when RabbitMQ server connection hangs

---

packages/platform-express/package.json

Signed-off-by: Sushant Zope <sushantzope9096@gmail.com>

chore(express): bump multer 1.4.4 to 1.4.4-lts.1 to fix "CVE-2022-24434"

---

packages/microservices/ctx-host/index.ts

The `BaseRpcContext` class was not being exposed in the main package
Now, the class is being exposed.

feat(microservices): exposes base context on the main package

---

packages/microservices/client/client-kafka.ts
packages/microservices/interfaces/microservice-configuration.interface.ts
packages/microservices/server/server-kafka.ts

Issue Number: closes #9677 
empty strings on `postfixId` option on `KafkaServer` and `KafkaClient`'s `constructor` are allowed now
as we're changing the behavior of a public API (`ClientsModule.register`)

fix(microservices): allow `postfixId` on `KafkaOptions` to be an empty string

---

packages/common/exceptions/http.exception.ts
packages/common/test/exceptions/http.exception.spec.ts

Adds the ability to configure the cause of an error when passing an error object to http exception.
I would love to see HTTP Exception change over time to be more flexible, such as having both a custom message and a cause, but for now this fits my needs.
- Don't think this needs docs, since this is a side effect of passing an error, and not really a decision the user needs to make.
You can't set the `cause` of an error object.
It is now possible to set the cause of an HTTP Exception based error.
Documentation
- https://nodejs.org/en/blog/release/v16.9.0/#error-cause
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/Error#rethrowin …

feat(common): Add error chaining support to http exception

---

packages/common/interfaces/http/http-server.interface.ts
packages/core/adapters/http-adapter.ts
packages/core/exceptions/base-exception-filter.ts
packages/core/test/utils/noop-adapter.spec.ts
packages/platform-express/adapters/express-adapter.ts
packages/platform-fastify/adapters/fastify-adapter.ts

When an exception is thrown it will trigger the exception filter to try to send a reply.
If a header was already sent then the exception filter will fail to send this reply.
This change requires adapters to provide two new methods, `isHeaderSent()` and `end()`

fix: only send exception responses if header is not already sent

---

packages/common/pipes/file/file-type.validator.ts
packages/common/test/pipes/file/file-type.validator.spec.ts

add regex support when checking a file mime-type as requested [here](https://github.com/nestjs/nest/pull/9718#issuecomment-1164127445).
FileTypePipe only checks against common strings.
FileTypePipe now can check against regular expressions.

feat(common): file type validator

---

packages/microservices/external/kafka.interface.ts

Current interface is from version 1.15.0 of kafkajs or earlier, which resulted in a typescript error in my project
Starting version 1.16.0 of kafkajs this field is changed from type Date to string
```
Type 'import("<path>/node_modules/@nestjs/microservices/external/kafka.interface").LogEntry' is not assignable to type 'import("<path>/node_modules/kafkajs/types/index").LogEntry'.
The types of 'log.timestamp' are incompatible between these types.
Type 'Date' is not assignable to type 'string'.
```
Interface has been updated and the problem doesn't occur anymore
[Link to new interface in kafka](https://github.com/tulios/kafkajs/blob/v1.16.0/types/index.d.ts#L534)
Tested …

fix(microservices): Update LogEntry in external kafka interface

---

packages/websockets/interfaces/gateway-metadata.interface.ts

The default value for maxHttpBufferSize property of GatewayMetadata interface is set to 1e5 (100 KB).
The actual default value for maxHttpBufferSize property is 1e6 (1 MB). <a href="https://github.com/socketio/engine.io#methods-1">SocketIO docs</a>

docs(websockets): update GatewayMetadata maxHttpBufferSize default value to 1 MB

---

packages/core/scanner.ts

node12 has `Array.prototype.flat` method. See https://node.green/#ES2019-features-Array-prototype--flat--flatMap--Array-prototype-flat
thus we don't need to write this logic anymore.
I didn't changed the `flatten` on `@nestjs/common` because it is being used by other nestjs packages that didn't bumped their major version (ie., they still supports node10, I guess)
<details>
</details>
https://github.com/nestjs/nest/blob/34cb6001c30b3e2d2a9570bc87c6bd78a8c49524/packages/common/decorators/core/dependencies.decorator.ts#L3-L8
the above could be written like this: `arr.flat(Infinity)`
---
Also, I've looked at every JS feature that was added in node12 (taking this table https://node.green) …

refactor(core): replace our own 1-level flatten by the native one

---

integration/injector/e2e/optional-factory-provider-dep.spec.ts
packages/core/injector/injector.ts

fix(core): scoped factories should not fail with optional deps

---

packages/core/injector/helpers/provider-classifier.ts
packages/core/injector/instance-wrapper.ts
packages/core/test/injector/helpers/provider-classifier.spec.ts
packages/core/test/injector/instance-wrapper.spec.ts

The `InstanceWrapper#mergeWith` method was using some verifications to determine how it would merge with a given provider. I extracted this logic to another file to improve its readability and also because it could be potentially used by other classes.
Moreover, I added some missing test cases for it.
No new behavior, only refactor of existing one.

refactor(core): extract instance wrapper merge logic

---

packages/microservices/ctx-host/kafka.context.ts
packages/microservices/external/kafka.interface.ts
packages/microservices/server/server-kafka.ts
packages/microservices/test/client/client-kafka.spec.ts
packages/microservices/test/ctx-host/kafka.context.spec.ts
packages/microservices/test/server/server-kafka.spec.ts

Implements https://github.com/nestjs/nest/issues/9949
https://github.com/nestjs/nest/issues/9949
Issue Number: 9949
Adds heartbeat callback to KafkaContext (so it will be passed to the endpoint)

feat(microservices): add Kafka heartbeat callback to KafkaContext

---

integration/nest-application/raw-body/e2e/express.spec.ts
integration/nest-application/raw-body/e2e/fastify.spec.ts
packages/platform-express/adapters/express-adapter.ts
packages/platform-express/adapters/utils/get-body-parser-options.util.ts
packages/platform-fastify/adapters/fastify-adapter.ts

Issue Number: #9901 
Registers raw body for `application/x-www-form-urlencoded` requests.
`@fastify/formbody` did not allow any customization in the parsing process. Looking at the source code of that package, shows that it is incredibly small. In order to add `req.rawBody`, most of the code had to be duplicated. So I made the choice to remove registration `fastify/formbody`, and handle the content type ourselves in the exact same way. Only difference: the `req.rawBody` also gets assigned if the option was set.
Keen eyes will also notice that I've added support for `bodyLimit` when registering these content parsers. The previous code (of mine) was missing this.
**Question**:
We do not …

fix(express,fastify): raw body for urlencoded requests

---

integration/send-files/e2e/express.spec.ts
integration/send-files/src/app.controller.ts
integration/send-files/src/app.service.ts
packages/common/file-stream/streamable-file.ts
packages/platform-express/adapters/express-adapter.ts

If a request is cancelled during a `StreamableFile` response, then the stream is not properly closed which can lead to memory leaks and possible server failures if enough of them occur
Issue Number: #9759
`pipeline` ends up destroying streams used if there is an error in one of
the streams. Due to this, there's no chance of a memory leak from errored out
streams. There's also now an addition of adding an error handler to the
`StreamableFile` so that stream errors by default return a 400 and can be
customized to return an error message however a developer would like. These
only effect the express adapter because of how Fastify already internally
handles streams.
fix: #9759

fix: use pipeline over stream.pipe

---

packages/microservices/client/client-rmq.ts
packages/microservices/constants.ts
packages/microservices/interfaces/microservice-configuration.interface.ts
packages/microservices/server/server-rmq.ts

Rabbit MQ brokers may not allow for queue declaration, so a check is needed to avoid 403 errors in that scenario

feat(microservices): add noAssert option for RMQ connection

---

packages/microservices/external/kafka.interface.ts

Change `var` in `let`, as the CI in the pipeline gives a lint error (see screenshot)
another idea would also be to set `CompressionCodecs` like so:
```
export declare const CompressionCodecs: {
[CompressionTypes.GZIP]: () => any;
[CompressionTypes.Snappy]: () => any;
[CompressionTypes.LZ4]: () => any;
[CompressionTypes.ZSTD]: () => any;
};
```
using `declare const`

chore(): improvement on kafka interface

---

packages/platform-express/adapters/express-adapter.ts

Remove unused declarations ( see screenshot)
I also noticed that there is an implementation error ( see screenshot)
I am trying to figure out how to fix it, some idea?
It probably refers the `get errorHandler()` in this file:
https://github.com/nestjs/nest/blob/b98e4d2b1ff46e5a9afde8a9a062e47d35a64127/packages/common/file-stream/streamable-file.ts#L55

chore(express-adapter): remove unused declarations

---

packages/core/injector/instance-loader.ts
packages/core/injector/lazy-module-loader-options.interface.ts
packages/core/injector/lazy-module-loader.ts
packages/core/injector/silent-logger.ts

Issue Number: closes #9107 
```ts
const moduleRef = await this.lazyModuleLoader.load(() => LazyModule, { logger: false });
const moduleRef = await this.lazyModuleLoader.load(() => LazyModule); // logs enabled
```
I choose the name `logger` so we could enhance this feature later on without introducing breaking changes on that signature

feat(core): add option to disable logs on `LazyModuleLoader#load`

---

packages/common/module-utils/configurable-module.builder.ts
packages/common/module-utils/interfaces/configurable-module-async-options.interface.ts
packages/common/module-utils/utils/get-injection-providers.util.ts
packages/common/test/module-utils/configurable-module.builder.spec.ts
packages/common/test/module-utils/utils/get-injection-providers.util.spec.ts

Pass parent module providers to 'provideInjectionTokensFrom' in ConfigurableModuleAsyncOptions in order to pass options down in nested async modules.
Only necessary providers are taken by recursively looking on the 'inject' array.
Right now it is not easy to have a hierarchy of async modules because options' providers are not passed down the hierarchy. [This](https://stackoverflow.com/questions/65875076/nestjs-nested-async-inits-in-dynamic-modules) is an example of the problem. The solution I gave (pushing the options' providers after creating the module) breaks as soon you have more than one level of nesting.
In an ideal application all modules *should* be imported asynchronously and …

feat(common): pass options to nested async modules

---

packages/microservices/helpers/kafka-parser.ts
packages/microservices/test/client/client-kafka.spec.ts
packages/microservices/test/helpers/kafka-parser.spec.ts

Kafka parser modifies messages during parsing. If a message handler fails and message is retried by KafkaJS, then the already parsed message is parsed again and the value ends up being the string `'[object Object]'`. 
Issue Number: 9956
Kafka parser duplicates message objects and puts parsed data into these newly created objects. So retries are executed with the same data.
fix: #9956

fix(microservices): prevent kafka parser from modifying received message

---

packages/microservices/client/client-rmq.ts
packages/microservices/server/server-rmq.ts
packages/microservices/test/client/client-rmq.spec.ts

`RmqRecordDeserializer#deserialize` always got an `undefined` as options, cannot pair of `RmqRecordSerializer#serialize`
Pass Rmq Message properties as options, just like what `serialize` does

fix(microservices): pass options to rmq deserialize

---

packages/microservices/interfaces/microservice-configuration.interface.ts
packages/microservices/server/server-rmq.ts

Issue Number: https://github.com/nestjs/nest/issues/10029

feat(microservices): add "maxConnectionAttempts" option to RMQ, hide urls log

---

packages/core/repl/repl-context.ts
packages/core/repl/repl.ts

The `ReplContext` only uses the `.container` private property from the NestApplication, which is also available on NestApplicationContext, which doesn't require a httpAdapter.
Closes #10052

refactor(repl): use INestApplicationContext instead of full INestApplication

---

integration/repl/e2e/repl.spec.ts
packages/core/repl/repl-context.ts
packages/core/test/repl/native-functions/debug-repl-fn.spec.ts

Issue Number: closes #9893 + one minor feature
(see the code below)
Now the `debug()` function will
- display string tokens with double quotes, so we could easily distinguish between classes references, which also means that `$("Foo")` and `$(Foo)` aren't treated alike anymore. So we could have both providers (`class Foo {}` and `{ provide: "Foo", ... }`)
- display all those providers registered in the module properly
<details>
<summary>full code + demo</summary>
</details>
I'm not sure if treating string tokens in the same way as class references was intentional but I believe this decreases the flexiblity of the REPL

fix(core): when debug-repl has duplicated providers

---

integration/microservices/e2e/sum-grpc.spec.ts
integration/microservices/src/grpc/grpc.controller.ts
integration/microservices/src/grpc/math.proto
packages/microservices/client/client-grpc.ts

closes #10104
Issue Number:  [#10104](https://github.com/nestjs/nest/issues/10104)
`this.serializeError(error)` is called before returning an error in `client-grpc.ts`,
this matches the behavior to the the rest of `ClientProxy` implementations
I didn't find any test cases for error handling, please refer me to any if i missed it.
Added a basic test to make sure old behavior is not affected when `serializeError` is not overridden

fix(microservice): grpc-client serialize error

---

integration/send-files/e2e/express.spec.ts
integration/send-files/e2e/utils.ts
integration/send-files/src/app.controller.ts
integration/send-files/src/app.service.ts
packages/common/file-stream/streamable-file.ts

If a client currently closes the request before the stream finishes we get an error about not being able to send headers to a response that is already sent. It should be noted that this is express only, fastify does not have this issue
Issue Number: #10105
In the case of using `curl` or a similar tool on the command line,
or if the client decides to end the request for a streamed file early
without the check we would end up causing a server crash. Now, we will
just not send the response as the client has already decided how to
move on.
_Technically_ yes due to the fact that the server now no longer dies, but that is the expected case, so I believe this should be fine as a `patch` …

fix: add a check if the res is destroyed before sending response

---

packages/microservices/nest-microservice.ts

Issue Number: #10120
Closes #10120

fix(microservices): close underlying server once if already terminated

---

hooks/mocha-init-hook.ts
integration/auto-mock/src/bar.service.ts
integration/auto-mock/test/bar.service.spec.ts
integration/microservices/src/disconnected.controller.ts
integration/repl/src/users/users.controller.ts
packages/common/constants.ts
packages/core/injector/lazy-module-loader-options.interface.ts
packages/core/repl/native-functions/methods-repl-fn.ts
packages/core/repl/repl-context.ts
packages/microservices/ctx-host/kafka.context.ts
packages/microservices/test/ctx-host/kafka.context.spec.ts
sample/12-graphql-schema-first/src/graphql.schema.ts
sample/30-event-emitter/test/app.e2e-spec.ts

`npm run format` touches several files
`npm run format` & `npm run lint:fix` has nothing to fix anymore.

style: fix formatting

---

sample/31-graphql-federation-code-first/users-application/package-lock.json
sample/31-graphql-federation-code-first/users-application/package.json

Issue Number: https://github.com/nestjs/nest/issues/10129
There are breaking changes since `@apollo/subgraph@2.0.3`
=> @nestjs/graphql@10.0.19 already solved this problem
Sample project 31-graphql-federation-code-first/users-application can start normally

fix: upgrade @nestjs/graphql to 10.0.19

---

packages/core/adapters/http-adapter.ts

I noticed that types were missing in some abstract methods. (see screenshot)
I used `any` as the type, also since typescript if it does not find the type by default sets `any`, I preferred to use that at the moment.

chore(core): added types on the  methods abstract in http-adapter

---

integration/docker-compose.yml

`npm run test:docker:up` fails on M1 Mac with the error below:
```
Pulling mysql (mysql:8.0.28)...
8.0.28: Pulling from library/mysql
ERROR: no matching manifest for linux/arm64/v8 in the manifest list entries
```
This is because 8.0.28 doesn't support arm64 architecture.
We can run successfully `npm run test:docker:up` on M1 Mac because 8.0.29 and above supports arm64 architecture.

chore(integration): update mysql image to 8.0.30

---

packages/common/services/console-logger.service.ts
packages/common/test/services/logger.service.spec.ts

Issue Number: #10280
ConsoleLogger prints arrays as json like objects.

fix(common): stringify arrays on printing with console-logger

---

packages/microservices/ctx-host/kafka.context.ts
packages/microservices/server/server-kafka.ts
packages/microservices/test/ctx-host/kafka.context.spec.ts

Kafka producer is not exposed in `KafkaContext`
Issue Number:  #10263 
Kafka producer is exposed in `KafkaContext` under `getProducer()`
Closes #10263 
In order not to introduce a braking change, I added the producer as the last argument of `KafkaContextArgs`. It would look better if it were immediately after `consumer`.
Btw, I noticed that all Kafka related integration tests are skipped for being "flaky", therefore I didn't add one. Is this something that can be worked on to make them reliable?

feat(microservices): Add producer reference to KafkaContext

---

packages/microservices/listeners-controller.ts

Issue Number: #10184
Fixes #10184

fix(microservices): multiple scoped event handlers issue #10184

---

packages/common/cache/cache.constants.ts

In Nest v9 now that we use the `ConfigurableModuleBuilder` we no longer expose the `CACHE_MODULE_OPTIONS` token that we used to in v8
Re-expose the `CACHE_MODULE_OPTIONS` as an alias for `MODULE_OPTIONS_TOKEN` so that the cache module options can be easily overwritten in a test rather than having to `import { MODULE_OPTIONS_TOKEN } from '@nestjs/common/cache/cache.module-definitions'`

fix: export cache module options token under easy name

---

packages/common/serializer/class-serializer.interceptor.ts
packages/common/serializer/class-serializer.interfaces.ts
packages/common/serializer/decorators/serialize-options.decorator.ts
packages/common/serializer/index.ts

feat(common): allow to serialize plain object

---

packages/core/services/reflector.service.ts

perf(core): optimize reflector

---

packages/common/module-utils/interfaces/configurable-module-cls.interface.ts
packages/common/module-utils/interfaces/configurable-module-host.interface.ts

the `OPTIONS_TYPE` and `ASYNC_OPTIONS_TYPE` require all fields of `ExtraModuleDefinitionOptions`, but `ExtraModuleDefinitionOptions` has default values which are set in the `setExtras` function.
the `ExtraModuleDefinitionOptions` in `OPTIONS_TYPE` and `ASYNC_OPTIONS_TYPE` is partial.

fix(common): make `ExtraModuleDefinitionOptions` partial in `OPTIONS_TYPE`

---

packages/common/package.json

`cache-manager` v5 introduces breaking changes that now are leading to an error described here: https://github.com/node-cache-manager/node-cache-manager/issues/210 But `@nestjs/common@9.1.2` doesn't covers that at package installation time
Now we'll get an peer dep version mismatch on installing `cache-manager@5` due to the semver range constraint. Note that I didn't tested older version of `cache-manager` so I can't tell for sure if the range `<=4` is correct.
Read this comment made by Jay: https://github.com/node-cache-manager/node-cache-manager/issues/210#issuecomment-1264848047

chore(common): only allow cache-manager version <=4

---

packages/common/module-utils/configurable-module.builder.ts

More clean way
```ts
export const {
ConfigurableModuleClass,
MODULE_OPTIONS_TOKEN,
OPTIONS_TYPE,
ASYNC_OPTIONS_TYPE,
}
= new ConfigurableModuleBuilder<MyOptions>().setExtras(
{
isGlobal: false,
},
// definition => definition, // we don't need this function if this PR is accepted
).build()
/**
* This module is only for generating options
*/
@Module({
exports: [MODULE_OPTIONS_TOKEN],
})
export class HttpBaseModule extends ConfigurableModuleClass {
}
@Module({})
export class HttpModule {
private static innerRegister(baseModule: DynamicModule, isGlobal = false): DynamicModule {
return {
module: HttpModule,
global: isGlobal,
providers: [Xxx], // this provider will consume …
```

feat(common): make `transformDefinition` optional

---

packages/common/cache/cache.providers.ts
packages/common/package.json

Currently with `cache-manager@5` there is an error about `get is not a function` on the store.
Issue Number: https://github.com/nestjs/docs.nestjs.com/pull/2487
https://github.com/node-cache-manager/node-cache-manager/issues/210
With the new `cachingFactory` we can support either v4 or v5 and use the proper `caching` method. I've tested v5 locally with success and the current tests still pass, confirming that v4 is unaffected.
If we'd rather just wait for Nest 10 to upgrade to cache-manager v5 that's fine too. Just giving us the option :smile_cat:

fix: support cache manager v4 and v5

---

packages/common/cache/cache.providers.ts

E2E tests failed using cache-manager v5 due to a difference in cache factory type and a need to `await` an async method
Issue Number: 10348
The new cache-manager 5 and cache-manager 4 are both supported, with integration tests passing
<details>
<summary>Tests with v5</summary>
```
nest at   on  fix/cache-v5 [ ] is  v9.1.2 via  v16.17.1 with 
❯ npx mocha integration/cache/e2e/*.spec.ts --reporter=spec
Async Register
✔ should be defined
✔ should return empty
✔ should return data
Caching Multi Store
✔ should return empty
✔ should return data
5 passing (167ms)
nest at   on  fix/cache-v5 [ ] is  v9.1.2 via  v16.17.1 with  took 2s
❯ npm ls cache-manager
@nestjs/core@9.1.2 ~/
└── …
```

fix: update factory to account for old v4 syntax for cache stores

---

packages/common/cache/cache.providers.ts

Revert "fix: update factory to account for old v4 syntax for cache stores"

---

packages/core/nest-application.ts

In `#getUrl()` we basically have the following flow when calling it before `#listen()`
```js
function getUrl() {
return new Promise((resolve, reject) => {
if (true) {
reject('something went wrong')
console.log('-----------') // this will be evaluated
}
// and so the following
resolve('useless evaluation')
})
}
getUrl()
.then(() => console.log('not called'))
.catch(() => console.error('called'))
```
```bash
$ node sample.js 
-----------
called
```
We don't have to call `resolve()` nor `formatAddress()` as they won't be used in the end.

refactor(core): early return on rejection on `getUrl`

---

integration/cache/src/async-register/config/cache.config.ts
packages/common/cache/cache.providers.ts
packages/common/cache/interfaces/cache-manager.interface.ts

This reverts commit 530af92.
Reverting a revert, I know, always fun! The flakiness of the tests came from how v5 uses milliseconds whereas v4 uses seconds to the `ttl`. This caused our tests to not pass because the HTTP calls weren't _quite_ fast enough all of the time. 
I updated the timing of the tests to be 100seconds or 100 milliseconds depending on the cache-manager version and that seems to have stabilized the test. The other option we have here would be to automatically multiply the `ttl` given to the `CacheModule.register/Async()` by `1000` to convert the `ms` to `s`. This would make other user's transition from v4 to v5 smoother, however, if someone were to put in a seconds …

Revert "Revert "fix: update factory to account for old v4 syntax for cache stores""

---

packages/common/cache/interfaces/cache-manager.interface.ts

Registering stores that implement new `CacheStore` interface ([here](https://github.com/node-cache-manager/node-cache-manager/blob/master/src/caching.ts#L36)) from new `cache-manager` module leads to typescript error for type mismatch.
It no longer gives error because of updated `CacheStore` interface in nest cache module.

fix(common): fix cache-manager v5 type compatibility

---

packages/common/services/console-logger.service.ts

allow overriding of timestampDiff formating
Currently there is no way to override timestampDiff formating by extending ConsoleLogger. This feature is required if we want to extend and create JsonConsoleLogger that emits json without any formating
Related: https://github.com/nestjs/nest/issues/10342
We can now override contextMessage formating by overriding `formatTimestampDiff` method
Related: https://github.com/nestjs/nest/pull/10364

feat(common): ConsoleLogger: extract protected formatTimestampDiff

---

packages/common/services/console-logger.service.ts

allow overriding of context formating
Currently there is no way to override contextMessage formating by extending ConsoleLogger. This feature is required if we want to extend and create JsonConsoleLogger that emits json without any formating
Related: https://github.com/nestjs/nest/issues/10342
We can now override contextMessage formating by overriding `formatContext` method

feat(common): ConsoleLogger: extract protected formatContext method

---

sample/06-mongoose/src/cats/schemas/cat.schema.ts

Currently, techniques/mongodb doc uses intersection type for defining the mongoose document interface.
```ts
import { Document } from 'mongoose';
export type CatDocument = Cat & Document;
```
it was okay before mongoose@6.3.2 but after that, they replaced the use of `this` with generics(`T`) in many `Document` methods so it infers incorrectly now.
```ts
// before
toObject(options?: ToObjectOptions): LeanDocument<this>;
toObject<T = DocType>(options?: ToObjectOptions): T;
// latest
toObject<T = LeanDocument<DocType>>(options?: ToObjectOptions): Require_id<T>;
// from: https://github.com/Automattic/mongoose/commit/659436de47d55aaa0a984b8f4cc99232c5ca8a16
```
```ts
type CatDocument = Cat …
```

sample(mongoose): change the way to define the mongoose document interface

---

packages/common/pipes/file/parse-file-pipe.builder.ts
packages/common/test/pipes/file/parse-file-pipe.builder.spec.ts

Currently it is not possible to add custom file validators using the `ParseFilePipeBuilder`.
This PR adds an `addValidator(validator: FileValidator)` function, which can be used to add additional validators.
My use-case for this feature is adding a [file-type](https://github.com/sindresorhus/file-type) based mime validator. This change would also allow extending the `ParseFilePipeBuilder` class with custom builder functions.

feat(common): Allow adding custom validators to ParseFilePipeBuilder

---

packages/core/repl/repl.ts

Issue Number: #10494 
`repl()` function can accept DynamicModule type parameter.

fix(core): change `repl()` function param type to `Type | DynamicModule`

---

packages/platform-express/adapters/express-adapter.ts
packages/platform-express/interfaces/nest-express-application.interface.ts

feat(plataform-express): replace `any` return type on `#listen` with `Server`

---

packages/common/exceptions/bad-gateway.exception.ts
packages/common/exceptions/bad-request.exception.ts
packages/common/exceptions/conflict.exception.ts
packages/common/exceptions/forbidden.exception.ts
packages/common/exceptions/gateway-timeout.exception.ts
packages/common/exceptions/gone.exception.ts
packages/common/exceptions/http-version-not-supported.exception.ts
packages/common/exceptions/http.exception.ts
packages/common/exceptions/im-a-teapot.exception.ts
packages/common/exceptions/internal-server-error.exception.ts
packages/common/exceptions/method-not-allowed.exception.ts
packages/common/exceptions/misdirected.exception.ts
packages/common/exceptions/not-acceptable.exception.ts
packages/common/exceptions/not-found.exception.ts
packages/common/exceptions/not-implemented.exception.ts
packages/common/exceptions/payload-too-large.exception.ts
packages/common/exceptions/precondition-failed.exception.ts
packages/common/exceptions/request-timeout.exception.ts
packages/common/exceptions/service-unavailable.exception.ts
packages/common/exceptions/unauthorized.exception.ts
packages/common/exceptions/unprocessable-entity.exception.ts
packages/common/exceptions/unsupported-media-type.exception.ts
packages/common/test/exceptions/http.exception.spec.ts

add error options object to HttpException constructor to allow use of error cause along with custom message.
We can only pass either a custom description or a cause error object.
Issue Number: #10392 
We can now use both custom messages and error cause with the following API:
```ts
const error = new HttpException('customDescription', 400, {
cause: new Error(),
});
```
We have yet to define what is the expected behavior when someone mistakenly passes both the first argument as an Error and also the `options` object with a cause. In that case, should we always consider the `cause` property or throw an error, @kamilmysliwiec ?

feat(common): add error options object

---

.gitignore
packages/core/errors/exceptions/unknown-request-mapping.exception.ts
packages/core/errors/messages.ts
packages/core/router/router-explorer.ts
packages/core/test/exceptions/external-exception-filter-context.spec.ts
packages/core/test/exceptions/external-exceptions-handler.spec.ts
packages/core/test/router/router-explorer.spec.ts

If we have an invalid controller class listed in some `controllers` array, we'll got this error:
Now the error will looks like this:
Also, I've leverage on this PR to increase the code coverage on `/core/exceptions` a bit as well because why not :cat: 
<details>
<summary>before</summary>
</details>
<details>
<summary>now</summary>
</details>

feat(core): display class's name on request mapping exceptions

---

integration/nest-application/sse/e2e/express.spec.ts
integration/nest-application/sse/e2e/fastify.spec.ts
integration/nest-application/sse/src/app.controller.ts
integration/nest-application/sse/src/app.module.ts
integration/nest-application/sse/tsconfig.json
packages/common/interfaces/nest-application-options.interface.ts
packages/platform-express/adapters/express-adapter.ts
sample/28-sse/src/main.ts

Issue Number: #9517 
When using long living HTTP connections (like SSE/Keep-Alive connecitons), in conjuction with `app.enableShutdownHooks()` exposed a flaw. When there are keep alive connections in our HTTP server, they would never get closed. This would cause our HTTP adapter to endlessly wait on them until a second restart.
Because the shutdown hooks would halt at `httpAdapter.close()`, the rest of the application shutdown logic would also never run.
We keep track of open connections in our Express adapter. When `httpAdapter.close()` is called, we iterate these open connections and close them.
On that note: this fix is superfluous for Fastify. Fastify has the …

fix(platform): shutdown hooks not firing caused by open http connections

---

.circleci/config.yml
integration/injector/e2e/optional-factory-provider-dep.spec.ts
packages/core/errors/messages.ts
packages/core/test/errors/test/messages.spec.ts

Sometimes people wrongly put things that aren't modules inside `imports` array, which leads to errors such as:
in this example we have a class annotated with `@WebSocketGateway()` placed at `imports` array of `EventsModule`
I found that sometimes people didn't understand that the error message tells that `EventsGateway` is being treated as a nestjs module
In the scenario described above, the error message will be:
I hope that with this minor change people we now understand why they got that error faster.
I'm a bit concerd on the proposed message tho. Another suggestion would be:
```
- If ${dependencyName} is a provider, is it part of the current module Module?
- If ${dependencyName} is …
```

feat(core): add hint to unknown dependency error msg

---

package.json

the packages: 
"@types/redis": "4.0.11",
"@types/reflect-metadata": "0.1.0"
are deprecated and the libraries provide their own types, so those won't be needed 

build: remove deprecated type deps

---

integration/cache/src/multi-store/multi-store.module.ts
packages/common/cache/cache.providers.ts

Issue Number: #10590 
CacheModule uses cache store object

fix(cache): use passed store object

---

packages/core/router/router-proxy.ts

Fastify requires us to return the response object when handling async methods and dealing with exceptions, otherwise a thenable gets wrapped and improperly handled later causing an exception. This is shown by [this repo][1] and discuessed in [this issue][2].
[1]: https://github.com/sgrigorev/nestjs-compress-issue
[2]: https://github.com/fastify/fastify-compress/issues/215#issuecomment-1210598312
If we use a fastify plugin, like `@fastify/compress` and there is an error handled by the exception filter, we end up getting a response without any body, and if the `onSend` hook is debugged we will see that it gets called twice, once with the proper response and once with an `undefined` …

fix(fastify): return the response on exception

---

packages/common/services/console-logger.service.ts
packages/common/services/logger.service.ts

This is the profiler information when we call `#log` method 10.000 times:
```
[Bottom up (heavy) profile]:
Note: percentage shows a share of a particular caller in the total
amount of its parent calls.
Callers occupying less than 1.0% are not shown.
ticks parent  name
958   56.8%  /home/h4ad/.asdf/installs/nodejs/12.22.12/bin/node
763   79.6%    v8::internal::Builtin_DatePrototypeToLocaleString(int, unsigned long*, v8::internal::Isolate*)
560   73.4%      LazyCompile: *getTimestamp /home/h4ad/Projects/opensource/performance-test-nestjs/test-performance/node_modules/@nestjs/common/services/console-logger.service.js:104:17
510   91.1%        LazyCompile: *log …
```

perf(common): faster logs by caching intl.datetimeformat

---

packages/core/injector/module-ref.ts
packages/core/injector/module.ts

when suppling an empty object as options to `ModuleRef#get` and `ModuleRef#resolve` methods, defaults options are not taking in count 
```ts
@Module({
providers: [{ provide: 'foo', useValue: 123 }]
})
class Foo {}
@Module({
imports: [Foo]
})
export class AppModule {
constructor(private readonly moduleRef: ModuleRef) {}
onModuleInit() {
this.moduleRef.get('foo', {}) // ends up being { strict: undefined, each: undefined }
// returns [123]
// which is wrong since "strict" should be enabled by default and the provider is out of this module
}
}
```
```ts
this.moduleRef.get('foo', {}) // will raise an 'not found provider' error since "strict" is enabled
```
I also fixed the type def for the …

fix(core): ModuleRef#get and #resolve opts default values

---

packages/platform-fastify/adapters/fastify-adapter.ts

Fix fastify reply context prop for new fastify versions
Issue Number: #10781
Middleware error not cause application crash, error is sent by http by error filter properly

[platform-fastify]fix: :bug: Fix context prop

---

packages/common/decorators/core/inject.decorator.ts
packages/common/decorators/core/optional.decorator.ts

fix(common): inject decorator should allow key to be undefined

---

packages/platform-express/multer/multer/multer.constants.ts
packages/platform-express/multer/multer/multer.utils.ts
packages/platform-express/test/multer/multer/multer.utils.spec.ts

Some malformed requests return as 500 instead of 400. This can be worked around by a custom exception filter, but it would be great for the MulterModule to handle this natively.
`multer` errors, as well as some raw `busboy/multipart` errors now return as 400 instead of 500.

fix(express): Map missing multer error and map busboy errors

---

packages/core/nest-application-context.ts

At the moment, when manually invoking the `app.close()`, no signal can be passed to the shutdown hooks (`beforeApplicationShutdown` & `onApplicationShutdown`). This means creating custom graceful shutdown implementations are limited by the fact that something simple as a signal can't be used for handling shutdown features.
By adding the possibility the pass a signal to the `app.close()` function, which is still not required, the signal can be used in shutdown hooks, even when custom graceful shutdown implementations are made. Although it's a small feature, it makes creating graceful shutdowns somewhat easier, even if it's for logging only for example.

feat(core): pass signal when manually invoking close

---

packages/microservices/client/client-nats.ts

The debug message of nats server is annoying and its cant be disabled.
`DEBUG [Server] NatsStatus: type: "pingTimer", data: "1".`
Issue Number: 10783
My propose it is extends the implementation existed flag **debug** of **MicroserviceOptions** for disable **pingTimer** message.

refactor(microservices): disable ping timer message in nats by flag

---

packages/core/injector/instance-wrapper.ts
packages/core/test/injector/instance-wrapper.spec.ts

If an instance has at least one dependency that is Request scope non durable, then the instance should be Request scope non durable itself.
Closes #10594

fix(core): Making Request scope non durable win over scope durable

---

package-lock.json
package.json

currently, typings for cache-manager are in devDependencies. These are for [version 4](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/cache-manager/index.d.ts) but the `cache-manager` version installed is `5.1.3` and it already comes with built-in types, so this dependency is unnecessary
This removes an unneeded development dependency. The behavior is the same.

chore(deps): remove old cache-manager typings

---

packages/core/injector/injector.ts
packages/core/test/injector/injector.spec.ts

Currently `reflectConstructorParams` mutates the original constructor parameter type metadata when applying the parameter decorator information.
It uses a shallow copy of the metadata so it doesn't mutate the original.

fix(core): fix reflectConstructorParams mutating constructor metadata

---

package-lock.json
package.json
packages/common/utils/random-string-generator.util.ts
packages/core/scanner.ts

The method `randomStringGenerator` is implemented with `uuid` package, which is slow when we compare with other package like `uid`:
```
uuid x 4,724,786 ops/sec ±2.35% (81 runs sampled)
nanoid x 2,880,683 ops/sec ±2.16% (79 runs sampled)
uid x 37,413,066 ops/sec ±1.91% (85 runs sampled)
Fastest is uid
```
> [Benchmark](https://gist.github.com/H4ad/0d4efdf2b1ccd2f944419671aabb9db2)
This method is also used inside `instance-wrapper.ts`, which is instantiated a lot during the initialization of NestJS, above the profiling information:
```
[Shared libraries]:
ticks  total  nonlib   name
35505   66.5%          /home/h4ad/.asdf/installs/nodejs/12.22.12/bin/node
725    1.4% …
```

perf(common): faster random string generator

---

packages/core/metadata-scanner.ts

I run some performance tests on `NestFactory.create(AppModule, { logger: false })` and I found that the function `getAllFilteredMethodNames` was heavily called on NodeJS profiler.
```
[Bottom up (heavy) profile]:
Note: percentage shows a share of a particular caller in the total
amount of its parent calls.
Callers occupying less than 1.0% are not shown.
ticks parent  name
6488   80.6%  /home/h4ad/.asdf/installs/nodejs/16.16.0/bin/node
2883   44.4%    /home/h4ad/.asdf/installs/nodejs/16.16.0/bin/node
407   14.1%      /home/h4ad/.asdf/installs/nodejs/16.16.0/bin/node
133   32.7%        LazyCompile: *getAllFilteredMethodNames /home/h4ad/Projects/opensource/performance-test-nestjs/test-perf …
```

perf(core): better performance to get method names

---

packages/core/middleware/middleware-module.ts
packages/core/router/router-explorer.ts
packages/microservices/listeners-controller.ts

regression introduce at v9.1.1
When injecting `REQUEST` for non-durable providers, its value is always being context payload even when the injectable chain is not durable, like this:
```ts
@Injectable({ scope: Scope.REQUEST, durable: false })
class AppService {
constructor(@Inject(REQUEST) private readonly req: any) {
console.log('Is req fasly?', !!req === false) // true but should be false
}
isReqDefined() {
return typeof this.req !== 'undefined' // false but should be true
}
}
@Controller() // request-scoped but not durable, due to its dependency
class AppController {
constructor(private readonly appService: AppService) {}
@Get()
getHello() {
return {
is_req_defined: …
```

fix(core,microservices): inject the context when the tree is not durable

---

packages/core/middleware/middleware-module.ts
packages/core/middleware/utils.ts
packages/core/nest-application.ts
packages/core/router/interfaces/exclude-route-metadata.interface.ts
packages/core/test/application-config.spec.ts
packages/core/test/router/route-path-factory.spec.ts

PR https://github.com/nestjs/nest/pull/9332 fixes https://github.com/nestjs/nest/issues/9124, but will introduce a bug - the global prefix will not work if middleware register in `'*'` route. For example, run the code below and visit `http://localhost:3000/test` should not get `{hello: 'hi'}` response, but actually will get. This means `setGlobalPrefix` not work.
```ts
import { NestFactory } from '@nestjs/core';
import { Injectable, MiddlewareConsumer, Module, NestMiddleware, NestModule } from "@nestjs/common";
import type { Request, Response, NextFunction } from 'express';
@Injectable()
export class EngineMiddleware implements NestMiddleware {
use(_req: Request, res: Response, _next: NextFunction) {
res.json({hello: 'hi'})
}
}
@Module({})
export class AppModule implements NestModule { …
```

fix(core): fix global prefix not working

---

packages/core/nest-application-context.ts
packages/core/test/nest-application-context.spec.ts

Apollo server has own process listener which used in NestJS graphql https://unpkg.com/browse/apollo-server-core@3.0.1/src/ApolloServer.ts
NestJs implementation https://github.com/nestjs/nest/blob/master/packages/core/nest-application-context.ts#L308
so both libs listen SIGINT code and NestJs just after start remove own listeners and then start waiting promise results, in same time event loop go to Apollo handler and just after Apollo server is down it send process.kill event, but NestJs already removed own handler, so app close without wait all promises inited by NestJs

fix(core): process exit before shutdown hook end

---

integration/nest-application/use-body-parser/e2e/express.spec.ts
integration/nest-application/use-body-parser/e2e/fastify.spec.ts
integration/nest-application/use-body-parser/src/app.controller.ts
integration/nest-application/use-body-parser/src/app.module.ts
integration/nest-application/use-body-parser/tsconfig.json
packages/common/interfaces/http/http-server.interface.ts
packages/core/adapters/http-adapter.ts
packages/core/nest-application.ts
packages/platform-express/adapters/express-adapter.ts
packages/platform-express/interfaces/index.ts
packages/platform-express/interfaces/nest-express-application.interface.ts
packages/platform-express/interfaces/nest-express-body-parser-options.interface.ts
packages/platform-fastify/adapters/fastify-adapter.ts
packages/platform-fastify/interfaces/index.ts
packages/platform-fastify/interfaces/nest-fastify-application.interface.ts
packages/platform-fastify/interfaces/nest-fastify-body-parser-options.interface.ts

Issue Number: #10471 
It wasn't possible to set a body parser limit, and have the `rawBody` functionality work together.
We expose a new `app.useBodyParser()`. This allows configuring the application with specific body parser settings, and it respects the application's `rawBody` option. The implementation is Express and Fastify specific.
I kept the `useBodyParser` function on `HttpAdapter` as an optional method.
Reviewing this commit by commit is the best way to go about it.

[Feature] Allow registering body parsers, while respecting application's `rawBody` option

---

packages/platform-fastify/adapters/fastify-adapter.ts

When using NestJS behind Microsoft IIS, the following error occurs : **options.port should be >= 0 and < 65536. Received NaN.**
Issue Number: #10602
No error message - calling listen() with a full FastifyListenOptions object is supported:
```javascript
async function bootstrap() {
const app = await NestFactory.create<NestFastifyApplication>(
AppModule,
new FastifyAdapter({ logger: true, ignoreTrailingSlash: true })
);
await app.listen({ port: '3000', host: 'localhost', path:'pipe' }, '0.0.0.0');
}
```
Microsoft IIS (and IISNode) uses a named pipe to communicate with Node - thus the "port" is not a number (it's a string). Supporting Fastify's latest syntax for listen() is mandatory to …

Adapt fastify adapter to comply with fastify.listen(FastifyListenOptions) - and make it compatible with Microsoft IIS

---

packages/common/cache/interfaces/cache-manager.interface.ts

After cache-manager v5, `cacheManager.caching` method has been allowed to receive synchronous or asynchronous store factory function, but current nest's interface is still accepting v4 styled factory type only.
update `CacheStoreFactory` as union type to match pure factory function.
packages:
- NestJS: 9.2.0
- cache-manager-ioredis-yet: 1.0.1

fix(common): CacheStoreFactory type

---

packages/common/services/logger.service.ts
packages/common/test/services/logger.service.spec.ts

The error() function of a logger has two optional parameters: the trace and the context. The logger now no longer passes the global context as the first optional parameter when there are is no value supplied for the trace parameter. Instead, the trace parameter is passed as undefined and the context is passed as the second optional parameter.
This fixes a bug where the trace is overwritten by the context when passed to custom loggers. Fixes gremo/nest-winston#473
When implementing a custom logger, instantiating the Nest `Logger` with a context and then calling `logger.error(message)`, the Nest logger will call the underlying logger's function with `customLogger.error(message, …

fix(common): correct order for logger error parameters

---

packages/common/pipes/file/parse-file.pipe.ts

The parse file validation pipe doesn't work if multiple files were passed.
- ParseFilePipe will now handle multiple files validations where the `IUploadValidatorOptions` will be applied to each file.
- It still works with single file as it already was.
I'm aware of the existing pull-request that introduces a similar solution, I tried to help with it but it seems to be abandoned, so I create this one to help ship this improvement quicker.

Parse file pipe fix (multiple files validation)

---

packages/microservices/server/server-nats.ts

The debug message of nats server appears even if debug mode is false, it seems that was fixed only on client side, not server one.
DEBUG [Server] NatsStatus: type: "pingTimer", data: "1".
Issue Number: [10783](https://github.com/nestjs/nest/issues/10783)
I filter out message if debug mode is false.

refactor(microservices): use switch case for types of statuses in server

---

integration/hello-world/e2e/exceptions.spec.ts
integration/hello-world/src/errors/errors.controller.ts
packages/platform-express/adapters/express-adapter.ts
packages/platform-fastify/adapters/fastify-adapter.ts

If the developer overrides the Content-Type header but doesn't add a custom ExceptionFilter to handle unexpected errors, Nest will respond with a JSON error object. This response wouldn't match the content type.
Fastify will throw another error about this mismatch, potentially leaking internal details.
Issue Number: #8469
The HTTP adapters check if we're trying to send a JSON object despite having a custom Content-Type. If yes, it overrides the Content-Type and adds a warning.
If an app uses a more exotic content type, that is none-the-less JSON (like `application/scim+json`) and relies upon the internal server error, the application will override the content type, potentially breaking …

Fix Content-Type for unexpected errors in Fastify

---

packages/microservices/client/client-rmq.ts
packages/microservices/test/client/client-rmq.spec.ts

Issue Number: https://github.com/nestjs/nest/issues/10562

fix(microservices): rmq should gracefully reconnect upon error

---

packages/core/inspector/uuid-factory.ts

Using relative path import will fail in pnpm workspace
```
Error: Cannot find module '../../common/utils/random-string-generator.util'
Require stack:
- /path/to/project/node_modules/.pnpm/@nestjs+core@9.3.1/node_modules/@nestjs/core/inspector/uuid-factory.js
- /path/to/project/node_modules/.pnpm/@nestjs+core@9.3.1/node_modules/@nestjs/core/injector/instance-wrapper.js
```
No errors

fix(core): import common package correctly

---

packages/microservices/client/client-kafka.ts
packages/microservices/test/client/client-kafka.spec.ts

Issue Number: https://github.com/nestjs/nest/issues/10449

fix(microservices): messages emitted before kafka client is ready fail

---

packages/platform-fastify/adapters/fastify-adapter.ts
packages/platform-fastify/interfaces/external/fastify-static-options.interface.ts
packages/platform-fastify/interfaces/external/fastify-view-options.interface.ts
packages/platform-fastify/interfaces/nest-fastify-application.interface.ts

In continuation of PR https://github.com/nestjs/nest/pull/10975
Not all user-facing APIs are annotated with `@publicApi`, which, from contributors like myself who help in NestJS, could lead to some confusion as to which APIs can be changed without breaking any changes.
If there are private APIs that are not public, which I forgot, please let me know so I can update the PR.

chore(fastify): mark facing apis public fastify

---

packages/testing/interfaces/override-by-factory-options.interface.ts
packages/testing/interfaces/override-by.interface.ts
packages/testing/services/testing-logger.service.ts
packages/testing/testing-injector.ts
packages/testing/testing-instance-loader.ts
packages/testing/testing-module.builder.ts
packages/testing/testing-module.ts
packages/websockets/context/exception-filters-context.ts
packages/websockets/decorators/connected-socket.decorator.ts
packages/websockets/decorators/gateway-server.decorator.ts
packages/websockets/decorators/socket-gateway.decorator.ts
packages/websockets/decorators/subscribe-message.decorator.ts
packages/websockets/exceptions/base-ws-exception-filter.ts
packages/websockets/exceptions/ws-exceptions-handler.ts
packages/websockets/interfaces/gateway-metadata.interface.ts
packages/websockets/interfaces/hooks/on-gateway-connection.interface.ts
packages/websockets/interfaces/hooks/on-gateway-disconnect.interface.ts
packages/websockets/interfaces/hooks/on-gateway-init.interface.ts
packages/websockets/interfaces/nest-gateway.interface.ts
packages/websockets/interfaces/server-and-event-streams-host.interface.ts
packages/websockets/interfaces/web-socket-server.interface.ts
packages/websockets/interfaces/ws-response.interface.ts

In continuation of PR https://github.com/nestjs/nest/pull/10975, https://github.com/nestjs/nest/pull/11032, https://github.com/nestjs/nest/pull/11033
Not all user-facing APIs are annotated with `@publicApi`, which, from contributors like myself who help in NestJS, could lead to some confusion as to which APIs can be changed without breaking any changes.
Add `@publicApi` in:
- testing
If there are private APIs that are not public, which I forgot, please let me know so I can update the PR.

chore(testing, websockets): mark facing apis public

---

package-lock.json
package.json
packages/core/injector/module-token-factory.ts
packages/core/package.json
packages/core/test/injector/module-token-factory.spec.ts

This PR aims to improve the speed of `ModuleTokenFactory#create`, today, here's the profiler information of the initialization (when we initialize 10k times):
```
[Shared libraries]:
ticks  total  nonlib   name
36828   80.3%          /home/h4ad/.asdf/installs/nodejs/16.16.0/bin/node
614    1.3%          /usr/lib/x86_64-linux-gnu/libc-2.31.so
7    0.0%          [vdso]
1    0.0%          /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.28
[JavaScript]:
ticks  total  nonlib   name
562    1.2%    6.7%  LazyCompile: *_object /home/h4ad/Projects/opensource/performance-analysis/test-performance-nestjs/node_modules/object-hash/index.js:192:22
475    1.0%    5.6%  LazyCompile: *InstanceWrapper …
```

perf: module token factory fast path

---

packages/core/metadata-scanner.ts
packages/core/repl/native-functions/methods-repl-fn.ts
packages/core/router/paths-explorer.ts
packages/core/scanner.ts
packages/core/test/metadata-scanner.spec.ts
packages/microservices/listener-metadata-explorer.ts
packages/microservices/test/listeners-metadata-explorer.spec.ts
packages/websockets/gateway-metadata-explorer.ts
packages/websockets/test/gateway-metadata-explorer.spec.ts

This is the current profiler information when we instantiate Nest 10k.
```
[Shared libraries]:
ticks  total  nonlib   name
36987   80.4%          /home/h4ad/.asdf/installs/nodejs/16.16.0/bin/node
633    1.4%          /usr/lib/x86_64-linux-gnu/libc-2.31.so
4    0.0%          /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.28
3    0.0%          [vdso]
[JavaScript]:
ticks  total  nonlib   name
497    1.1%    5.9%  LazyCompile: *_object /home/h4ad/Projects/opensource/performance-analysis/test-performance-nestjs/node_modules/object-hash/index.js:192:22
420    0.9%    5.0%  LazyCompile: *InstanceWrapper /home/h4ad/Projects/opensource/performance-analysis/test-performance-nestjs/node_modules/@nestj …
```

perf: metadata scanner

---

packages/common/cache/interceptors/cache.interceptor.ts

If the `CacheIntereceptor` is used and a `StreamableFile` is returned, the class instance won't be properly cached due to serialization of the stream. 
Issue Number: #10575 
This is the easier fix to do rather than taking the stream and serializing it to something that can be cached in. If we'd rather actually serialize the stream I can work on that functionality instead

fix: skip caching the response if it is a streamable file instance

---

packages/core/package.json

Closes #11068
Currently Yarn 3.x PnP support is broken.
Issue Number: 11068
Works with Yarn 3.x PnP now.

build(core): need to depend on the uid

---

packages/common/services/console-logger.service.ts
packages/common/test/services/logger.service.spec.ts

Due to a change in #10531 when the `stack` is added as `undefined` a new `undefined` log would be added whenever `this.logger.error()` would be called. 
Issue Number: #11074
Now, we check that the last element is either a string or undefined, and if so strip the last element. That element should only exist when we artificially add the stack via the changes from #10531.
This at least shouldn't be breaking. Added a new test to ensure it does what I expect it to as well.

fix(common): account for when stack is undefined in logger

---

packages/core/test/injector/instance-wrapper.spec.ts

Added test for staticity calcuation when circular dependency present
Added a few new unit tests to verify that the calculation of isTreeStatic and isTreeDurable is correct even for circular dependencies.

test(core): :white_check_mark: added tests for checking durability and staticity calculation when circular dependency

---

integration/injector/src/self-injection/self-injection-provider.module.ts
integration/send-files/e2e/utils.ts
packages/common/cache/interceptors/cache.interceptor.ts
packages/common/module-utils/configurable-module.builder.ts
packages/common/test/decorators/injectable.decorator.spec.ts
packages/common/test/exceptions/http.exception.spec.ts
packages/common/test/pipes/validation.pipe.spec.ts
packages/core/errors/messages.ts
packages/core/injector/helpers/transient-instances.ts
packages/core/repl/repl-context.ts
packages/core/test/helpers/context-utils.spec.ts
packages/core/test/injector/instance-wrapper.spec.ts
packages/core/test/router/router-explorer.spec.ts
packages/core/test/scanner.spec.ts
packages/microservices/external/kafka.interface.ts
packages/microservices/test/client/client-grpc.spec.ts
packages/microservices/test/json-socket/message-parsing.spec.ts
packages/microservices/test/listeners-controller.spec.ts
packages/platform-fastify/interfaces/nest-fastify-application.interface.ts
sample/31-graphql-federation-code-first/README.md
sample/32-graphql-federation-schema-first/README.md
tools/gulp/util/task-helpers.ts

This PR fixes a few random typos (this was a trial run for [a CLI I made](https://github.com/Lioness100/rspell))
I don't think so, but I did notice that `ConsumerReceivedUnsubcribedTopicsEvent` (now `ConsumerReceivedUnsubscribedTopicsEvent`) was exported, so maybe.

docs: fix typos

---

packages/core/helpers/index.ts

Allow third party packages to register handlers (like controller methods) that pass through the whole pipeline of interceptors, pipes, guards, filters and param decorators while still being compliant with node16 moduleResolution, where imports like
```typescript
import {
ExternalContextCreator,
ParamsFactory,
} from "@nestjs/core/helpers/external-context-creator";
```
are not allowed.
No tests are added here because functionality is not changed.
`ExternalContextCreator` and `ParamsFactory` are not exposed for third party packages to use.
`ExternalContextCreator` and `ParamsFactory` are exposed for third party packages to use.
No tests are added because no …

feat(core): expose external-context-creator

---

packages/common/pipes/parse-array.pipe.ts
packages/common/test/pipes/parse-array.pipe.spec.ts

ParseArrayPipe is parsing the input as number even though String is requested.
Not implemented, but it should parse only string.

Add test case for ParseArrayPipe that doesn't work as expected

---

packages/platform-ws/adapters/ws-adapter.ts

If the message handler return `false`, the `ws-adapter` will filter this result.
Only nil results will be filtered. This behavior is the same as `io-adapter`. 
By the way, I don't think `null` should be filtered 🤔.

fix(ws): filter only nil results

---

sample/24-serve-static/src/app.module.ts

Updated path specification to working one #92.
Problem with [example 24](sample/24-serve-static/src/app.module.ts) is, that exclude isn't working, it still redirects to static content if API path does not exist.
Works as expected. If API path not found, it returns HTTP 404.

Updated excluded path in 24-serve-static example

---

packages/platform-express/adapters/express-adapter.ts
packages/platform-express/interfaces/nest-express-application.interface.ts

Issue Number: closes #11279
I just tested that `server` from `app.listen` is an instance of `http.Server`

fix(platform-express): wrong type def for `NestExpressApplication#listen`

---

integration/cache/e2e/custom-ttl.spec.ts
integration/cache/src/custom-ttl/custom-ttl.controller.ts
integration/cache/src/custom-ttl/custom-ttl.module.ts
integration/cache/src/custom-ttl/tsconfig.json
packages/common/cache/interceptors/cache.interceptor.ts

Currently the ``@CacheTTL`` decorator does not work. With cachemanager v5
Issue Number: #11119 
``@CacheTTL`` Works again and the behavior is inline with the docs (expects milliseconds)
The interceptor has been updated to also check, like the provider does, if version 5 or later is beeing used.
If so the inteceptor uses the new signature for the ``set(key, value, ttl)`` method. Version 4 used an options object as third paremeter. V5 uses a number directly.
Because it checks which version of cache manager is beeing used.

fix(common): fix cache ttl not beeing respected

---

packages/common/services/console-logger.service.ts
packages/common/test/services/logger.service.spec.ts
packages/common/utils/shared.utils.ts

In certain case, it is very expensive to log some values. Instead of checking if certain level is enabled, allow the users to pass in a function that is only called if we need to stringify the log value.
This keeps the API small, while still allowing expensive logging to be called when needed, and skipped when not.
e.g. instead of
```javascript
// This check is technically done twice.
if (this.logger.isLevelEnabled('debug')) {
this.logger.debug(this.generateAsciiArtFromJpeg());
}
```
the customer could use:
```javascript
this.logger.debug(() => this.generateAsciiArtFromJpeg());
```

perf(common): In case of an expensive log, allow to pass a function

---

packages/core/injector/module.ts
packages/core/test/injector/module.spec.ts

```ts
import { Module } from '@nestjs/common';
@Module({
providers: [
{ provide: 'foo', useValue: undefined  },
{ provide: 'bar', useFactory: () => undefined  },
],
exports: [
// This triggers the 'cannot export a provider ...' error
'foo',
// This won't
'bar',
]
})
export class AppModule {}
```
when exporting some custom value provider that was registered with the value `undefined` we got the following error
We could now have mandatory custom provider values with the value `undefined`. Although this unlikely make sense, it's aligned with the present behavior of factory providers that could return `undefined`
I find this bug when trying to help one dev on our Discord. He was importing …

fix(core): false-positive value provider not registered error when the value is `undefined`

---

.gitignore
integration/graphql-schema-first/src/main.ts
packages/common/services/console-logger.service.ts
packages/common/services/logger.service.ts

ConsoleLogger.updateAndGetTimestampDiff can't be called in child class. 
ConsoleLogger.updateAndGetTimestampDiff can be called in child class. 
this PR is related to this discussion https://github.com/nestjs/nest/pull/11391

feat: change updateAndGetTimestampDiff from private to protected

---

sample/06-mongoose/src/cats/cats.service.ts

The current example uses `Model<CatDocument>` as a Mongoose model type. The result model type doesn't match the plain Mongoose model type. It wasn't a problem in v6. But the `Model` interface was changed in v7 and now `Model<>` doesn't accept `Document` types. It leads to some type mismatch problems if we use `Document` in generic.
For example, lean documents still have document properties and methods when they shouldn't.
```typescript
// Mongoose v6
type CatDocumentModel = Model<CatDocument>
// Model<Document<unknown, any, Cat> & Cat & { _id: Types.ObjectId }, {}, {}, {}, any>
type CatModel = Model<Cat>
// Model<Cat, {}, {}, {}, any>
// ref: …
```

sample(mongoose): change mongoose model type

---

packages/platform-express/adapters/express-adapter.ts
packages/platform-express/adapters/utils/get-body-parser-options.util.ts
packages/platform-express/interfaces/index.ts
packages/platform-express/interfaces/nest-express-application.interface.ts
packages/platform-express/interfaces/nest-express-body-parser-options.interface.ts
packages/platform-express/interfaces/nest-express-body-parser.interface.ts

Issue Number: #11302
We were depending on `@types/body-parser` in this new feature, as `body-parser` does not ship its own types. But this breaks when using `skipLibsCheck: false` in `tsconfig.json`.
I moved the `@types/body-parser` interface we use over to `@nestjs/platform-express`. We already have our own `NestExpressBodyParserOptions` which we can use to type ourselves. So this should not be a breaking change.

fix(express): remove body-parser types and ship these types our own

---

packages/microservices/decorators/event-pattern.decorator.ts
packages/microservices/decorators/message-pattern.decorator.ts
packages/microservices/test/decorators/event-pattern.decorator.spec.ts
packages/microservices/test/decorators/message-pattern.decorator.spec.ts

Ran into this challenge when creating a custom transport strategy. As far as I can tell there's no way to read additional metadata off of our handlers within the strategy itself; we just have access to the `extras` object.
However, the extras object can only be set when using the `@MessagePattern` or `@EventPattern` decorator reliably because they will always override any existing extras.
With this change the `@MessagePattern` and `@EventPattern` decorators will merge their extras with any existing extras found.
In our custom transport framework we have multiple decorators which work the same way as the `@HttpCode` decorator does for an HTTP transport by adding …

feat: allow extension of microservice event and message extras

---

packages/microservices/interfaces/microservice-configuration.interface.ts

Proposal:
- Updated the `ConsumerSubscribeTopic` interface with `ConsumerSubscribeTopics`, because `ConsumerSubscribeTopic` is deprecated.

chore(): update interface deprecated for kafka

---

packages/common/decorators/core/inject.decorator.ts
packages/common/decorators/core/optional.decorator.ts

Use PropertyDecorator and ParameterDecorator as return type to ensure typings are correct

fix(common): fix @Inject and @Optional return types

---

packages/microservices/client/client-kafka.ts
packages/microservices/client/client-proxy.ts

Falsy values passed to `ClientsModule` options would be overwritten by defaults.
Noticeably, the `postfixId` passesd to `ClientKafka`.
This happens because of faulty logic in the `getOptionsProp` method on `ClientProxy`. I have changed it to align with the behavior of the corresponding method in `Server`.
When passing empty string to `postfixId` to options of `ClientKafka`, the `-client` postfix no longer gets appended. This probably fixes a bunch of other defaults as well.
I have also uncommented the skipped Kafka integration tests, but they got stuck on the error below (after the annoying rebalancing errors) and I had to cancel them.
I did not investigate further, because I think …

fix(microservices): allow falsy values in options

---

packages/common/pipes/file/file-type.validator.ts
packages/common/pipes/file/file-validator.interface.ts
packages/common/pipes/file/interfaces/file.interface.ts
packages/common/pipes/file/interfaces/index.ts
packages/common/pipes/file/max-file-size.validator.ts
packages/common/test/pipes/file/file-type.validator.spec.ts
packages/common/test/pipes/file/max-file-size.validator.spec.ts
packages/common/test/pipes/file/parse-file-pipe.builder.spec.ts

feat(common): define type for file input

---

integration/hello-world/e2e/exceptions.spec.ts
packages/common/interfaces/nest-application.interface.ts
packages/platform-express/adapters/express-adapter.ts
packages/platform-express/interfaces/nest-express-application.interface.ts
packages/platform-fastify/interfaces/nest-fastify-application.interface.ts

feat(common,express,fastify): enhance the type of `httpServer`

---

packages/common/pipes/validation.pipe.ts
packages/common/test/pipes/validation.pipe.spec.ts

Issue Number: the issue #10246 is broader than what this PR address. For optional boolean values, when they are not supplied, the value is parsed to `false`
(using `ValidationPipe({ transform: true })`)
This only fixes(?) the following use case:
```
@Query('foo') foo?: boolean
```
```
@Param('foo') foo?: boolean
```
now leads to `foo === undefined` if no query/path parameter for `foo` key was supplied instead of always failing back to `false`. Note that marking them as optional doesn't matter
```
@Query('foo', new DefaultValue(false)): foo = false
```

fix(common)!: when transforming optional boolean parameters on `ValidationPipe`

---

packages/core/interceptors/interceptors-consumer.ts
packages/core/test/interceptors/interceptors-consumer.spec.ts

This is necessary to allow use cases such as allowing interceptors to
change the context in OpenTelemetry. You might for example want to add
Baggage to the context in an interceptor but because of the way it was
structured before the baggage would not make its way into the controller
Before this change the context would be lost before the controller was called because of the deferred nature of the next call.
This PR makes it possible to use `AsyncLocalStorage` from interceptors in such a way that the controller method will have access to the storage. 
Not sure if it's a breaking change. If anyone relies on the interceptor chain running asap, but the controller being …

feat: Support async local storage in interceptors

---

packages/common/interfaces/http/http-server.interface.ts
packages/platform-express/interfaces/nest-express-application.interface.ts
packages/platform-fastify/interfaces/nest-fastify-application.interface.ts

The return type of `HttpServer#getInstance` is always `any` even when we explicitly supply the adapter type (`NestExpressApplication`/`NestFastifyApplication`) to `NestFactory.create`
Depending on which HTTP adapter is being used, we have a type-strong return on `getInstance()`. Now one don't need to find out what's that returned object

feat(common)!: narrow `getInstance` return type for http adapters

---

packages/common/constants.ts

I'm not sure if we will drop the deprecated methods on `core/metadata-scanner.ts` in v10
https://github.com/nestjs/nest/blob/bee462e031f9562210c65b9eb8e8a20cab1f301f/packages/core/metadata-scanner.ts#L12-L16

refactor(common)!: drop deprecated misspelled constant `CUSTOM_ROUTE_AGRS_METADATA`

---

packages/core/router/router-explorer.ts

Using named groups of regex in host option works correctly
But, when I use the HostParam decorator there is nothing there
Returns an empty object
If I don't use named groups, just capture groups, it works, however, the indexing is numerical. HostParam works fine with Express dynamic routes (`host = ':accountId.localhost.com'`), but doesn't understand full regex usage.
Named groups are now read correctly.
Just added support for reading named groups as well.

feat(core): add support to named groups

---

packages/microservices/interfaces/microservice-configuration.interface.ts
packages/microservices/server/server-redis.ts
packages/microservices/test/server/server-redis.spec.ts

The redis microservice now makes use of `psubscribe` and `pmessage` if the `wildcards` option is enabled in the options of the microservice, which makes it possible to use wildcards as specified by the Redis documentation.
Closes #10344
The current setup uses `subscribe` and `message` when listening for patterns in a Redis microservice, while using `psubscribe` and `pmessage` would make it possible to use wildcards in those patterns as prescribed by the Redis documentation.
Issue Number: #10344 
The change makes it possible to use wildcards in the Redis microservice patterns by enabling the `wildcards` option of the microservice.

feat(microservices): enable wildcards in redis microservice patterns

---

.circleci/config.yml
packages/common/decorators/http/request-mapping.decorator.ts
packages/common/enums/request-method.enum.ts
packages/common/test/decorators/route-params.decorator.spec.ts
packages/core/adapters/http-adapter.ts

Issue Number: #10420
This PR adds the new Search method decorator to be a valid handler to routes. 
This change was rather simple, since both express and fastify already support this little akward and rather new http method

feat(core/common): Add @Search decorator to the available HTTP route handlers

---

package.json
packages/common/package.json
packages/core/package.json
packages/microservices/package.json
packages/platform-express/package.json
packages/platform-fastify/package.json
packages/platform-socket.io/package.json
packages/platform-ws/package.json
packages/testing/package.json
packages/websockets/package.json

https://docs.npmjs.com/cli/v9/configuring-npm/package-json#repository
> The URL should be a publicly available (perhaps read-only) url that can be handed directly to a VCS program without any modification. It should not be a url to an html project page that you put in your browser. It's for computers.
> If the package.json for your package is not in the root directory (for example if it is part of a monorepo) ...

chore: update repo references in package.json files

---

packages/common/pipes/parse-float.pipe.ts

Issue Number: closes #11602
instead of importing `Injectable` and `Optional` decorators from `packages/common/index.ts`, we now import them from `packages/common/decorators/core.ts` to avoid a circular import

refactor(common): import from decorators module instead of common's barrel file

---

package.json

In the `package.json` file the `@fastify/cors` dependency has a caret sign before it which is not true for all other dependencies. 
Hardcoded `@fastify/cors` dependency version to `8.2.1`. That is the current version in the lock file of the main branch anyway.

chore(deps): remove caret sign from @fastify/cors

---

packages/common/services/console-logger.service.ts
packages/common/services/logger.service.ts
packages/common/test/services/logger.service.spec.ts

The second parameter in `error` function must be a stack, but it logs context instead (if I pass 2 parameters to `error` function).
```
logger.error('message', 'stacktrace');
```
Log:
```
[Nest] 153  - 04/27/2023, 12:34:05 PM   ERROR [stacktrace] message
```
Log stack instead of context if passing 2 arguments to `error` function.

fix(common): `ConsoleLogger` doesn't log stacktrace

---

packages/microservices/module/clients.module.ts
packages/microservices/module/interfaces/clients-module.interface.ts

There is no way to import Clients module globally.
In my case, the client provider is used in guard, which in turn is used quite often, but not everywhere to use it at the application level.
Added the possibility of global import for Clients Module.
This method of adding a parameter is the most uncritical of all possible, although it departs a little from the established code style of options for modules.
The best way to solve the problem is to use a well-established code style of parameters
export interface ClientsModuleOptions {
providers: Array<ClientProviderOptions>;
/**
* If "true', register `ClientsModule` as a global module.
*/
isGlobal?: boolean;
}
this approach will be a …

feat(microservices): Add isGlobal option to the ClientsModule

---

packages/common/exceptions/http.exception.ts
packages/common/index.ts
packages/common/interfaces/http/index.ts

If the first argument is a non-empty string, previously compiler allowed providing it alone:
```ts
HttpException.createBody('some message'); // ✅
```
… which is incorrect, because that would make `.error` and `.statusCode` equal to `undefined` (no second and third arguments provided). This is fixed now: if `.createBody(…)` is called with a single argument, it is expected to be a full custom body:
```ts
HttpException.createBody('some message'); // ❌ Error: Argument of type 'string' is not assignable to parameter of type 'Record<string, unknown>'.
```
_(none)_

chore: improve typings of `.createBody(…)`

---

integration/typeorm/ormconfig.json
integration/typeorm/src/app.module.ts
integration/typeorm/src/async-class-options.module.ts
integration/typeorm/src/async-existing-options.module.ts
integration/typeorm/src/async-options.module.ts
integration/typeorm/src/database.module.ts

related #11648
This PR changes mysql connection host to '127.0.0.1'
Because nodejs prefers IPv6 addresses over IPv4 after 17 version.
I confirmed that this change solves typeorm test failure in integration test.
The following error occurred in node 18.14.0 version
```
28) TypeOrm (async configuration)
"before each" hook for "should return created entity":
Error: connect ECONNREFUSED ::1:3306
at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16)
at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
29) TypeOrm (async configuration)
"after each" hook for "should return created entity":
TypeError: Cannot read properties of undefined (reading …
```

fix(integration): change mysql connection host to 127.0.0.1

---

sample/05-sql-typeorm/src/app.module.ts
sample/05-sql-typeorm/test/users/users.e2e-spec.ts
sample/07-sequelize/src/app.module.ts

This PR changes mysql connection host to '127.0.0.1'
Because nodejs prefers IPv6 addresses over IPv4 after 17 version.
I am using the LTS version and I found that the sample code gives error.
here is my local test log
```
day1@MacBook-Pro  ~/Documents/git/nest/sample/05-sql-typeorm   master  node -v
v18.14.0
day1@MacBook-Pro  ~/Documents/git/nest/sample/05-sql-typeorm   master  npm start
> nest-typescript-starter@1.0.0 start
> nest start
[Nest] 43476  - 2023. 05. 22. 오후 6:58:30     LOG [NestFactory] Starting Nest application...
[Nest] 43476  - 2023. 05. 22. 오후 6:58:30     LOG [InstanceLoader] AppModule dependencies initialized +167ms
[Nest] 43476  - 2023. 05. …
```

fix(sample): change mysql connection host to 127.0.0.1

---

integration/hello-world/e2e/middleware-run-match-route.ts
packages/core/middleware/builder.ts

Currently, routes that has dynamic params can trigger a middleware multiple times for a single request if matches another static route inside the controller.
Issue Number: [#1628](https://github.com/nestjs/nest/issues/1628)
Routes will only trigger the middleware for the exact path match.

feat(core): middleware runs once for matching route

---

packages/common/services/utils/is-log-level-enabled.util.ts

Issue Number: https://github.com/nestjs/nest/issues/10878
- Updated the log level value
Note: PR for the next major version of NestJS 😻 (Not merge at the moment)

refactor(common): update log level

---

integration/websockets/e2e/gateway.spec.ts
integration/websockets/e2e/ws-gateway.spec.ts
integration/websockets/src/app.gateway.ts
integration/websockets/src/request.interceptor.ts
integration/websockets/src/server.gateway.ts
packages/common/interfaces/features/arguments-host.interface.ts
packages/core/helpers/execution-context-host.ts
packages/websockets/context/ws-context-creator.ts

The only way to get the websocket pattern is through reflection, which is unavailable inside of filters as the `ArgumentsHost` doesn't have a `getClass` or `getHandler` method. 
Issue Number: #10520
`ExecutionContext#switchToWs().getClient()` now has a `getPattern()` method attached to it so that the pattern can be retrieved in filters.
This pattern **is still a reflected pattern**, and not retrieved from the direct request, as we don't, to my knowledge, bind the exception filter for when invalid patterns are called (if I'm wrong about that please point to where it is)

feat: create method on client to get websocket pattern

---

packages/platform-express/multer/interceptors/index.ts
packages/platform-express/multer/interceptors/no-files.interceptor.ts
packages/platform-express/test/multer/interceptors/no-files.inteceptor.spec.ts

Adds an interceptor for multer's none option https://github.com/expressjs/multer#none. This allows for Nest.js users to process `multipart/form-data` that does not include any files.
I am implementing a feature that uses the [Sendgrid Inbound Parse API](https://docs.sendgrid.com/for-developers/parsing-email/setting-up-the-inbound-parse-webhook#raw-parameters). This sends the data encoded as `multipart/form-data` however the payload includes no files. I believe all data are sent as strings/text.
I reached for the Nest.js MulterModule but it currently does not support [multer's none option](https://github.com/expressjs/multer#none). `multer.none` parses only the text …

feat(express): add support for multer.none

---

integration/versioning/e2e/uri-versioning.spec.ts
integration/versioning/src/app.module.ts
integration/versioning/src/middleware.controller.ts
integration/versioning/src/multiple-middleware.controller.ts
integration/versioning/src/neutral-middleware.controller.ts
packages/core/middleware/middleware-module.ts
packages/core/middleware/routes-mapper.ts
packages/core/test/middleware/builder.spec.ts
packages/core/test/middleware/routes-mapper.spec.ts

fix(core): apply middleware to versioned controllers (ctrl-level)

---

packages/microservices/client/client-kafka.ts
packages/microservices/server/server-kafka.ts
packages/microservices/test/client/client-kafka.spec.ts
packages/microservices/test/server/server-kafka.spec.ts

currently, Kafka is subscribing to topics one by one, which is deprecated
https://github.com/nestjs/nest/blob/8399c68b20cd76d766cd25790f662ef211e810ff/packages/microservices/external/kafka.interface.ts#L1034-L1045
Use the correct way to subscribe to topics using a single call as described in [their docs](https://kafka.js.org/docs/consuming)

fix(microservices): migrate from deprecated kafka subscribe usage

---

packages/core/middleware/builder.ts

Issue Number: closes #11833
dot not exclude routes ending with slash
but I'm not 100% sure on this fix although it works for the mentioned Issue (I tested it locally)
@rychardvale could you please review this?

fix(core): when filtering routes ending with slash to apply a nestjs middleware

---

sample/31-graphql-federation-code-first/gateway/package-lock.json
sample/31-graphql-federation-code-first/gateway/package.json
sample/31-graphql-federation-code-first/posts-application/package-lock.json
sample/31-graphql-federation-code-first/posts-application/package.json
sample/31-graphql-federation-code-first/users-application/package-lock.json
sample/31-graphql-federation-code-first/users-application/package.json

Issue Number:
https://github.com/nestjs/nest/issues/11799
https://github.com/nestjs/nest/issues/11942
Proposal:
- Downgrade @apollo/subgraph and @apollo/gateway to version `2.2.3` in example: `31-graphql-federation-code-first`. ( see here: https://github.com/apollographql/federation/issues/2375) 
Using version `2.2.3` of the following packages:
- `@apollo/gateway`
- `@apollo/subgraph`
in the code first mode the following error is not generated:
```
sample/31-graphql-federation-code-first/users-application/node_modules/@apollo/federation-internals/src/error.ts:66 super( ^ GraphQLError: The schema is not a valid GraphQL schema.. Caused by: Invalid definition for directive "@tag": "@tag" …
```

sample(31-graphql-federation-code-first): downgraded the @apollo/subgraph and @apollo/gateway versions 

---

packages/core/nest-application.ts
packages/core/test/nest-application.spec.ts

Fixes #12006
Issue Number: #12006

fix(core): Initialize application only once

---

sample/02-gateways/e2e/events-gateway/gateway.e2e-spec.ts

`socket.connect()` was not needed as `io()` already auto connects. Also wait for socket to be connected.

Update socket.io example: Wait for socket to be connected

---

packages/common/pipes/file/file-type.validator.ts
packages/common/pipes/file/file-validator.interface.ts
packages/common/pipes/file/max-file-size.validator.ts

Issue Number: closes #12019
the only way to proper narrowing the type of the first arg of `FileValidator#isValid` method AFIAK is via generic type arg instead of the method-based one which was introduced in PR #11040

fix(common): right generic type arg constraint for `FileValidator#isValid` method

---

packages/platform-fastify/interfaces/external/fastify-static-options.interface.ts

since version 6.10.0, fastify-static added an option to specify route constraints. I've just updated the interface in platform-fastify package to reflect the latest type in fastify-static package.
[fastify-static v6.10.0 changelog](https://github.com/fastify/fastify-static/releases/tag/v6.10.0)

refactor(fastify): updated static options

---

packages/microservices/client/client-grpc.ts
packages/microservices/test/client/client-grpc.spec.ts

Unsubscribe unary request with client upstream do nothing:
- Not cancel grpc call
- Request keep connection
Issue Number: #12023
When unsubscribe unary request with client upstream:
- Check grpc call is finished or not
- If not, call `call.cancel()` to cancel request & release resource

fix(microservices): support client cancel grpc request in unary stream

---

integration/injector/e2e/circular-custom-providers.spec.ts
packages/core/errors/exceptions/circular-dependency.exception.ts
packages/core/injector/injector.ts
packages/core/injector/instance-wrapper.ts
packages/core/injector/settlement-signal.ts

fix(core): throw on circular factories and custom providers

---

integration/lazy-modules/e2e/lazy-import-global-modules.spec.ts
integration/lazy-modules/src/app.module.ts
integration/lazy-modules/src/eager.module.ts
integration/lazy-modules/src/global.module.ts
integration/lazy-modules/src/lazy.module.ts
integration/lazy-modules/src/main.ts
packages/core/injector/container.ts
packages/core/injector/lazy-module-loader/lazy-module-loader.ts
packages/core/scanner.ts
packages/core/test/injector/injector.spec.ts
packages/core/test/inspector/graph-inspector.spec.ts
packages/core/test/nest-application-context.spec.ts
packages/core/test/repl/native-functions/debug-repl-fn.spec.ts
packages/core/test/repl/native-functions/methods-repl-fn.spec.ts

Fork of https://github.com/nestjs/nest/pull/10005

fix(core): allow importing providers from global modules in lazy modules

---

packages/platform-express/interfaces/nest-express-application.interface.ts
packages/platform-fastify/interfaces/nest-fastify-application.interface.ts

the return type of `#listen` when defining the type arg for `NestFactory.create` isn't correct. See:
- express
> ![image](https://github.com/nestjs/nest/assets/13461315/c182d0dd-7133-4e84-ba83-da9851bf60ea)
- fastify
> ![image](https://github.com/nestjs/nest/assets/13461315/c033fde0-9b1a-4c47-b73d-c90247b1b4c7)

fix(express,fastify): return type of `#listen` method

---

packages/core/nest-factory.ts

Issue Number: #12165 #9017
NestContainer init w/o application config.
`NestFactory.initialize` take default value for application config. For that reason we got application config undefined and no global enhancers.
After bootstrap application allow to create fns via ExternalContextCreator with global enhancers. For that we need to pass ApplicationConfig to container.

fix(core): pass application config to nest container when using application context

---

packages/core/injector/settlement-signal.ts

Currently, even correct circular dependencies _can_ cause exceptions for seemingly no reason.
Issue Number: #12153
With this new `completed` field, all properly managed circular dependencies work as anticipated.

fix(core): create completed field on settlement for better tracking

---

packages/core/router/router-explorer.ts
packages/core/test/router/router-explorer.spec.ts
packages/platform-fastify/adapters/fastify-adapter.ts
packages/platform-fastify/constants.ts
packages/platform-fastify/decorators/index.ts
packages/platform-fastify/decorators/route-config.decorator.ts
packages/platform-fastify/index.ts
packages/platform-fastify/test/decorators/router-config.decorator.spec.ts

Resolves #11815
Issue Number: #11815
Users can use the `@RouteConfig()` decorator to specify a value for the route config for fastify endpoints

feat(fastify): supporting fastify route config

---

packages/common/pipes/file/file-validator.interface.ts

fix(common): fix custom multi file validator

---

packages/common/services/console-logger.service.ts
packages/common/services/logger.service.ts
packages/common/services/utils/is-log-level-enabled.util.ts
packages/core/injector/helpers/silent-logger.ts

Issue Number: #11945
This PR introduces a new 'fatal' log level in the NestJS default logger classes (Logger, ConsoleLogger, LoggerService, etc). This level helps differentiate critical application errors from other issues, making it easier to prioritize and address high-priority problems. The addition is backward compatible, requiring no migration, and offers a simple way to improve error identification for developers. The documentation update includes the new method signature in the LoggerService code snippet.

feat(common): added "fatal" as a log level (issue #11945)

---

packages/core/services/reflector.service.ts
packages/core/test/services/reflector.service.spec.ts
sample/01-cats-app/src/cats/cats.controller.ts
sample/01-cats-app/src/common/decorators/roles.decorator.ts
sample/01-cats-app/src/common/guards/roles.guard.ts

feat(core): add strongly-typed decorators factory (reflector)

---

packages/microservices/server/server-redis.ts

Currently the following code
```ts
app.connectMicroservice<RedisOptions>({
transport: Transport.REDIS,
});
```
will throw the following error
```
/.../server/node_modules/@nestjs/microservices/server/server-redis.js:42
subClient.on(this.options.wildcards ? 'pmessage' : constants_1.MESSAGE_EVENT, this.getMessageHandler(pubClient).bind(this));
^
TypeError: Cannot read properties of undefined (reading 'wildcards')
at ServerRedis.bindEvents (/.../server/node_modules/@nestjs/microservices/server/server-redis.js:42:35)
at /.../server/node_modules/@nestjs/microservices/server/server-redis.js:35:18
at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
I chose to fix the bind function where the `options` were referenced, however if we …

Guard undefined Redis options

---

packages/core/services/reflector.service.ts
packages/core/test/services/reflector.service.spec.ts

Currently, the return type of `Reflector.get(ReflectableDecorator)` resolves incorrectly if the `transform` option is used with the `Reflector.createDecorator` call and the transformed value has a different type than the input.
Issue Number: https://github.com/nestjs/nest/issues/12264
Add a second optional generic param on Reflector.createDecorator to describe the transformed value type as following:
```typescript
const Roles = Reflector.createDecorator<string[], number>({
key: 'roles',
transform: (roles: string[]): string[] => roles.length, // Must return type number
});
const roles = this.reflector.get(Roles, context.getHandler()) // Will resolve as type number
```

feat(core): add generic type for transformed value in decorators factory

---

packages/microservices/server/server-grpc.ts
packages/microservices/test/server/server-grpc.spec.ts

When error is thrown in Streamed GRPC controller, the application crashed
Issue Number: https://github.com/nestjs/nest/issues/12187
Any errors thrown inside GrpcStreamMethod should be handle correctly without crashing the app.

fix(microservices): handle error thrown in the stream gRPC controller

---

packages/microservices/server/server-grpc.ts
packages/microservices/test/server/server-grpc.spec.ts

Adds code to handle back pressure when writing output from Observable streams.
Docs are n/a.
Currently, when writing out observables to the GRPC Call writable stream, it's not waiting for the stream writer to be drained before writing the next bit of data. This means the service doesn't get a breather between each part.
The consumer of the observable will wait for the stream to drain before trying to write the next bit.

fix: appropriately handle backpressure

---

packages/platform-ws/adapters/ws-adapter.ts

function call was missing the second argument
Currently, when using `platform-ws` and calling `host.switchToWs().getPattern()` on `ArgumentsHost` given in exception filter, we don't get a pattern but we get a `data` object. For example for following message on the websocket:
```
{
event: 'foo',
data: {  test: 1  }
}
```
we would get `{  test: 1  }` as a "pattern"
When using `platform-ws` and calling `host.switchToWs().getPattern()` on `ArgumentsHost` given in exception filter we get correct pattern matched for this branch. For the following message on the websocket:
```
{
event: 'foo',
data: {  test: 1  }
}
```
we correctly get `'foo'` as a pattern
If I traced the …

fix(ws): fix incorrect host pattern on messages

---

packages/core/injector/module-ref.ts
packages/core/injector/module.ts

Custom classes can only be static, because they are not associated with a contextId, and thus cannot find an associated request.
Allows us to construct request-scoped custom classes by passing a `contextId` to `moduleRef.create`
This feature is really small and the moduleRef is not directly covered. Shall I add tests and/or docs?

feat(core): instantiate non-static custom classes

---

packages/microservices/server/server-mqtt.ts

- [ x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [ x] Tests for the changes have been added (for bug fixes / features)
- [x ] Bugfix
The current behavior of the `getHandlerByPattern` method in the `ServerMqtt` class is to exclude patterns that do not contain wildcards when looking for message handlers. This means that binding to shared topics without wildcards is not supported.
Issue Number: [#12367](https://github.com/nestjs/nest/issues/12367)
The new behavior allows binding to shared topics without wildcards in the `getHandlerByPattern` method.
- [x ] No

Allow Binding to Shared Topics Without Wildcards

---

integration/websockets/e2e/gateway.spec.ts
integration/websockets/src/app.gateway.ts
integration/websockets/src/request.filter.ts
packages/websockets/context/ws-context-creator.ts
packages/websockets/context/ws-proxy.ts

Currently, websocket exception filters are not aware of the value from `getPattern()` due to the way the args get passed around between the [`WsContextCreator`](https://github.com/nestjs/nest/blob/67951ff2e9b7f4803856ab8169e23350e49d7dfc/packages/websockets/context/ws-context-creator.ts#L112) and the [`WsProxy`](https://github.com/nestjs/nest/blob/67951ff2e9b7f4803856ab8169e23350e49d7dfc/packages/websockets/context/ws-proxy.ts#L11) classes.
Issue Number: #12380
By adding a new parameter to the `WsProxy#create` method, we're able to pass the found `targetPattern` from the `WsContextCreator` to the `WsProxy` class so that it can be properly passed on the the `handleError` method and …

fix: allow for filters to be aware of the pattern for websockets

---

packages/platform-ws/adapters/ws-adapter.ts

Invalid URL TypeError handled with a try-catch block
fixes #12381
Issue Number: #12381 
In case of invalid URL socket is closed with an error message.

fix(platform-ws): URL parsing error handled

---

packages/common/services/console-logger.service.ts
packages/common/test/services/logger.service.spec.ts
packages/core/injector/module.ts
packages/core/middleware/routes-mapper.ts
packages/microservices/server/server-mqtt.ts

this a fix for the regression introduced by PR #11281
For example:
```ts
import { Logger } from '@nestjs/common'
class Foo {}
function foo() {
return 'foobar'
}
const logger = new Logger()
logger.log(foo)
logger.log(Foo)
logger.log(class {})
```
You'll see:
```
/tmp/nestjs-app/node_modules/@nestjs/common/services/console-logger.service.js:150
? this.stringifyMessage(message(), logLevel)
^
TypeError: Class constructor Foo cannot be invoked without 'new'
at ConsoleLogger.stringifyMessage (/tmp/nestjs-app/node_modules/@nestjs/common/services/console-logger.service.js:150:37)
at ConsoleLogger.formatMessage (/tmp/nestjs-app/node_modules/@nestjs/common/services/console-logger.service.js:142:2 …
```

fix(common): when passing class functions to logger methods

---

integration/injector/e2e/optional-factory-provider-dep.spec.ts
packages/core/errors/messages.ts
packages/core/test/errors/test/messages.spec.ts

when some provider registered with a string token is missing, the error message is the same as the ones registered with classes
I believe this confuse people sometimes specially when the token is created by 3rd-party libs and, on the consumer side, there is a class with the same name
For example:
I believe that this minor change would decrease the debugging time spent of resolving such errors. But I don't know if not having quotes around provider's name was intentional in first place.

feat(core): disambiguate string-based providers from class-based providers on error message

---

integration/discovery/e2e/discover-by-meta.spec.ts
integration/discovery/src/decorators/non-applied.decorator.ts
packages/core/discovery/discoverable-meta-host-collection.ts

Issue Number: closes #12518 
returns an empty Set - a null object, kinda (although I dislike the ideia of initializing a new empty object every time)

fix(core): when the discoverable decorator was not used on calling `getProviders`/`getControllers`

---

packages/common/file-stream/streamable-file.ts
packages/platform-express/adapters/express-adapter.ts

When the StreamableFile handle has an error, it uses the built in `this.logger.error()` handler to log the error. This works, but can cause a lot of noise with the stack trace that gets printed.
Issue Number: #12542
Devs are now able to do `new StreamableFile().setErrorLogger((err) => this.logger.error(err.message))` to only log the message and not the stack trace, or whatever other custom logging they want to use

feat: allow for custom logger with streamable files

---

packages/common/pipes/validation.pipe.ts

If a parameter decorator with the metatype `Date` is used, with the `ValidationPipe` with at least one validation option, then the parameter will be transformed into a date object, even if `transform: false` is set. 
Issue Number: #12647 
`Date` specific parameters are now ignored, just as `Array`, `Object`, `String`, and `Number` are, for consistency
_Technically_ yes, but it's fixing what is a bug.

fix: add date to ignored metatypes

---

packages/microservices/interfaces/microservice-configuration.interface.ts
packages/microservices/server/server-rmq.ts

Currently Rmq microservice config params does not accept consumerTag parameter.  
Microservice options should now accept consumerTag param while configuring the rabbitmq microservice app.

Add consumerTag param on rmq microservice config

---

packages/core/injector/module-token-factory.ts

The serialization can be slow and the user will never know about it.
Issue Number: #12738
Fixes #12738
Now we emit a warning using `process.emitWarning` when the serialization took more than `10ms`.
This is an arbitrary value, we can raise or lower this value depending on the real-world applications.

feat(core): emit warning when serialization of module is slow

---

packages/core/router/interfaces/routes.interface.ts
packages/core/router/router-module.ts
packages/core/test/router/utils/flat-routes.spec.ts

change type of RouteTree.children to accept both RouteTree and Type<any> in junction
fixes #12700
Issue Number: #12700 
Instead of only allowing either an array of `RouteTree` OR `Type<any>`, both can now be used in junction to reduce code for simple nested routes
SImple Type Change, no further changes required

feat(core): allow using modules and nested route trees in parallel

---

packages/microservices/server/server-grpc.ts

At the current moment if you throw error in stream, It will throw all app, but with this fix error will be handled, and server will not fall dawn

FIX catch stream errors in grpc

---

.github/ISSUE_TEMPLATE/Bug_report.yml

A minor change to the bug report issue template form to better align with contributions expectations. I'm using [this](https://antfu.me/posts/why-reproductions-are-required) great article to clarify why we need a reproduction. This is my attempt to decrease the amount of bugs report without reproductions when they clearly need one

chore: add notice about closing unreproducible issues to bug report issue template

---

packages/common/interfaces/external/cors-options.interface.ts

Issue Number: closes #12816 
we can now supply `null` to the callback as the [`cors` docs](https://www.npmjs.com/package/cors) suggests
A better definition would be:
```ts
export interface CorsOptionsCallback {
(error: Error): void;
(error: null, options: CorsOptions): void;
}
```
but I believe this would introduce a breaking change

fix(common): type def for cors delegated callback function option

---

packages/common/decorators/core/controller.decorator.ts
packages/core/errors/exceptions/unknown-module.exception.ts
packages/core/nest-application-context.ts
packages/core/nest-factory.ts
packages/core/router/router-response-controller.ts
packages/microservices/server/server-rmq.ts
packages/platform-socket.io/adapters/io-adapter.ts

when calling `app.select()` over modules that weren't registered, we will see the following error message:
now we'll see module's name:
It works for dynamic modules as well
The code used in my tests:
This will help us to find which `.select` is broken
I also ran `npm run format` (commit [aad263a](https://github.com/nestjs/nest/pull/12905/commits/aad263a92cd1cac78123cfa892c19147eb74f21c))

feat(core): display module's name on `.select(module)` errors

---

packages/core/repl/repl.ts

The `nestjs/core/repl` function that runs `node:repl` does not allow the consumers to provide `node:repl`'s option (`ReplOptions`).
Issue Number: https://github.com/nestjs/nest/issues/12916
This PR allows passing `ReplOptions` to the `nestjs/core/repl` function. Current implemented behavior will also override default options `prompt` / `ignoreUndefined` if they are provided. If required, I can change the PR to not override this default options.
- I don't know if a test for this is required or not (we are just adding a new paramter whose type is defined within node typings itself). If a test is expected for this, it would be nice to have an hint of exactly "what" to test for to avoid …

feat(core): add options parameter to repl

---

packages/microservices/external/rmq-url.interface.ts
packages/microservices/interfaces/microservice-configuration.interface.ts

remove the comments from the types of the rmq options interface to get types and modify the types
previous behavior: queueOptions and socketOptions fields type is any
- [ v ] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [ v ] Refactoring (no functional changes, no api changes)
any type for socketOptions and queueOptions fields in RMQ microservice options
get autocomplete for socketOptions  and queueOptions fields in RMQ microservice options because of the types
- [ x ] No

refactor(microservices): modify rmq options interface

---

integration/inspector/e2e/fixtures/post-init-graph.json
integration/inspector/e2e/fixtures/pre-init-graph.json
package.json
packages/common/module-utils/configurable-module.builder.ts
packages/core/injector/internal-core-module/internal-core-module-factory.ts
packages/core/router/router-module.ts
packages/core/test/router/router-module.spec.ts
packages/microservices/module/clients.module.ts
packages/microservices/test/module/clients.module.spec.ts
packages/platform-express/multer/multer.module.ts
packages/platform-express/test/multer/multer/multer.module.spec.ts

Because of the nature of the `ModuleTokenFactory`, heavy objects will slow down the initialization, especially when using `.proto` files.
Issue Number: #12719
Closes #12719
Now, we defer the initialization of the `.proto` files by using `useFactory`, this will fix any initialization issue.
> The second run is with the fix.
I also updated almost all the references for `useValue`, so this can help avoid the same issue in other places.

perf: prefer use factory instead of use value when possible

---

packages/microservices/decorators/message-pattern.decorator.ts
packages/microservices/errors/invalid-grpc-message-decorator.exception.ts

`TypeError: Cannot read properties of undefined (reading 'value')`
`InvalidGrpcDecoratorException[Error]: The invalid gRPC decorator (method "methodName" in service "serviceName")`

feat(microservices): Added invalid-grpc-message-decorator.exception.ts

---

packages/microservices/client/client-grpc.ts
packages/microservices/errors/invalid-grpc-package-definition-missing-package-definition.exception.ts
packages/microservices/errors/invalid-grpc-package-definition-mutex.exception.ts
packages/microservices/helpers/grpc-helpers.ts
packages/microservices/helpers/index.ts
packages/microservices/interfaces/microservice-configuration.interface.ts
packages/microservices/server/server-grpc.ts
packages/microservices/test/client/client-grpc.spec.ts
packages/microservices/test/helpers/grpc-helpers.spec.ts
packages/microservices/test/server/server-grpc.spec.ts

PR #8465 added support for packageDefinition for `ClientGrpc`, this PR adds it to `ServerGrpc`.
- Export common `packageDefinition` logic to `getGrpcPackageDefinition` and used it in both gRPC Server & Client, for consistency
- This change means that `GrpcOptions['options']['protoPath']` is now optional - `getGrpcPackageDefinition` verifies that either `protoPath` or `PackageDefinition` exist
- Also, changed the error thrown from `ServerGrpc.loadProto`: it was Error, now `InvalidProtoDefinitionException`, as it is in `ClientGrpc`
- Add a `loadProto` test for `ServerGrpc`, similar to the one that exists for `ClientGrpc`
Currently, it's impossible to create a gRPC microservice by …

feat(microservices): add package definition option to server-grpc

---

packages/common/interfaces/external/https-options.interface.ts

feat(common): support `secureOptions` on https options

---

packages/common/decorators/core/inject.decorator.ts
packages/common/test/decorators/inject.decorator.spec.ts

Issue Number: #12914 
In response to issue #12914, this commit enhances the Nest.js injector for better debugging efficiency. The improvement involves throwing a specific error when a token is undefined, aiding developers in quicker problem identification and resolution. The error message provides guidance on potential circular dependencies and references for further assistance.

perf(common): Improve error handling for undefined tokens

---

packages/common/decorators/http/header.decorator.ts
packages/core/router/router-response-controller.ts

chore(core): allow dynamic value for header value

---

packages/microservices/client/client-grpc.ts
packages/microservices/test/client/client-grpc.spec.ts

Currently, using GRPC client created through `ClientProxyFactory`, it's not possible to close once initiated connection.
```ts
const client = ClientProxyFactory.create({
transport: Transport.GRPC
});
const service = client.getService('ServiceName')
await firstValueFrom(service.callSomething())
// do nothing with connection
client.close()
// workaround to close connection properly
client.getClientByServiceName<Client>('ServiceName').close();
```
That looks like a bug, as `close()` method of `ClientGrpcProxy` class trying to call corresponding method not from `Client` instance, created by `@grpc/grpc-js`, but from parsed proto package definition, loaded by `@grpc/proto-loader`:
```ts
// …
```

fix(microservices): grpc client closing

---

packages/platform-fastify/package.json

This change allows updating @fastify/static to v7.
when updating @fastify/static you might get the error "Conflicting peer dependency".
allows updating @fastify/static

fix: allow @fastify/static v7

---

packages/microservices/client/client-nats.ts

Pretty simple fix to correctly prepend the `inboxPrefix` to the NATS inbox ID
https://github.com/nestjs/nest/issues/13150
Issue Number: 13150
The inbox prefix being added to the inbox ID

fix(packages/microservices): pass inboxPrefix as argument to createInbox

---

packages/microservices/client/client-rmq.ts
packages/microservices/external/rmq-url.interface.ts
packages/microservices/server/server-rmq.ts

change socketOptions.connectionOptions type from any to amqp-manager's AmqpConnectionOptions which allows to specify not only mTLS but also External auth
Closes https://github.com/nestjs/nest/issues/13071
Currently in RabbitMq client options `socketOptions.connectionOptions` type is `any`
Issue Number: https://github.com/nestjs/nest/issues/13071
- RabbitMq client options `socketOptions.connectionOptions` type is now `AmqpConnectionOptions`
- In `server-rmq.ts` and `client-rmq.ts` local variable `rqmPackage` has been renamed to `rmqPackage`

feat(microservices): add type for rmq connection options

---

packages/microservices/external/kafka.interface.ts

Incompatible typing between the KafkaJs and Nest Kafka Microservice types.
Issue Number: #13077 
This will change the SASL Mechanism to be compatible types.
While technically this is a breaking change, since we Object.assign, the current signature actually won't work: https://github.com/edeesis/nest/blob/master/packages/microservices/server/server-kafka.ts#L114-L118.
The signature change was introduced in kafkajs 2.2.1.

fix: #13077 KafkaJs typing consistency

---

packages/common/interfaces/http/http-server.interface.ts
packages/core/adapters/http-adapter.ts
packages/core/helpers/router-method-factory.ts

> compile time error will be generated if missed
> added jsdocs
see issue
Issue Number: https://github.com/nestjs/nest/issues/12998
see issue

fix(core,common): 🐛 missing registration handling of `SEARCH` http verb

---

packages/microservices/constants.ts
packages/microservices/server/server-rmq.ts
packages/microservices/test/server/server-rmq.spec.ts

Same problem as descibed in [issue 11641](https://github.com/nestjs/nest/issues/11641) but for messages (not events).
With RMQ Options:
* prefetchCount: 1
* noAck: false
When you send a message (using `client.send()`) with an unknown pattern, the server does not send an acknowledgment. The message remains unacknowledged. Application reaches prefetch count and freezes.
Minimum reproduction code - https://github.com/toxol/nest-rmq-nack
When RMQ server receives a message for which there is no handler, it will send a negative acknowledgment without retrying.

fix(microservices): send rmq nack without matching message handler

---

packages/core/adapters/http-adapter.ts
packages/core/test/utils/noop-adapter.spec.ts
packages/platform-express/adapters/express-adapter.ts
packages/platform-fastify/adapters/fastify-adapter.ts

The setHeader method would replace a header, while there can be multiple headers with the same name
Talking about cookie headers, you can have more than one header with the same key (two Set-Cookie headers). With the existing setHeader method, a header in Express could not be appended with the same key, just in Fastify platform, because Fastify handles this problem, unlikely Express.
I ended up adding a getHeader() and an appendHeader() method. The appendHeader() Express implementation calls `response.append(name, value)`, and the Fastify implementation calls `response.header(name, value). Now, you can have more than one Set-Cookie header in Express.

feat: Implement getHeader and appendHeader methods in adapters

---

.husky/commit-msg
.husky/pre-commit
package.json

The version of husky in the repository is +9.0.1 but the files have not been migrated
The files have been migrated and the `prepare` script has been updated
https://github.com/typicode/husky/releases/tag/v9.0.1

chore(deps): migrate husky from v8 to v9

---

packages/common/exceptions/http.exception.ts

HttpException cannot be instantiated with zero arguments. The provided first example is misleading.
There is a misleading example of the usage of HttpException's constructor. It cannot be instantiated with zero arguments.
Removed incorrect example.

docs(common): remove incorrect constructor signature of HttpException

---

packages/microservices/server/server-grpc.ts

From https://github.com/nestjs/nest/pull/13195
```
call.emit('error', err);
subscription.unsubscribe();
reject(err);
```
The bug was fixed by adding `call.emit('error', err)` before `subscription.unsubscribe()`.
```
try {
await this.writeObservableToGrpc(result$, call);
} catch (err) {
call.emit('error', err);
return;
}
```
The `call.emit('error', err);` of the `catch` statement by `reject()` is a code that does not work because it follows `subscription.unsubscribe();`.
If you only look at the `try catch` statement without looking inside the `writeObservableToGrpc()` function, `call.emit('error', err);` is a misleading code and should be deleted.

fix(microservices): fix redundant code to emit error

---

packages/common/services/console-logger.service.ts
packages/common/test/services/logger.service.spec.ts

```typescript
const logger = new Logger();
const err = new Error("err");
logger.error(err.message, err.stack);
```
output:
```
[Nest] 54113  - 03/13/2024, 11:06:24 PM   ERROR [Error: err!
at bootstrap (/path/to/src/main.ts:30:15)] err!
```
```
[Nest] 54113  - 03/13/2024, 11:06:24 PM   ERROR err!
Error: err!
at bootstrap (/path/to/src/main.ts:30:15)
```

fix(common): fix stacktrace regex

---

packages/microservices/client/client-rmq.ts
packages/microservices/server/server-rmq.ts
packages/microservices/test/client/client-rmq.spec.ts
packages/microservices/test/server/server-rmq.spec.ts

The `noAssert` flag is a state property on the `ServerRMQ` and `ClientRMQ` classes but it's not being used.
Instead, the `queueOptions.noAssert` is used to determine if the `assertQueue` should be called or not (can be seen [here for server](https://github.com/nestjs/nest/blob/7f00840c074ba5a5f233f73ef6c8456115abd7c1/packages/microservices/server/server-rmq.ts#L148) and [here for client](https://github.com/nestjs/nest/blob/7f00840c074ba5a5f233f73ef6c8456115abd7c1/packages/microservices/client/client-rmq.ts#L190))
This means that the `noAssert` flag is not used, at all.
This PR  makes sure to use the `noAssert` property of the class, instead of reading it from the `queueOptions`
The …

fix(microservices): fix rabbitmq no-assert not being applied correctly

---

packages/microservices/server/server-grpc.ts
packages/microservices/test/server/server-grpc.spec.ts

> (node:66623) DeprecationWarning: Calling start() is no longer necessary. It can be safely omitted.
    at ServerGrpc.start (\<PATH\>/node_modules/@nestjs/microservices/server/server-grpc.js:39:25)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ServerGrpc.listen (\<PATH\>/node_modules/@nestjs/microservices/server/server-grpc.js:31:13)
The above warning message appeared, so even if I deleted `this.grpcClient.start();` and ran it, it worked normally.

fix(microservice) Delete unnecessary call of grpcClient.start

---

packages/common/decorators/http/route-params.decorator.ts
packages/common/enums/route-paramtypes.enum.ts
packages/core/router/route-params-factory.ts
packages/core/router/router-execution-context.ts
packages/core/test/router/route-params-factory.spec.ts
packages/core/test/router/router-execution-context.spec.ts

Issue Number: #13224 
Adds `@RawBody()` decorator

feat(core,common): Add `@RawBody()` decorator

---

packages/microservices/interfaces/microservice-configuration.interface.ts
packages/microservices/package.json
packages/microservices/server/server-grpc.ts
sample/04-grpc/package-lock.json
sample/04-grpc/package.json
sample/04-grpc/src/grpc-client.options.ts

Automatically add support for the gRPC reflection API if the user has the `@grpc/reflection` package installed
I currently maintain a Nest Module package (`nestjs-grpc-reflection`) which adds this capability to a user's app, but opening this PR as a discussion point for whether this makes sense to add to NestJS directly!
The [gRPC server reflection API](https://github.com/grpc/grpc/blob/master/doc/server-reflection.md) exposes information about a gRPC package so that clients can introspect it, this is gaining in popularity in developer tooling such as Postman, grpcui, ezy and so on as it removes the need for developers to manually manage proto file definitions and can …

feat(microservices): add support for grpc reflection api

---

integration/nest-application/global-prefix/e2e/global-prefix.spec.ts
integration/nest-application/global-prefix/src/app.controller.ts
packages/core/middleware/middleware-module.ts
packages/core/middleware/route-info-path-extractor.ts
packages/core/middleware/routes-mapper.ts
packages/core/test/middleware/builder.spec.ts
packages/core/test/middleware/route-info-path-extractor.spec.ts
packages/platform-fastify/adapters/fastify-adapter.ts

Issue Number: https://github.com/nestjs/nest/issues/11572
Based off https://github.com/nestjs/nest/pull/12179

fix(core): middleware is not executed for root route when global prefix is set

---

packages/common/decorators/core/set-metadata.decorator.ts

Documentation
The current behavior is that the link in the SetMetadata decorator documentation is broken and redirects to the wrong page.
The new behavior is that the broken link in the SetMetadata decorator documentation has been fixed to accurately direct users to the Reflection section within the Execution Context page of the NestJS fundamentals documentation.

fix: update broken link in SetMetadata decorator documentation

---

packages/core/helpers/context-utils.ts

Reference caused in getContextFactory, and it stored in handlerMetadataStorage in Map, that never be purged
[issue](https://github.com/nestjs/nest/issues/13365)
Issue Number: 13365
same, but without leak

fix(core): break reference chain to instance object

---

packages/common/decorators/core/inject.decorator.ts
packages/common/test/decorators/inject.decorator.spec.ts

Revert "perf(common): Improve error handling for undefined tokens"

---

packages/common/interfaces/middleware/middleware-config-proxy.interface.ts

This PR fixes some typos & clarifies some comments.

doc: fix typos & clarify comments

---

packages/microservices/ctx-host/base-rpc.context.ts
packages/microservices/ctx-host/kafka.context.ts
packages/microservices/ctx-host/mqtt.context.ts
packages/microservices/ctx-host/nats.context.ts
packages/microservices/ctx-host/redis.context.ts
packages/microservices/ctx-host/rmq.context.ts
packages/microservices/ctx-host/tcp.context.ts
packages/microservices/record-builders/mqtt.record-builder.ts
packages/microservices/record-builders/nats.record-builder.ts
packages/microservices/record-builders/rmq.record-builder.ts
packages/microservices/server/server-grpc.ts
packages/microservices/server/server-kafka.ts
packages/microservices/server/server-mqtt.ts
packages/microservices/server/server-nats.ts
packages/microservices/server/server-redis.ts
packages/microservices/server/server-rmq.ts
packages/microservices/server/server-tcp.ts
packages/microservices/server/server.ts

Proposal:
- Added public api annotation (`@publicApi`) on `microservices`, in the following files:
- `packages/microservices/ctx-host/base-rpc.context.ts`
- `packages/microservices/ctx-host/kafka.context.ts`
- `packages/microservices/ctx-host/mqtt.context.ts`
- `packages/microservices/ctx-host/nats.context.ts`
- `packages/microservices/ctx-host/redis.context.ts`
- `packages/microservices/ctx-host/rmq.context.ts`
- `packages/microservices/ctx-host/tcp.context.ts`
- `packages/microservices/record-builders/mqtt.record-builder.ts`
- `packages/microservices/record-builders/nats.record-builder.ts`
- `packages/microservices/record-builders/rmq.record-builder.ts`
- …

chore: add public api annotation on microservices

---

sample/05-sql-typeorm/package.json

"@nestjs/typeorm": "10.0.1" is not compatible with "reflect-metadata": "0.2.1". We had to bump version to 0.2.2

fix(sample) NestJS TypeOrm compatibility with reflect-metadata 0.2.1

---

sample/11-swagger/package.json

In this sample next/swagger 7.2.0 is used as a dependency, but its no more compatible with the latest version so bumping to 7.3.0

fix(sample) NestJS compatibility with nest/swagger 7.2.0

---

integration/versioning/e2e/default-versioning.spec.ts
packages/platform-fastify/adapters/fastify-adapter.ts

feat(fastify): Do not crash if enableVersioning is not used

---

integration/hello-world/e2e/exclude-middleware.spec.ts
packages/core/middleware/builder.ts

Summary:
Previously, calling multiple `exclude` method in `MiddlewareConsumer` overwrote the previously excluded routes.
```typescript
configure(consumer: MiddlewareConsumer) {
consumer
.apply((req, res, next) => res.send(MIDDLEWARE_VALUE))
.exclude('test', 'overview/:id', 'wildcard/(.*)', {
path: 'middleware',
method: RequestMethod.POST,
}) // ignored
.exclude('multiple/exclude')
.forRoutes('*');
}
```
It only worked well when using a single `exclude` method.
```typescript
configure(consumer: MiddlewareConsumer) {
consumer
.apply((req, res, next) => res.send(MIDDLEWARE_VALUE))
.exclude('test', 'overview/:id', 'wildcard/(.*)', 'multiple/exclude', {
path: 'middleware', …
```

fix(core): prevent exclude method from overwriting previous calls

---

packages/common/decorators/core/inject.decorator.ts
packages/core/test/injector/injector.spec.ts

Issue Number: closes #13426
We can use `@Inject()` (ie., no token supplied) on constructor-based injections. It works just like property-based injection

feat(common): support empty `@Inject()` on constructor-based injection

---

packages/core/errors/exceptions-zone.ts
packages/core/nest-factory.ts
packages/core/test/errors/test/exceptions-zone.spec.ts

Issue Number: closes #13400
For the following code
```ts
import { NestFactory } from '@nestjs/core'
import { AppModule } from './app.module' // no-op module
async function bootstrap() {
const app = await NestFactory.create(AppModule, {
bufferLogs: true,
autoFlushLogs: true,
});
app.get('foo')
await app.listen(3000);
}
bootstrap();
```
we'll see the following error:
Do note that if `autoFlushLogs` is `false`, no logs will be shown for the above code.

fix(core): auto flush logs on synchronous internal errors

---

packages/microservices/server/server-grpc.ts

In order to find grpc service descriptors, `collectDeepServices` function recursively searches whole grpcDefinitions generated by protoLoader, which currently includes all descriptors like namespace, service, and field.
Because field descriptors cannot have namespace as their child, they don't need to be recursively searched. They can distinguished by checking existence of 'format' field and they can be skipped from the search to speed up the process.
In the project I am working on, proto models are heavily used.
It took more than 3 seconds in M2 MacBook Pro to run `collectDeepServices` before the modification.
Now it takes around 300ms in the same environment after …

refactor(microservices): improve speed of grpc server initialization

---

integration/microservices/e2e/math-grpc.spec.ts
integration/microservices/src/grpc/grpc.controller.ts
integration/microservices/src/grpc/math.proto
packages/microservices/server/server-grpc.ts
packages/microservices/test/server/server-grpc.spec.ts

currently the Observable that wraps ServerStreaming calls to write data out to the gRPC call object can reject which needs to be caught, even though the `call.emit` in the catch handler won't do anything because `call.end()` happens before that catch block can run, thanks to the `unsubscribe` call in the Subscription cleanup functions used inside `writeObservableToGrpc`
This promise should just never reject in the first place. The Promise is just used to signal when writing has completed and the call has ended. The error signal is handled exclusively by emitting `error` on the `Call`.
A series of changes recently outlined here …

refactor(microservices): prevent grpc write promise from throwing

---

packages/platform-ws/adapters/ws-adapter.ts

Close all existing websocket connections to ensure a graceful shutdown.
Issue Number: closes #13534
Existing connections are not closed automatically, according to https://github.com/websockets/ws/blob/master/doc/ws.md#serverclosecallback.
Application shutdown hangs when shutdown hooks are enabled and there are existing websocket connections. This is because the server.close callback that is awaited only resolves after all connections are closed. This is the call chain:
1. [process.cleanup](https://github.com/nestjs/nest/blob/master/packages/core/nest-application-context.ts#L326)
2. [NestApplication.dispose](https://github.com/nestjs/nest/blob/master/packages/core/nest-application.ts#L9 …

fix(ws): close existing connections

---

packages/core/router/router-response-controller.ts
packages/core/router/sse-stream.ts
packages/core/test/router/router-response-controller.spec.ts

Closes: #11601 
Issue Number: #11601

fix(core): possible memory leak when using server side events

---

packages/platform-fastify/adapters/fastify-adapter.ts

Route injection is handled by the shorthands methods
As discussed here: https://github.com/fastify/fastify/issues/5412#issuecomment-2068657469
Fastify allows the user to decorate the instance with any name. This can cause problems if common words are used instead of HTTP methods.
The other advantage is that Nest will not depend on the implementation of shorthands methods on the fastify side.
Related to https://github.com/nestjs/nest/pull/13278

refactor(platform-fastify): use the route method to inject routes

---

sample/18-context/src/app.module.ts
sample/18-context/src/main.ts
sample/18-context/src/my-dynamic.module.ts

From time to time people seem to not understand on how to use `app.select` over dynamic modules. I'll prepare another PR to improve the docs as well

chore: add use case for selecting dynamic modules to 18-context sample

---

packages/platform-fastify/adapters/fastify-adapter.ts

Issue Number: [13729](https://github.com/nestjs/nest/issues/13729)
It's possible to skip middie registration by passing a `skipMiddie` flag.

feat(fastify-adapter): support for skipping middie registration

---

packages/common/file-stream/interfaces/streamable-options.interface.ts
packages/common/utils/load-package.util.ts

same as https://github.com/nestjs/nest-cli/pull/2623

feat(common): less verbose 'missing package' error message

---

packages/platform-fastify/adapters/fastify-adapter.ts

Fastify has support for http options through the fastify function call which was not officially included in the nest adapter. Currently passing an object with a http field works, but gives the developer no type hinting about the `http` field.
First time open source contributor so please let me know what is not correct.
Currently creating an http server we cannot pass any http options without fooling the typescript type system. So this works, but in my opinion more magical than explicit.
```typescript
const serverOptions: ServerOptions = {
// Increase max header size from default ~16kb
maxHeaderSize: 32768,
};
const options = {
logger: undefined,
http: serverOptions,
};
const adapter = …
```

feat(fastify): add type for http options

---

packages/platform-fastify/adapters/fastify-adapter.ts

The usage of the @Search method with fastify was not properly declared
```ts
node_modules/@nestjs/core/adapters/http-adapter.js:59
return this.instance.search(...args);
^
TypeError: this.instance.search is not a function
at FastifyAdapter.search (node_modules/@nestjs/core/adapters/http-adapter.js:59:30)
at node_modules/@nestjs/core/router/router-explorer.js:105:17
at Array.forEach (<anonymous>)
at node_modules/@nestjs/core/router/router-explorer.js:90:29
at Array.forEach (<anonymous>)
at RouterExplorer.applyCallbackToRouter (node_modules/@nestjs/core/router/router-explorer.js:82:15)
at node_modules/@nestjs/core/router/router-explorer.js:65:18
at Array.forEach (<anonymous>)
at …
```

fix(platform-fastify): search method not declared

---

packages/microservices/server/server-grpc.ts
packages/microservices/test/server/server-grpc.spec.ts

Issue Number: #13719
If there are gRPC services with duplicate names, it is not possible to register handlers separately even if they are distinguished by different packages.
In decorators like `@GrpcMethod`, specifying the service name like `package.MethodName` allows handlers to be registered for each package separately.

feat(microservices): grpc package name can be specified with service name

---

packages/platform-ws/adapters/ws-adapter.ts

Each WebSocket request requires iterating through all message handlers to find the appropriate one now. When there are many message handlers, this is much less efficient than using a `Map` for lookup.
Using a `Map` for message handler lookup instead of traversing an array.

perf(ws): optimize message handler lookup

---

packages/core/interceptors/interceptors-consumer.ts
packages/core/test/interceptors/interceptors-consumer.spec.ts

fix(core): unhandled promise rejection in interceptors consumer

---

packages/common/pipes/parse-uuid.pipe.ts

ParseUUIDPipe will be able to validate uuid v7

feat(common): Added uuid v7 validation regex to ParseUUIDPipe

---

packages/core/discovery/discoverable-meta-host-collection.ts
packages/core/injector/container.ts
packages/core/inspector/serialized-graph.ts

style(core): fix formatting

---

packages/platform-fastify/package.json

see https://github.com/fastify/middie/releases/tag/v8.3.3

chore(fastify): upgrade `@fastify/middie` to address security vulnerability

---

packages/common/Readme.md
packages/core/Readme.md
packages/microservices/Readme.md
packages/platform-express/Readme.md
packages/platform-fastify/Readme.md
packages/platform-socket.io/Readme.md
packages/platform-ws/Readme.md
packages/testing/Readme.md
packages/websockets/Readme.md

Documentation (README) updates to many packages. This fixes changes in https://github.com/nestjs/nest/commit/d3dd896181379b3979fe2c0f65975e235c74b56d which broke the CircleCI badge across many READMEs
CircleCI Badge renders textual link instead of build:passing image.
CircleCI build:passing image renders

chore: Fix CircleCI Badge URLs in README

---

packages/platform-fastify/adapters/fastify-adapter.ts

Fastify expects uppercase and won't auto-add the HEAD method otherwise
Closes #13016
When a `GET` endpoint is registered with Fastify, Nest responds with 404 on a `HEAD` request
Issue Number: #14016 
Fastify correctly detects that the endpoint is a `GET` and auto-adds a `HEAD` handler too.
The Fastify logic is here and you can see it expects uppercase method names: 
https://github.com/fastify/fastify/blob/238d8a4f78b75c88e7b69b2d97fe27dd93fc520d/lib/route.js#L210

fix(fastify): uppercase http method names

---

packages/common/test/pipes/validation.pipe.spec.ts

no tests regarding `validateCustomDecorators` option of `ValidationPipe`
more unit tests to cover all values for `validateCustomDecorators` option of `ValidationPipe`

test(common): add tests for validation pipe on 'custom' types

---

package-lock.json
package.json
packages/platform-fastify/package.json

Seeing a security scan issue from Mend regarding a vulnerability with cookie, a dependency of light-my-request.
[light-my-request v6.1.0](https://github.com/fastify/light-my-request/releases/tag/v6.1.0) upgrades the affected package
The vulnerability is detailed here: https://www.mend.io/vulnerability-database/CVE-2024-47764
Mend security scan will no longer flag this dependency for repositories using the Fastify platform.

build(fastify): upgrade light-my-request to 6.1.0

---

package-lock.json
package.json
packages/platform-express/package.json

fixes vulnerabilites with cookie and path-to-regexp.
Currently security scanners like Anchore or Trivy are reporting vulnerabilities from express for certain packages. Please see
* https://github.com/jshttp/cookie/security/advisories/GHSA-pxg6-pf52-xh8x
* https://github.com/advisories/GHSA-9wv6-86v2-598j
Security scanners will not report vulnerabilities for the installed express package anymore.

build(express): upgrade to express 4.2.1

---

packages/platform-fastify/interfaces/nest-fastify-application.interface.ts

related to [https://github.com/fastify/fastify/pull/3712](https://github.com/fastify/fastify/pull/3712), [https://github.com/fastify/fastify/issues/3652](https://github.com/fastify/fastify/issues/3652) [https://github.com/fastify/fastify/pull/3751](https://github.com/fastify/fastify/pull/3751)
adding the missing instance.listen() interface to allow the use of opts: FastifyListenOptions argument instead of variadic arguments only, accordingly with the current version of fastify.
variadic is already deprecated in fastify v4 TS interfaces, being runtime warned in v5 and should be removed in v6.
this change **_is not removing any previous behavior_**.
allows the use of listen option …

feat(fastify): adding opts to the listen method interface and deprecating variadic JSDocs warnings

---

packages/common/serializer/class-serializer.interceptor.ts

Issue Number: Closes #12763 
options can be applied to plainToClass method too, which is needed for options like exposeDefaultValues.

fix(common): apply options to plaintoclass in classserializerinterceptor

---

packages/common/interfaces/nest-application-context-options.interface.ts
packages/core/injector/compiler.ts
packages/core/injector/container.ts
packages/core/injector/module.ts
packages/core/injector/opaque-key-factory/by-reference-module-opaque-key-factory.ts
packages/core/injector/opaque-key-factory/deep-hashed-module-opaque-key-factory.ts
packages/core/injector/opaque-key-factory/interfaces/module-opaque-key-factory.interface.ts
packages/core/nest-application-context.ts
packages/core/test/injector/compiler.spec.ts
packages/core/test/injector/opaque-key-factory/by-reference-module-opaque-key-factory.spec.ts
packages/core/test/injector/opaque-key-factory/deep-hashed-module-opaque-key-factory.spec.ts

feat(core): introduce different module opaque key factories

---

.circleci/install-wrk.sh
packages/common/decorators/core/inject.decorator.ts

we can pass anything to `@Inject()` decorator factory
now we can only pass injection tokens (same type for `provide` on custom providers)

feat(common)!: type narrowing allowed injection tokens for `@Inject()`

---

packages/microservices/server/server-tcp.ts

In the [docs from Node net server](https://nodejs.org/api/net.html#serverlisten):
> If port is omitted or is 0, the operating system will assign an arbitrary unused port, which can be retrieved by using server.address().port after the ['listening'](https://nodejs.org/api/net.html#event-listening) event has been emitted.
In the current code `0` is handled as a falsey value, which means the TCP server uses the `TCP_DEFAULT_PORT` value (`3000`) instead of letting the OS determine a random port.
Using a random free port is especially handy when running tests.
To get the port I am currently using the following function:
```ts
export const getAppTcpAddress = (app: INestMicroservice) => {
const serverTcp = (app as NestMicroservice)?.['server']
if (!(serverTcp instanceof ServerTCP)) return null …
```

Be able to use a random port for the TCP server

---

packages/common/interfaces/modules/module-metadata.interface.ts

Issue Number: closes #13733
we don't support supplying promises to the `exports` option of `@Module()`/dynamic module anymore. This feature never worked, anyway.

fix(common)!: drop broken support for promises on `exports` of modules

---

packages/core/scanner.ts

Issue Number: #14096 
The module distance is reevaluated when the module is not within the modules visited in the current depth search. This should be enough to avoid endless loops on cyclic dependency graphs. However, modules that have dependency paths of different length are now evaluated to the higher distance.

fix(core): revisit dependencies w/ possibly higher distance

---

packages/common/interfaces/nest-application-context.interface.ts
packages/core/nest-application-context.ts

Issue Number: https://github.com/nestjs/nest/issues/13735

feat(core): allow overriding abortOnError for the select method

---

packages/platform-fastify/interfaces/external/fastify-static-options.interface.ts

Proposal:
- Refactor `fastify-static-options.interface.ts`, see here for other info: https://github.com/fastify/fastify-static/blob/master/types/index.d.ts

refactor(fastify): update fastify static options interface

---

packages/common/decorators/http/create-route-param-metadata.decorator.ts
packages/common/interfaces/features/custom-route-param-factory.interface.ts

Issue Number: #14093 
The context parameter in createParamDecorator callback currently has an any type, which reduces type safety. Developers are unable to leverage the type-checking benefits of TypeScript when working with this parameter.
The context parameter in the createParamDecorator callback now has a narrower type of ExecutionContext. This allows developers to benefit from TypeScript’s type-checking capabilities, improving code quality and reducing potential errors when using this parameter in decorators.
This change improves type safety and aligns with TypeScript best practices by eliminating unnecessary any types. Tests have been added to validate that the context parameter is …

fix(common): type narrowing context parameter on createParamDecorator's callback 

---

.gitignore
integration/scopes/e2e/durable-providers.spec.ts
integration/scopes/src/durable/durable-context-id.strategy.ts
integration/scopes/src/durable/durable.service.ts
packages/core/injector/injector.ts
packages/core/injector/instance-wrapper.ts
packages/core/test/injector/instance-wrapper.spec.ts

Issue Number: https://github.com/nestjs/nest/issues/13953 https://github.com/nestjs/nest/issues/11664
PR based off https://github.com/nestjs/nest/pull/11666 + updated unit tests, added integration test, resolved conflits

fix(core): flaky durable provider, remove instance on error 

---

packages/core/nest-application-context.ts
packages/core/test/nest-application-context.spec.ts

Not fully sure if this is a bugfix or feature. I guess one could argue in both directions.
If you use lifecycle methods during startup of the nestjs applications with async operations with calls e.g. to the database, message/job processing and you receive a SIGTERM signal it can happen that the connections required for the async operations are closed while executing those async operations. For us this happened now and then in our K8s cluster where the process can be terminated at any time. That can lead to unexpected errors.
When a shutdown is requested via the incoming termination signal, the application defers calling the shutdown hooks until the app is fully …

chore(core): defer application shutdown until init finishes

---

packages/microservices/client/client-rmq.ts

Configuration properties were being discarded upon rmqClient creation.
All other properties, beside 'connectionOptions', from the this.options.socketOptions object ( of type AmqpConnectionManagerSocketOptions ) were being discarded on the creation of the AmqpConnectionManager client
See:
https://github.com/nestjs/nest/blob/master/packages/microservices/external/rmq-url.interface.ts#L47 https://github.com/jwalton/node-amqp-connection-manager/blob/v4.1.14/src/AmqpConnectionManager.ts#L46
Issue Number: https://github.com/nestjs/nest/issues/5788#issuecomment-2373361313
The other properties from the socketOptions key will now be included ( if present ) when the rmqClient is created

fix(microservices): include discarded rmq client options

---

package.json
tools/gulp/tasks/samples.ts

no changes
This PR replaces the [cli-color](https://github.com/medikoo/cli-color) package with smaller, faster, TypeScript-friendly [ansis](https://github.com/webdiscus/ansis).
- Installed package size is smaller: ansis `11 KB` (no dependencies) vs cli-color `754 KB` (5 dependencies)
see [Compare the size of most popular packages](https://github.com/webdiscus/ansis#compare-size)
- 20x faster than `cli-color`, see [Benchmarks](https://github.com/webdiscus/ansis#benchmark)
- Supports `Bun` and `Deno` runtimes
- [Fallback](https://github.com/webdiscus/ansis#fallback) to supported color space: TrueColor → 256 colors → 16 colors → no colors
- Supports [environment …

build(sample): replace cli-color with smaller and faster ansis

---

.circleci/install-wrk.sh

just to make this script a bit faster and less footprint in the `wrk` directory.

chore: shallow cloning `wrk` repository on benchmark setup

---

integration/hooks/e2e/on-module-destroy.spec.ts
packages/core/nest-application-context.ts

Suppose A depends on B, currently, A.onModuleDestroy is executed after B.onModuleDestroy. 
Issue Number: https://github.com/nestjs/nest/issues/14118
Suppose A depends on B, A.onModuleDestroy is executed before B.onModuleDestroy.

fix(core): Order of module destroy should be the reverse of module init

---

integration/hooks/e2e/on-module-init.spec.ts
packages/core/scanner.ts

The global module’s `onModuleInit` is **not** called before its dependent’s `onModuleInit`. This happens because, during the distance calculation, the global module is not yet included in the dependent’s `imports`. It only appears in the `imports` after `bindGlobalScope`, so the distance should be calculated at that point.
Issue Number: https://github.com/nestjs/nest/issues/14117
The global module’s `onModuleInit` is called before its dependent’s `onModuleInit`.
The test mentioned above passes.

fix(core): Calculate module distance after bindGlobalScope

---

packages/core/services/reflector.service.ts

Сorrection of `Reflector` types

---

packages/core/services/reflector.service.ts
packages/core/test/services/reflector.service.spec.ts

When only a single metadata value is present in the list of targets for `Reflector#getAllAndMerge`, that value gets wrapped in an array if it is not already an array or an object.
Previously, single values were returned as is, so the method could actually return any value. Now the method always returns an array or an object, and the type constraint for `TResult` is changed to reflect that.
Fixes #12231
`getAllAndMerge` can return any value when only one of its targets has a metadata value set, contradicting its declared return type.
Additionally, its return type declaration contradicts its actual and [documented](https://docs.nestjs.com/fundamentals/execution-context#reflection-and-meta …

fix(core): fix type and return value of `Reflector#getAllAndMerge`

---

packages/microservices/client/client-rmq.ts
packages/microservices/constants.ts
packages/microservices/interfaces/microservice-configuration.interface.ts
packages/microservices/server/server-rmq.ts

Currently, when creating a new microservice with @nestjs/microservices for RMQ, using an empty string for the queue name creates a queue named default rather than a unique, exclusive queue. Additionally, binding a queue to an exchange specified by exchange and routingKey does not occur as expected.
Issue Number: #13931 
This PR modifies the default queue name behavior to use an auto-generated name when an empty string is provided. It also implements automatic binding of the queue to the specified exchange and routing key, aligning with standard RabbitMQ behavior.
This PR also includes updates to the microservices package documentation, detailing the new exchange and routingKey options …

fix: rabbitmq bindings and auto-generated queues

---

integration/websockets/e2e/ws-gateway.spec.ts
packages/platform-ws/adapters/ws-adapter.ts

Issue Number: #14027 
Add a `setMessagePreprocessor` method to the `wsAdapter` to customize how messages are preprocessed.
```ts
const wsAdapter = new WsAdapter(app);
wsAdapter.setMessagePreprocessor((message: any) => {
const [event, ...data] = message;
return { event, data };
});
```

feat(ws): introduce message parser for ws adapter

---

packages/platform-express/multer/multer/multer.utils.ts
packages/platform-express/test/multer/multer/multer.utils.spec.ts

When transforming a `MulterError` into a Nest error, the optional `field` property is dropped.
The `field` property is included in the error message, if applicable.
If Multer throws an error, some identifying information is hidden from the error message. 
[https://github.com/expressjs/multer/blob/aa42bea6ac7d0cb8fcb279b15a7278cda805dc63/lib/multer-error.js#L19](https://github.com/expressjs/multer/blob/aa42bea6ac7d0cb8fcb279b15a7278cda805dc63/lib/multer-error.js#L19). This is where Multer adds the optional `field` property.

feat: add multer error fieldname to the exception message

---

integration/microservices/e2e/sum-rpc-async.spec.ts
packages/microservices/interfaces/microservice-configuration.interface.ts
packages/microservices/nest-microservice.ts

Microservices are now able to be created by getting their options from within the DI container itself. This has been a long requested feature of developers and I finally had some time to work through how we could possibly let this happen.
There is no way to apply the microservice config for a microservice server, by getting the configuration from within the DI container, like from the `ConfigService`
Issue Number:
* #12620
* #2343
* #4410 
* #5102
* #7108 
Microservices are now able to be configured via a provider that was registered within the DI tree, without creating a new `NestFactory.createApplicationContext()` first. Devs are now able to pass a `useFactory` and `inject` as a part …

feat: allow for microservice options to come from the di container

---

packages/microservices/client/client-kafka.ts
packages/microservices/test/client/client-kafka.spec.ts

Issue Number: #12748
enable kafka producer to emit batch
- [v] Yes

feat: emit batch

---

sample/01-cats-app/src/cats/cats.controller.spec.ts
sample/01-cats-app/src/cats/cats.service.spec.ts
sample/01-cats-app/src/cats/cats.service.ts

- [ x] Other... Please describe: Adding unitary tests to sample 01 service
The sample 01 already have e2e tests and unitary tests on the controller, but it's missing tests on the service. It's also missing tests on the create cat function
Issue Number: #1539 
I've added a new test file providing an example on how to test only the service, and modified the controller test to add the create cat test.
I've tried to create an e2e test to the POST method, however the Role guard is blocking the request, I've noticed that in the  `src/common/guards/roles.guard.ts` the guard is expecting an property from the request called `user` but I did not found a way to pass this property in my request, …

test(sample-01): added service unit tests

---

sample/06-mongoose/package-lock.json
sample/06-mongoose/package.json
sample/06-mongoose/src/cats/cats.controller.spec.ts
sample/06-mongoose/src/cats/cats.controller.ts
sample/06-mongoose/src/cats/cats.service.spec.ts
sample/06-mongoose/src/cats/cats.service.ts
sample/06-mongoose/src/cats/dto/update-cat.dto.ts

Sample 06-mongoose is missing some unit tests.
More unit tests in sample 06-mongoose.

Add unit tests for sample 06-mongoose

---

packages/common/module-utils/utils/get-injection-providers.util.ts
packages/common/test/module-utils/utils/get-injection-providers.util.spec.ts
packages/core/injector/injector.ts

fix(common,core): align the logic of optional provider

---

integration/websockets/e2e/error-gateway.spec.ts
packages/websockets/exceptions/base-ws-exception-filter.ts
packages/websockets/test/exceptions/ws-exceptions-handler.spec.ts

Includes the `cause` attribute when emitting the `exception` message. This allows the error to be associated with the request that caused the exception.

feat(websockets): include exception cause to associate error with req

---

integration/hello-world/e2e/middleware-fastify.spec.ts
packages/platform-fastify/adapters/fastify-adapter.ts

Issue Number: #13401 , #11572
By using `FastifyAdapter` and setting a route config with `exclude` and `prefix` the middleware stops begin executed
For reproduction see tests in https://github.com/xtrinch/nestjs-middleware-issue-demo provided by @xtrinch 
The behavior occurs because during the normalization performed on the pathname, it is not taken into account whether the application instance was configured to handle a prefix.
These changes guarantee that when the Adapter is registered with a prefix, the normalization of the pathname will be taken into account when generating the regex expression.
Note: Given the [@fastify/middie](https://github.com/fastify/middie) behavior described …

fix(fastify-adapter): middleware not executed when root path is excluded

---

integration/lazy-modules/e2e/lazy-import-transient-providers.spec.ts
integration/lazy-modules/src/eager.module.ts
integration/lazy-modules/src/lazy.controller.ts
integration/lazy-modules/src/transient.module.ts
integration/lazy-modules/src/transient.service.ts
packages/core/injector/module.ts

Issue Number: Closes #13761 
When a lazy module resolver a lazy provider marked as transient the singleton dependencies are recreated for the new requests in same context.
Skipping creation of new providers if they are marked as transient and have annotation in the score of module.

fix(core): dependencies not resolving for transient lazy providers

---

packages/microservices/server/server-nats.ts
packages/microservices/test/server/server-nats.spec.ts

feat(microservices): support nats queue per handler

---

packages/common/pipes/validation.pipe.ts

fix(common): fallback to empty string for enums when validating (swc builder)

---

integration/websockets/e2e/gateway.spec.ts
integration/websockets/src/server.gateway.ts
packages/websockets/adapters/ws-adapter.ts
packages/websockets/socket-module.ts

fixes #13910
Issue Number: #13910 
When ws connections and other long-running connections are handled by the same HTTP server instance, the shutdown process will not be blocked, allowing for proper termination of all connection types.

fix(websockets): Prevent HTTP server early close in Socket.IO shutdown

---

packages/platform-socket.io/adapters/io-adapter.ts
packages/websockets/adapters/ws-adapter.ts

When forceCloseConnections is enabled, non-shared HTTP servers are not being properly closed.
When forceCloseConnections is enabled, non-shared HTTP servers should be closed by WS.

fix(websockets): ensure non-shared servers call close method

---

packages/common/pipes/file/file-type.validator.ts
packages/common/pipes/file/max-file-size.validator.ts
packages/common/test/pipes/file/file-type.validator.spec.ts
packages/common/test/pipes/file/max-file-size.validator.spec.ts

Currently, the file validation system (e.g., MaxFileSizeValidator and FileTypeValidator) provides error messages that are not context-aware.
Specifically:
MaxFileSizeValidator uses a default error message that does not include the current file size if available.
FileTypeValidator uses a default error message without referencing the current file's MIME type.
This limits the usefulness of the error messages for developers, as they lack specific context regarding what caused the validation failure.
Issue Number: #14070 
This PR enhances the error message generation for file validators:
example code:
```
@Post('upload-image')
@UseInterceptors(FileInterceptor('file'))
uploadFile( …
```

feat(common): add error messages for file validators

---

packages/common/decorators/http/route-params.decorator.ts

Closes #14254
Issue Number: #14254
The RawBody decorator now has proper TypeScript type declarations for pipe transformations. Users can now use pipes with the RawBody decorator with full type safety

chore(common): Add type declaration for RawBody decorator with pipes

---

integration/hooks/e2e/before-app-shutdown.spec.ts
integration/hooks/e2e/on-app-shutdown.spec.ts
packages/core/nest-application-context.ts

Please check if your PR fulfils the following requirements:
Issue Number: #14118
This issue was already closed. However the fix in #14111 only impacts the `onModuleDestroy` hook. Other shutdown hooks still have an incorrect behavior (i.e. are called in ascending distance order).
The `beforeApplicationShutdown` and `onApplicationShutdown` hooks are called in descending distance order.
This is purposely extremely similar to #14111, but I'm open to suggestions if needed.
I've targeted `11.0.0` because this was also the case of the aforementioned PR.

Fix shutdown hooks order

---

packages/core/helpers/router-method-factory.ts

It is useful piece of code for create custom adapter
- [ x] Refactoring (no functional changes, no api changes)
const REQUEST_METHOD_MAP  { *** }
export const REQUEST_METHOD_MAP  { *** }
- [x ] No
For example people do that
[type HttpMethods =] = *** (https://github.com/seidelmartin/nest-koa-adapter/blob/d83478e55351be128762836a9cffff0e12b5c234/src/KoaAdapter.ts#L22)
but can use REQUEST_METHOD_MAP
I need for example something like:
```
m !== REQUEST_METHOD_MAP[RequestMethod.ALL]
? REQUEST_METHOD_MAP[m] as Method : undefined
```

fix: export cont REQUEST_METHOD_MAP from router-method-factory 

---

package-lock.json
package.json
packages/core/package.json

Current `@nuxtjs/opencollective` version is using a long-time deprecated version of `node-fetch`. This version under the hood is using `whatwg-url`, that in turn uses `tr46@0.3.0` which is the cause of dreaded warning most people've seen in their life, namely
```
(node:96024) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
```
Updated version of `@nuxt/opencollective` is not using external fetch package at all.
```
pnpm why tr46
dependencies:
@anatine/zod-nestjs 2.0.9
└─┬ @nestjs/swagger 7.4.2 peer
└─┬ @nestjs/core 10.4.12 peer
└─┬ …
```

chore(deps): Update opencollective to 0.4.1 under new scope

---

integration/cors/e2e/fastify.spec.ts
packages/common/interfaces/http/http-server.interface.ts
packages/common/interfaces/nest-application.interface.ts
packages/core/adapters/http-adapter.ts
packages/core/nest-application.ts
packages/platform-express/interfaces/nest-express-application.interface.ts
packages/platform-fastify/adapters/fastify-adapter.ts
packages/platform-fastify/interfaces/nest-fastify-application.interface.ts

Fastify adapter uses typings from `@fastify/cors` package for `enableCors` method
Fix nestjs/nest#13234
Issue Number: https://github.com/nestjs/nest/issues/13234
I'm not sure I've got the architecture right. My understanding is that the adapter should be platform-independent, and if there is a platform-specific implementation of the adapter then not. I took inspiration from `useStaticAssets` method for example, i.e. a universal adapter has `any` types and then the individual types are applied to the adapter (fastify, express) implementations.

fix: typings for fastify `enableCors` method

---

.github/ISSUE_TEMPLATE/Bug_report.yml
.github/ISSUE_TEMPLATE/Feature_request.yml
.github/ISSUE_TEMPLATE/Regression.yml
.github/ISSUE_TEMPLATE/Suggestion_improve_performance.yml

how the issues will use the _type_ feature 
https://github.com/orgs/community/discussions/112806

chore: add issue types to issue templates forms

---

packages/testing/test.ts
packages/testing/testing-module.builder.ts

Issue Number: #14455
Add the ability to control moduleIdGeneratorAlgorithm in TestingModuleBuilder

fix: Module id generatorAlgorithm can't be controlled in test #14455

---

packages/platform-express/adapters/express-adapter.ts
packages/platform-express/package.json

`@nestjs/platform-express` depends on `express@5.0.1` and on `body-parser@1.20.3`. Express 5.0.1 itself depends on `body-parser@2.0.2` and reexports its middlewares. So 2 different versions of `body-parser` are installed and used.
`nestjs/platfrom-express` depends only on `express@5.0.1` and uses the body-parser reexports. They are not deprecated and will not be removed! See: https://github.com/expressjs/express/blob/master/lib/express.js#L77-L81
It was already proposed in #8645 a while ago.

fix: use express body-parser reexports

---

sample/25-dynamic-modules/package.json
sample/26-queues/package.json
sample/27-scheduling/package.json
sample/28-sse/package.json

as we are using the latest version of `dotenv`, we don't need the `@types/dotenv` anymore

chore(sample): remove `@types/dotenv` useless dev dep

---

packages/microservices/server/server-kafka.ts

Issue Number: [#11616](https://github.com/nestjs/nest/issues/11616)
While the new major release ships an ability to unwrap underlying server instance, it's still not possible to manipulate on existing consumer and producer instances which are created in `start` method. As an example provided in the issue, we still can't subscribe heartbeat event on consumer created by NestJS
Following the example in Redis server, we can return all created instances, but not just client instance. In this case everyone can get an access to consumer and producers
`unwrap` method is not type-safe and fully depend on developer who define expected type. If someone is already start using `unwrap` method we …

feat(microservices): return all clients from kafka unwrap

---

integration/hello-world/e2e/middleware-execute-order.spec.ts
packages/core/middleware/middleware-module.ts

Issue Number: https://github.com/nestjs/nest/issues/14487

fix(core): global module middleware should be executed first

---

integration/hello-world/e2e/middleware-fastify.spec.ts
packages/core/middleware/route-info-path-extractor.ts

fix(core): allow optional named wildcard groups 

---

integration/hello-world/e2e/middleware-execute-order.spec.ts
packages/core/middleware/middleware-module.ts

- [] Tests for the changes have been added (for bug fixes / features)
Global middleware is not executed in import order, because sort is not stable
Preserve order of global middleware definitions.  
Sort docs state a list of rules that the sort function must adhere to. Current impl violates it and as such the order is not stable. Violation happens when 2 modules are both global but he return value is not 0. so if comparing a,b it retuns a is "bigger" and if comparing b,a it returns b is "bigger".
This bug was introduced in https://github.com/nestjs/nest/commit/44490dcad084c856e52987a38b3553a4c112e266

fix: middleware sort issues

---

.gitignore

When I run npm run build:samples on my machine. I have a bunch of package-lock.json files' changes afterwards.
These package-lock.json files are ignored by version control.

chore(sample): ignore all package lock files

---

packages/platform-express/adapters/express-adapter.ts

Express 5 made the router public API again and renamed the field from app._router to app.router. This broke the detection mechanism whether a middleware named "jsonParser" or "urlencodedParser" is already re or not, because app._router no longer exists.
- the adjusted code seems totally untested. so not sure how to add a simple test. maybe I missed something?
The express adapter overwrites existing middlewares called jsonParser and urlencodedParser with its on parsers.
This regression was caused by updating from Express 4 to 5. Express 5 exposes the router via app.router, while Express 4 exposed it via app._router.
Issue Number: N/A - I didn't create an issue yet - let me know if you …

fix(platform-express) make check for existing middlewares work with Express 5

---

packages/platform-express/adapters/express-adapter.ts
packages/platform-express/test/adapters/express-adapter.spec.ts

Express 5 made the router public API again and renamed the field from app._router to app.router. This broke the detection mechanism whether a middleware named "jsonParser" or "urlencodedParser" is already registered or not.
Unfortunately, https://github.com/nestjs/nest/pull/14574 only fixed the issue partially. This commit now uses app.router everywhere.
To avoid future regressions a test was added to verify the expected behavior.
The express adapter overwrites existing middlewares called jsonParser and urlencodedParser with its on parsers.
This regression was caused by updating from Express 4 to 5. Express 5 exposes the router via app.router, while Express 4 exposed it via …

fix(platform-express) respect custom parser middlewares in Express 5

---

packages/platform-fastify/adapters/fastify-adapter.ts
packages/platform-fastify/package.json

This should be considered. The performance gains are not negligible. Additionally, [find-my-way](https://github.com/delvedor/find-my-way/) and [Fastify](https://fastify.dev/) use it by default, so there's no reason to regress on this for the adapter.
The `querystring` is also absolutely deprecated with the last feature commit from 2018 (it seems). @kamilmysliwiec 
Related to https://github.com/nestjs/nest/pull/10248.

perf: Switch deprecated parser querystring for fast-querystring

---

packages/core/router/legacy-route-converter.ts

feat(core): add options to the legacy route converter

---

integration/lazy-modules/e2e/lazy-import-request-providers.spec.ts
integration/lazy-modules/src/lazy.controller.ts
integration/lazy-modules/src/request.module.ts
integration/lazy-modules/src/request.service.ts
packages/core/injector/module.ts

Issue Number: Closes https://github.com/nestjs/nest/issues/14791
Skipping creation of new providers if they are marked as request-scoped and have annotation in the score of module.

fix(core): dependencies not resolving for request-scoped lazy providers

---

packages/microservices/client/client-grpc.ts

I saw the method `getService` from `client-grpc.ts` always re-create `client` that could lead to memory potentially. Also I saw method `getClientByServiceName` has been implemented by not being used by anywhere. 
My backend got issue when calling `getService` multiple times and I observed that memory has been increased constantly (I know that we should call `getService` only once when NestModule has been inited but there is exception for my codebase). 
I've tested by calling thousand of grpc calls (that will call `getService` method) and here is the memory profiling.
After changing `createClientByServiceName` by `getClientByServiceName`, the memory issue has been solved, no more memory increasing occur.

fix(microservices): do not re-create client connection once get client by service name

---

integration/hello-world/e2e/middleware-fastify.spec.ts
packages/platform-fastify/adapters/fastify-adapter.ts

Calling `setGlobalPrefix()` with an exclusion list that includes wildcards or parameters when middleware is present with fastify causes an error when trying to run the application.
Issue Number: https://github.com/nestjs/nest/issues/14894
Application starts, middleware is applied, prefix is applied and routes are correctly excluded.
I didn't make any specific doc updates as the docs are already correct for the expected behavior but if something else is needed just let me know. This was originally introduced by https://github.com/nestjs/nest/pull/13797 but I think this fix maintains the spirit and the desired outcome of that PR.

fix(fastify-adapter): global prefix exclusion path handling w/middleware

---

packages/microservices/client/client-grpc.ts

The type definition for the variable `keepaliveKeys` is incorrect.
Because `GrpcOptions['options']['keepalive']` can be undefined, an unintended type is being generated. (`Record<never, string>`)
It is unintentionally allowing anu key values.

refactor(microservices): fix wrong type for keepalive keys

---

packages/platform-fastify/adapters/fastify-adapter.ts

Issue Number: https://github.com/nestjs/nest/issues/14510
PR: https://github.com/nestjs/nest/pull/14511
Fix operator comparison

fix(fastify): methods comparison

---

package-lock.json
package.json
packages/common/pipes/file/file-type.validator.ts

Replace wrapping dynamic import of ESM module in `eval` with load-esm.
Wraps the dynamic import in an `eval` function, which is not the best workaround to avoid the TypeScript compiler breaks the  dynamic import.
More information: https://stackoverflow.com/a/79265806/28701779
Is uses [load-esm](https://github.com/Borewit/load-esm) instead, which is just like `eval` a simple trick to keep the dynamic import outside the scope of the TypeScript compiler, yet not by wrapping the entire ESM module in an `eval` method.
Not black and white science, wrapping code in `eval` this case the import and the entire ESM module, is not such a great idea:
- https://stackoverflow.com/a/198031/28701779 …

refactor(common): Prevent JavaScript being wrapped in `eval`

---

packages/common/test/pipes/file/file-type.validator.spec.ts

Fixes a unit test, which aims to provide a PNG instead of JPEG. The unit test passes because the file type cannot be recognized, yet the intention was more likely to detect it was a different file type.
* Change the PNG data into valid PNG file data.
* Ensure the PNG data is detected as PNG.
What kind of change does this PR introduce: _Fix unit test_

test(common): Fix invalid file type test

---

packages/microservices/server/server-redis.ts
packages/microservices/test/server/server-redis.spec.ts

Redis connection were not properly closed for pub/sub client due to missing async/await
Added async/await when quit() is called for pub/sub client for server-redis so that all the connections are properly closed.

fix(microservices): ensure all redis connections are closed

---

packages/platform-express/adapters/express-adapter.ts

Pipeline is great for when multiple streams need to be used together but can also end up causing problems when there's a readstream of a large file being sent in chunks, because the streams get destroyed early. Technically, everything works fine, but there's warnings in the terminal that could be misleading, so calling the streams with error handlers directly is a safer way to go about it.
When streaming back a large partial file, the terminal would print a warning along the lines of:
```
[Nest] 21362  - 04/23/2025, 8:33:41 AM   ERROR [StreamableFile] Error [ERR_STREAM_PREMATURE_CLOSE]: Premature close
at ReadStream.onclose (node:internal/streams/end-of-stream:153:30)
at …
```

feat: remove use of pipeline

---

packages/microservices/server/server-rmq.ts
packages/microservices/test/server/server-rmq.spec.ts

AMQP close connection method is asynchronous, in the current behaviour, connection were not properly closed for channel/server due to missing `async/await`.
Added `async/await` when `close()` is called for channel/server in `server-rmq` so that all the connections are properly closed.

fix(microservices): ensure all the amqp connections are closed properly

---

packages/core/adapters/http-adapter.ts
packages/core/test/utils/noop-adapter.spec.ts
packages/platform-fastify/adapters/fastify-adapter.ts

fix(core): bring back `getHeader` and `appendHeader` methods from `AbstractHttpAdapter`

---

packages/common/services/console-logger.service.ts

Proposal:
-  Marked public api with `@publicApi` tag in the `console-logger.service.ts`

chore(): marked public api in the console-logger.service.ts

---

packages/microservices/client/client-redis.ts
packages/microservices/client/client-rmq.ts
packages/microservices/test/client/client-redis.spec.ts
packages/microservices/test/client/client-rmq.spec.ts

Redis and AMQP close connection method is asynchronous, in the current behaviour, connection were not properly closed for pub/sub or channel/client for clients due to missing `async/await`.
Added `async/await` when `close()` is called for pub/sub or channel/client in `client-redis` and `client-rmq` respectively, so that all the connections are properly closed.

fix(microservices): ensure all redis and amqp client closes properly

---

packages/core/router/routes-resolver.ts
packages/core/test/router/routes-resolver.spec.ts

FastifyError instance did not mapped to HttpException which broke conditions in ExceptionFilter
Issue Number: #15022
Added handler for FastifyError in mapping function in RoutesResolver.

fix(core): HTTP adapter error mapping

---

packages/microservices/external/rmq-url.interface.ts
packages/microservices/interfaces/microservice-configuration.interface.ts

Currently, only the default exchange types can be used.
Make exchangeType configurable as a generic string instead of strict union, enabling support for plugins like [rabbitmq-delayed-message-exchange](https://github.com/rabbitmq/rabbitmq-delayed-message-exchange) which use non-standard types (e.g., `x-delayed-message`, `x-local-random`).
| # | Exchange Type | Plugin | Key Features | Min. RabbitMQ |
|---|---------------|--------|--------------|---------------|
| 1 | **`x‑delayed-message`** | [rabbitmq_delayed_message_exchange](https://github.com/rabbitmq/rabbitmq-delayed-message-exchange) | Schedules or retries messages via the `x-delay` header—removes the need for …

feat(microservices): Allow custom exchangeType as string for plugin compatibility

---

packages/microservices/interfaces/custom-transport-strategy.interface.ts
packages/microservices/interfaces/microservice-configuration.interface.ts
packages/microservices/server/server-factory.ts
packages/microservices/server/server-grpc.ts
packages/microservices/server/server-kafka.ts
packages/microservices/server/server-mqtt.ts
packages/microservices/server/server-nats.ts
packages/microservices/server/server-redis.ts
packages/microservices/server/server-rmq.ts
packages/microservices/server/server-tcp.ts
packages/microservices/server/server.ts
packages/microservices/test/server/server-factory.spec.ts

transportId field is hardcoded in specific server classes.
If users need more concurrency on same server or many servers need to extends from base server classes and override server id
Sample:
```ts
import { CustomTransportStrategy, KafkaOptions, ServerKafka } from '@nestjs/microservices';
export const NEW_KAFKA_TRANSPORT = Symbol('NEW_KAFKA_TRANSPORT');
export class NewKafkaServer extends ServerKafka implements CustomTransportStrategy {
//@ts-expect-error In Nest.js ServerKafka can not override transportId
transportId = NEW_KAFKA_TRANSPORT;
constructor(config: KafkaOptions['options']) {
super(config);
}
}
```
Issue Number:
https://github.com/nestjs/nest/issues/14590 …

feat(microservices): add specific transport id to microservices

---

packages/microservices/client/client-redis.ts
packages/microservices/test/client/client-redis.spec.ts

When calling `close()` on `ClientRedis`, the `isManuallyClosed` flag is set **after** awaiting the `quit()` calls on the Redis clients. If Redis emits the `'end'` event during or after `quit()`, event handlers may see `isManuallyClosed` as `false` and incorrectly log errors or attempt reconnection logic. This creates a race condition and can result in misleading error logs during a normal shutdown.
The `isManuallyClosed` flag is now set to `true` **before** calling `quit()` on the Redis clients. This ensures that any event handlers triggered during shutdown will see the correct state and will not log errors or attempt reconnection when the shutdown is intentional. …

fix(microservice): prevent error logs during redis client shutdown

---

packages/microservices/nest-microservice.ts
packages/microservices/test/nest-microservice.spec.ts

When using dynamic microservice configuration with useFactory, any strategy field returned from the factory function is ignored.
This makes it impossible to provide a custom transport strategy dynamically.
Issue Number: [#15144](https://github.com/nestjs/nest/issues/15144)
NestMicroservice now properly checks for a strategy field after resolving AsyncMicroserviceOptions.useFactory().
Adds test cases to ensure both static and dynamic strategy injection paths work as expected.

fix(microservices): support custom strategy in async usefactory config

---

integration/repl/e2e/repl-process.spec.ts
integration/repl/src/database/database.connection.ts
integration/repl/src/database/database.module.ts
integration/repl/src/long-living-app.module.ts
integration/repl/src/repl.ts
packages/core/repl/repl.ts

The application module we pass to repl may have long-running phases (e.g. database connection polling) and if we don't finish those long-running phases the repl would stuck on exit possibly forever.
I encoutered this issue while using MikroORM.forRoot module.
The solution is to call `app.close()` when repl exits. Modules should implement graceful shutdown using lifecycle hooks.
When using modules that have long-running phases (e.g. a database module) repl process stuck on exit and never finishes.
Repl process gracefully shutdown modules with long-running phases and exits itself.

fix(core): gracefully shutdown the app when repl exits

---

packages/common/interfaces/microservices/nest-hybrid-application-options.interface.ts
packages/core/nest-application.ts
packages/core/test/nest-application.spec.ts

Currently, when using `app.connectMicroservice()`, the microservice is immediately initialized inside the method call. This creates several limitations:
1. **Limited configuration options**: Microservice settings can only be applied through `inheritAppConfig` option and must be set before calling `.connectMicroservice()`
2. **No post-connection configuration**: Adding global handlers, pipes, filters, interceptors, etc. to the returned `INestMicroservice` object is ineffective because initialization has already completed
3. **Confusing developer experience**: The API suggests that you can configure the microservice after connection, but this doesn't work as expected
**Example of current …

feat(core): defer initialization connected microservice

---

packages/core/guards/guards-consumer.ts
packages/core/test/guards/guards-consumer.spec.ts

If we have multiple sync guards being executed and the second one initializes a AsyncLocalStorage, The storage gets lost due to Nodejs promise handling.
In the same situation, the storage is accessible along the request, which is useful if you want to have contextual operation with some granular control "guard wide"
This need appeared after I created two libs:
* [winston-context-logger](https://www.npmjs.com/package/winston-context-logger), which offers a logger integrated with an async local storage that is common for me to initialize at guards in projects using NestJS (this lib is not well documented yet)
* …

feat: supporting fine async storage control

---

packages/microservices/constants.ts
packages/microservices/server/server-rmq.ts
packages/microservices/test/server/server-rmq.spec.ts

close #15304
Issue Number: 15304
Before starting I asked myself, what would be the best approach?
Option 1: Keep Current Regex but Make it Safer
Tradeoffs:
- ✅ Minimal change, maintains current performance, backward compatible
- ❌ Still vulnerable to other typical regex issues, complex escaping logic, harder to maintain
Option 2: Use Map and Nested For Loop same as SeerverMQTT
Based on MQTT approach (matchMqttPattern in server-mqtt.ts:180-210):
- Split patterns and topics by separator
- Loop through segments comparing each one
- Handle wildcards with simple string comparison
Tradeoffs:
- ✅ No regex vulnerabilities, easier to understand, similar to existing MQTT code
- ✅ More …

fix(microservices): Revisit RMQ pattern matching with wildcards

---

packages/core/router/utils/flatten-route-paths.util.ts
packages/core/test/router/utils/flat-routes.spec.ts

flattenRoutePath method was returning an object instead of a module when path property was an empty string
closes #15332
Issue Number: #15332

fix(core): Make flattenRoutePath return a valid module

---

packages/platform-fastify/adapters/fastify-adapter.ts
packages/platform-fastify/constants.ts
packages/platform-fastify/decorators/index.ts
packages/platform-fastify/decorators/route-schema.decorator.ts
packages/platform-fastify/test/decorators/router-schema.decorator.spec.ts

Add an ability to attach json schema to request with a RequestSchema decorator
Currently, there is no easy way of using fastify's [schema property](https://fastify.dev/docs/latest/Reference/Validation-and-Serialization/) and adding a response schema can have positive impact on performance [source](https://fastify.dev/docs/latest/Reference/Validation-and-Serialization/#serialization)
This PR adds a new decorator `RequestSchema` that takes a schema object and sets it as `schema` property on fastify route [doc](https://fastify.dev/docs/latest/Reference/Routes/#routes-options)

feat(fastify): add decorator for custom schema

---

packages/core/test/scanner.spec.ts

There is a typo in `packages/core/test/scanner.spec.ts`
The class is named `OverwrittenControlerOne`
The typo has been fixed by renaming `OverwrittenControlerOne` to `OverwrittenControllerOne`

refactor(core): fix the typo 'controler' to 'controller'

---

packages/microservices/helpers/json-socket.ts

MaxPacketLengthExceededException always reports length of 0
Issue Number: https://github.com/nestjs/nest/issues/15472
MaxPacketLengthExceededException correctly reports the actual buffer length.

fix(microservices): report correct buffer length in exception

---

packages/microservices/errors/invalid-tcp-data-reception.exception.ts
packages/microservices/errors/invalid-tcp-message.exception.ts
packages/microservices/server/server-tcp.ts

Currently, when the NestJS ​​Server-TCP module​​ encounters ​​receive errors (recv errors)​​, the thrown error messages are overly verbose or include unnecessary low-level details (e.g., raw socket error stacks, unformatted binary data). This causes:
1. Developers to struggle to quickly identify the root cause;
2.Logs or monitoring systems to be cluttered with irrelevant information, reducing readability.

feat(errors): add InvalidTcpDataReceptionException for handling TCP receive errors​

---

integration/hello-world/e2e/force-console.spec.ts
packages/common/interfaces/nest-application-context-options.interface.ts
packages/common/services/console-logger.service.ts
packages/common/test/services/logger.service.spec.ts
packages/core/nest-factory.ts

Currently, ConsoleLogger always uses process.stdout.write() and process.stderr.write() for output.
This causes issues in test environments like Jest, which can buffer console.* calls but not direct stream writes. making it difficult to capture or suppress log output during tests.
Issue Number: #15483 
Added a new forceConsole option to ConsoleLoggerOptions that, when set to true, forces the logger to use console.log() and console.error() instead of process.stdout.write() and process.stderr.write().
This allows test frameworks like Jest to properly buffer and capture log output, making tests cleaner and enabling log assertion testing.
Example usage:
```ts
const logger = new …
```

feat(common): add force-console option to console logger
