nestjs/nest

- src/common/enums/request-method.enum.ts
- src/common/test/utils/route-params.decorator.spec.ts
- src/common/utils/decorators/request-mapping.decorator.ts
- src/core/helpers/router-method-factory.ts
- src/core/test/helpers/router-method-factory.spec.ts
PATCH method is widely used, would be nice to support the one.
> Support HTTP method PATCH

- .github/ISSUE_TEMPLATE.md
- Readme.md
- package.json
This pull request adds backers and sponsors from your Open Collective https://opencollective.com/nest ❤️
It adds two badges at the top to show the latest number of backers and sponsors. It also adds placeholders so that the avatar/logo of new backers/sponsors can automatically be shown without having to update your README.md. [[more info](https://github.com/opencollective/opencollective/wiki/Github-banner)]
See how it looks on [this repo](https://github.com/apex/apex#backers).
We have also added a `postinstall` script to let people know after `npm|yarn install` that you are welcoming donations. [[More info](https://github.com/OpenCollective/opencollective-cli)]
> Activating Open Collective

- src/common/utils/decorators/exception-filters.decorator.ts
- src/common/utils/decorators/use-guards.decorator.ts
- src/common/utils/decorators/use-interceptors.decorator.ts
- src/common/utils/decorators/use-pipes.decorator.ts
Also removes some extra "the".
> 'setuped' => 'set up'

- src/websockets/container.ts
```
const m = new Map();
m.set({a:1}, 2);
m.get({a:1}); // we get undefined
```
> Map key should not be object

- package.json
- src/core/pipes/pipes-model-parser.ts
- src/core/test/pipes/pipes-model-parser.spec.ts
https://github.com/nestjs/nest/issues/196
> Created PipesModelParser

- examples/01-cats-app/package.json
- examples/10-mockgoose/e2e/cats/cats.e2e-spec.ts
- examples/10-mockgoose/e2e/jest-e2e.json
- examples/10-mockgoose/index.js
- examples/10-mockgoose/package.json
- examples/10-mockgoose/src/modules/app.module.ts
- examples/10-mockgoose/src/modules/cats/cats.controller.ts
- examples/10-mockgoose/src/modules/cats/cats.module.ts
- examples/10-mockgoose/src/modules/cats/cats.providers.ts
- examples/10-mockgoose/src/modules/cats/cats.service.ts
- examples/10-mockgoose/src/modules/cats/dto/create-cat.dto.ts
- examples/10-mockgoose/src/modules/cats/interfaces/cat.interface.ts
- examples/10-mockgoose/src/modules/cats/schemas/cat.schema.ts
- examples/10-mockgoose/src/modules/database/database.module.ts
- examples/10-mockgoose/src/modules/database/database.providers.ts
- examples/10-mockgoose/src/server.ts
- examples/10-mockgoose/tsconfig.json
- examples/10-mockgoose/tslint.json
- package-lock.json
Creating 10-mockgoose example on top of 06-mongoose ( mongoose ) and 01-cats-app ( e2e )
> E2E Testing MongoDB application with Mockgoose.

- examples/03-microservices/src/modules/common/pipes/validation.pipe.ts
Remove unused imports like WsException and HttpStatus
> fix(microservices-example): Remove unused imports

- examples/12-graphql-apollo/src/cats/cats.resolvers.ts
- examples/12-graphql-apollo/src/cats/cats.service.ts
- examples/12-graphql-apollo/src/cats/cats.types.graphql
* Fixed some issues on run graphql example.
Nest is amazing!
Great work, congratulations!
> [Fix] Graphql example

- readme_zh.md
> Add Chinese document

- lib/common/package.json
see https://github.com/typestack/class-transformer/issues/28
> fix class-transformer related issues

- .travis.yml
An indentation of 6 spaces is not what I normally see and there should be used 2 spaces in yaml files.
> style: reformat Travis CI config

- sample/01-cats-app/src/common/guards/roles.guard.ts
```
[ ] Bugfix
[ ] Feature
[ x ] Other... Please describe: Fix Samples
```
in sample 01-cats-app hasRole is not a function 
https://github.com/nestjs/nest/blob/master/sample/01-cats-app/src/common/guards/roles.guard.ts#L15
https://github.com/nestjs/nest/blob/master/sample/01-cats-app/src/common/guards/roles.guard.ts#L16
Docs are okey 
hasRole is assigned with a function.
```
[ ] Yes
[ x ] No
```
I was considering opening an issue, then I read the guidelines and decided to create the little PR
Great samples thanks …
> sample(@nestjs) fix hasRole is not a function (01-cats-app)

- packages/common/pipes/validation.pipe.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> bugfix(@nestjs/common) ValidationPipe throws 500 error

- Readme.md
Update Chinese guide format
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> Update Chinese guide format

- bundle/core/errors/messages.js
- bundle/websockets/adapters/io-adapter.js
- bundle/websockets/adapters/ws-adapter.js
- packages/core/errors/exceptions/undefined-dependency.exception.ts
- packages/core/errors/exceptions/unknown-dependencies.exception.ts
- packages/core/errors/messages.ts
- packages/core/injector/injector.ts
- packages/core/test/errors/test/messages.spec.ts
- packages/core/test/injector/injector.spec.ts
This feature displays the found dependency names when any unknown
dependency is getting injected. Before this feature the error message
gets displayed like (?, +). After this implementation, like this e.g.
(?, CatsService).
```
[ ] Bugfix
[x] Feature
```
Issue Number: #223
```
[ ] Yes
[x] No
```
> feature(@nestjs/core) display known dependency names in unknown dependency exception

- packages/core/nest-factory.ts
```
[ ] Bugfix
[ ] Feature
[X] Refactoring (no functional changes, no api changes)
```
This PR just updates the NestFactory.create method signature, decreasing the number of signatures from six to four.
Issue Number: #876 
No change in behavior or API, just more maintainable.
```
[ ] Yes
[X] No
```
> refactor(): reduce complexity of NestFactory.create signature

- packages/common/utils/random-string-generator.util.ts
- packages/core/scanner.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> bugfix(@nestjs/core) enable dynamic modules recursive imports #671

- packages/common/decorators/core/component.decorator.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> bugfix(@nestjs/common) fix mixin testing issue #854

- packages/core/scanner.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> bugfix(@nestjs/core) inherited metadata is not applied #879

- packages/common/decorators/core/catch.decorator.ts
- packages/common/decorators/core/inject.decorator.ts
- packages/common/decorators/core/reflect-metadata.decorator.ts
- packages/common/test/decorators/catch.decorator.spec.ts
- sample/01-cats-app/src/cats/cats.controller.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[ ] No
```
>  enhancement(@nestjs/common) add validation to @catch() decorator

- packages/common/decorators/http/create-route-param-metadata.decorator.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> bugfix(@nestjs/common) data parameter is not required (custom decorators)

- sample/15-mvc/src/main.ts
```
[x] Bugfix
[ ] Feature
[] Code style update (formatting, local variables)
```
Path is joint incorrectly
Path is resolved correctly
```
[ ] Yes
[x] No
```
> Fix path.join arguments seperation

- packages/common/interfaces/nest-application-context.interface.ts
- packages/core/nest-application-context.ts
- packages/core/nest-factory.ts
```
[ ] Bugfix
[ ] Feature
```
Issue Number: 926
```
[ ] Yes
[ ] No
```
> feature(@nestjs/core) add useLogger() to Nest context #926

- packages/common/interceptors/file-fields.interceptor.ts
- packages/common/interceptors/files.interceptor.ts
- sample/15-mvc/src/app.controller.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #935 
```
[ ] Yes
[ ] No
```
> bugfix(@nestjs/common) fix multiple file interceptors issue

- packages/common/pipes/validation.pipe.ts
- packages/core/exceptions/exceptions-handler.ts
- packages/core/helpers/external-context-creator.ts
- packages/microservices/exceptions/rpc-exceptions-handler.ts
- packages/websockets/exceptions/ws-exceptions-handler.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> refactor: use some method

- integration/microservices/e2e/sum-nats.spec.ts
- integration/microservices/src/nats/nats-broadcast.controller.ts
- integration/microservices/src/nats/nats.controller.ts
- packages/common/services/logger.service.ts
- packages/microservices/client/client-mqtt.ts
- packages/microservices/client/client-nats.ts
- packages/microservices/client/client-proxy.ts
- packages/microservices/client/client-redis.ts
- packages/microservices/server/server-nats.ts
- packages/microservices/server/server.ts
- packages/microservices/test/client/client-mqtt.spec.ts
- packages/microservices/test/client/client-nats.spec.ts
- packages/microservices/test/client/client-redis.spec.ts
- packages/microservices/test/server/server-nats.spec.ts
- sample/01-cats-app/src/cats/cats.controller.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> bugfix(@nestjs/microservices) fix nats wildcards

- package-lock.json
- package.json
- packages/microservices/client/client-grpc.ts
- packages/microservices/interfaces/microservice-configuration.interface.ts
- packages/microservices/server/server-grpc.ts
- packages/microservices/test/client/test.proto
- sample/04-grpc/package-lock.json
- sample/04-grpc/package.json
```
[ ] Bugfix
[x] Feature
```
unable to open a proto file with options
possibility to open a proto with options
```
[ ] Yes
[x] No
```
`grpc.load` is deprecated https://github.com/grpc/grpc-node/blob/master/packages/grpc-native-core/index.js#L153
it is better to use [gRPC Protobuf Loader](https://github.com/grpc/grpc-node/blob/master/packages/grpc-protobufjs/README.md)
> feature(@nestjs/microservices) load proto with proto-loader

- packages/core/adapters/fastify-adapter.ts
- packages/core/router/router-explorer.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> bugfix(@nestjs/core) middleware wildcard is not working with fastify

- sample/19-auth/package-lock.json
- sample/19-auth/package.json
```
[x] Bugfix
[ ] Feature
```
Sample code in `sample/19-auth` fails to run after `npm install` because `@nestjs/jwt` package is missing from the dependency list in `package.json`.
`@nestjs/jwt` has been addedd to `package.json` and now the code runs correctly.
```
[ ] Yes
[x] No
```
> add @nestjs/jwt to auth sample dependencies

- packages/core/guards/guards-consumer.ts
- packages/core/helpers/external-context-creator.ts
- packages/core/pipes/pipes-consumer.ts
- packages/core/router/router-response-controller.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> refactor: unnecessary instanceOf Promise deletion

- sample/12-graphql-apollo/package.json
- sample/12-graphql-apollo/src/app.module.ts
Update GraphQL example
```
[x] Bugfix
[ ] Feature
```
The subscriptions are not working in the current GraphQL example. 
Issue Number: https://github.com/nestjs/graphql/issues/51
```
[ ] Yes
[x] No
```
> Update GraphQL example

- Readme.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> Add An logo to Readme

- integration/injector/e2e/default-values.spec.ts
- integration/injector/src/defaults/core.service.ts
- integration/injector/src/defaults/defaults.module.ts
- integration/injector/src/defaults/defaults.service.ts
- packages/core/injector/injector.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #1150 
Fixed
```
[ ] Yes
[ ] No
```
> bugfix(core) make use of default assignments (DI)

- .travis.yml
- packages/core/injector/module-token-factory.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> build add lint for travis build

- .gitattributes
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
https://medium.com/@clarkbw/managing-generated-files-in-github-1f1989c09dfd
> build: hide package lock during a PR

- packages/common/interfaces/abstract.interface.ts
- packages/common/interfaces/index.ts
- packages/common/interfaces/modules/module-metadata.interface.ts
```
[ ] Bugfix
[x] Feature
```
Accept export Abstract class in the @Module
```
@Module({
providers: [
{
provide: MyAbstractFooClass,
useValue: new MyImplFooClass(),
},
],
exports: [
MyAbstractFooClass,
],
```
```
[ ] Yes
[x] No
```
> feature(common): accept export abstract class

- packages/common/package.json
```
[ ] Bugfix
[ ] Feature
```
Package update
Issue Number: #1078 
```
[ ] Yes
[ ] No
```
> feature(common) update axios dependency

- readme_zh.md
Chinese developers are growing, and in order to allow Chinese developers to communicate and share with each other, I have established a communication group.
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: add communication groups for Chinese developers in readme_zh
```
```
[ ] Yes
[x] No
```
> Add communication groups for Chinese developers

- packages/common/utils/shared.utils.ts
- packages/core/injector/module.ts
Closes #1246
```
[x] Bugfix
[ ] Feature
```
Issue Number: #1246
Symbol token can be used in the exports section as well as the string token
```
[ ] Yes
[x] No
```
> fix(core/common): allow to use symbol token in the module exports

- packages/core/injector/injector.ts
- packages/core/test/injector/injector.spec.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #928 
```
[ ] Yes
[x] No
```
> bugfix(core) use direct class instance

- packages/common/cache/interceptors/cache.interceptor.ts
- packages/core/exceptions/base-exception-filter.ts
- packages/core/exceptions/exceptions-handler.ts
```
[x] Bugfix
[ ] Feature
[x] Other... Please describe: improvement
```
Issue Number: #1160 
```
[ ] Yes
[x] No
```
> improvement(core) use application ref host instead of http ref

- packages/common/index.ts
- packages/common/interfaces/external/validation-error.interface.ts
- packages/common/interfaces/index.ts
- packages/common/pipes/validation.pipe.ts
```
[ ] Bugfix
[x] Feature
```
Issue Number: #1267 
```typescript
new ValidationPipe({
exceptionFactory: (errors: ValidationError[]) => 
new BadRequestException('Validation error'),
}),
```
```
[ ] Yes
[x] No
```
> feature(common) add validation error factory (ValidationPipe)

- integration/microservices/e2e/sum-nats.spec.ts
- integration/microservices/src/nats/nats.controller.ts
- integration/websockets/e2e/error-gateway.spec.ts
- integration/websockets/src/error.gateway.ts
- packages/microservices/context/rpc-proxy.ts
- packages/microservices/test/context/rpc-proxy.spec.ts
- packages/websockets/context/ws-proxy.ts
- packages/websockets/test/context/ws-proxy.spec.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #1285
```
[ ] Yes
[x] No
```
> bugfix(ws/microservices): add catchError() to observables

- packages/common/decorators/core/inject.decorator.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #1338 
```
[ ] Yes
[x] No
```
> bugfix(common) invalid metadata inheritance with custom providers

- packages/common/utils/http-exception-body.util.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #1339 
```
[ ] Yes
[x] No
```
> bugfix(common): custom exception body #1339

- packages/microservices/client/client-grpc.ts
- packages/microservices/constants.ts
- packages/microservices/interfaces/microservice-configuration.interface.ts
- packages/microservices/server/server-grpc.ts
```
[ ] Bugfix
[x] Feature
```
Issue Number: #1269
You will be able to use another proto-loader
```
[ ] Yes
[x] No
```
> feat(grpc): added option for proto-loader

- Readme.md
```
[ ] Bugfix
[ ] Feature
```
No discord badge in the README
Issue Number: #891 
Added Discord badge to the README
```
[ ] Yes
[x] No
```
> chore: add discord badge to README.md

- sample/06-mongoose/src/cats/cats.controller.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> Creation behavior should await

- integration/hooks/.gitignore
- integration/hooks/e2e/on-app-boostrap.spec.ts
- integration/hooks/e2e/on-app-shutdown.spec.ts
- integration/hooks/e2e/on-module-destroy.spec.ts
- integration/hooks/e2e/on-module-init.spec.ts
- integration/hooks/package.json
- integration/hooks/tsconfig.json
- integration/hooks/tslint.json
- package-lock.json
- packages/common/index.ts
- packages/common/interfaces/index.ts
- packages/common/interfaces/on-application-shutdown.interface.ts
- packages/core/constants.ts
- packages/core/hooks/index.ts
- packages/core/hooks/on-app-bootstrap.hook.ts
- packages/core/hooks/on-app-shutdown.hook.ts
- packages/core/hooks/on-module-destroy.hook.ts
- packages/core/hooks/on-module-init.hook.ts
- packages/core/injector/instance-trancient.ts
- packages/core/nest-application-context.ts
- packages/core/nest-application.ts
```
[ ] Bugfix
[ ] Feature
```
At the moment the `nest-application-context.ts` is kind of bloated with lifecycle hooks. They can be easily refactored into dedicated files `packages/core/hooks/*.hook.ts`.
Related issue #1417 
The hooks are being refactored in a dedicated file per lifecycle hook (e.g. `on-module-init.hook.ts`).
```
[ ] Yes
[x] No
```
I have not finished the PR yet. I want to get first some feedback before I continue. So please feel free to comment if this PR is in the alignment of the …
> [next] refactor/lifecycle hooks

- packages/core/interceptors/interceptors-consumer.ts
```
[*] Bugfix
[ ] Feature
```
```
[ ] Yes
[*] No
```
> bugfix(core) Interceptors toPromise is break Observable stream

- packages/microservices/client/client-rmq.ts
- packages/microservices/client/constants.ts
…ect one)
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> bugfix(microservices): remove reply_queue in rabbitmq client

- package-lock.json
- package.json
```
[X] Build related changes
```
Several test/linting dependencies were updated, new husky configuration syntax is used
```
[X] No
```
> build(test/linting) update test/linting dependencies

- packages/common/test/utils/http-exception-body.util.spec.ts
- packages/common/utils/http-exception-body.util.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #1622 
```
[ ] Yes
[x] No
```
> bugfix(common): prevent exception body override if message is an array

- packages/core/nest-factory.ts
```
[ ] Bugfix
[ ] Feature
```
Issue Number: #1690
```
[ ] Yes
[ ] No
```
> bugfix(core): invalid context object (proxy) #1690

- LICENSE
```
```
Update License to include updated year
> chore(license): update license date

- package-lock.json
- package.json
> Revert "chore(deps): update dependency mocha to v6"

- Readme.md
```
```
Update documents to use target="_blank"
> docs(readme): update links to open in new window

- packages/common/index.ts
- packages/common/interfaces/modules/provider.interface.ts
- packages/core/scanner.ts
```
[ ] Bugfix
[] Feature
```
```
[ ] Yes
[x] No
```
same thing https://github.com/nestjs/nest/pull/1208
> feat(common): accept provide abstract class

- packages/microservices/client/client-tcp.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #1839
Send data properly on ClientPorxy `emit` method
```
[ ] Yes
[x] No
```
> fix dispatchEvent

- integration/docker-compose.yml
- sample/01-cats-app/e2e/jest-e2e.json
- sample/01-cats-app/jest.json
- sample/01-cats-app/package-lock.json
- sample/01-cats-app/src/cats/cats.controller.spec.ts
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: Fix tests in sample
```
```
[ ] Yes
[x] No
```
> Fix Tests in Sample 1

- packages/platform-fastify/adapters/fastify-adapter.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number:  #1867 
```
[ ] Yes
[ ] No
```
> fix(fastify):  fix the fastify adapter cors options  config

- packages/common/exceptions/http.exception.ts
- packages/common/test/exceptions/http.exception.spec.ts
```
[x] Bugfix
[ ] Feature
```
In this PR was introduced BC and released as patch version: https://github.com/nestjs/nest/commit/ca62dc951d234864b989093e535a82156988ca28#diff-7df9268bccefc4018a65350f53ddcc5c
Taking back the original behavior and introducing the unit test for it
It is fixing the BC
> bugfix(common): fix breaking change on http exception

- renovate.json
```
[ ] Bugfix
[ ] Feature
[x ] CI related changes
```
like : `Update dependency rxjs to v6.5.2 `
like `chore(deps): update dependency typescript to ~3.4.5 `
> chore(renovate):  use semanticCommits

- CONTRIBUTING.md
> bugfix(@nestjs/nest): Update gitter URL in CONTRIBUTING.md

- packages/common/interfaces/nest-application-context.interface.ts
- packages/core/nest-application-context.ts
- packages/core/nest-application.ts
- packages/microservices/nest-microservice.ts
```
[ ] Bugfix
[x] Feature
```
`init` function is not exposed on `NestApplicationContext` 
Issue Number: #1592 
Exposed `init` function on `NestApplicationContext`.
```
[ ] Yes
[x] No
```
> feat(@nestjs/core): Add init function on NestApplicationContext to API

- package-lock.json
- package.json
- packages/core/package.json
In v0.2.2 it is now possible to suppress the opencollective message
properly with multiple kinds of environment variables.
Fixes #2264
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> bugfix(core): Upgrade opencollective dependency

- packages/common/interfaces/external/class-transform-options.interface.ts
```
[ ] Bugfix
[x] Feature
```
Issue Number: #2253
```
[ ] Yes
[x] No
```
> class-transformer enableImplicitConversion flag added

- packages/common/interfaces/modules/provider.interface.ts
- packages/core/injector/module.ts
- packages/core/scanner.ts
- packages/core/test/injector/module.spec.ts
```
[ ] Bugfix
[x] Feature
```
Issue Number: 2415
```
[ ] Yes
[x] No
```
> feat(@nestjs/core): support `useExisting` provider #2415

- integration/injector/e2e/core-injectables.spec.ts
- integration/injector/src/core-injectables/core-injectables.module.ts
- packages/core/index.ts
- packages/core/injector/module.ts
```
[ ] Bugfix
[x] Feature
```
Issue Number: #2410 
- Provides `ApplicationConfig` as core injectable
```ts
const applicationConfig = module.get<ApplicationConfig>(
ApplicationConfig,
);
```
- Add integration test cases for core injectables
- ApplicationConfig
- ModuleRef
- Module as provider
- **Exposes `ApplicationConfig` to the public API**
```
[ ] Yes
[x] No
```
> Add application config as core injectable

- sample/11-swagger/package.json
fix The "swagger-ui-express" package is missing.
> The "swagger-ui-express" package is missing.

- .travis.yml
- integration/graphql/tsconfig.json
- package.json
```
[ ] Bugfix
[ ] Feature
```
- Adds Travis Job Stages
- Speeds up (non-integration-)tests by ~0-20 secs. (thanks to running Lint in parallel)
- Adds integration test to build job
- Fixes integration test using path like `integration/*/node_modules/**/e2e/*.spec.ts`
**Overall build increased by  ~2-3 minutes due to integration tests.** But I think it is still worth it.
```
[ ] Yes
[x] No
```
I would love to further improve the maintainability. How about building (and test if present) all the samples? …
> Run integration tests with TravisCI

- Readme.md
- readme_zh.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
Lets finally deprecate Gitter :)
> chore(): Remove Gitter badge

- packages/common/decorators/modules/module.decorator.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> refactor: module decorator

- sample/24-serve-static/.gitignore
- sample/24-serve-static/client/index.html
- sample/24-serve-static/package-lock.json
- sample/24-serve-static/package.json
- sample/24-serve-static/src/app.module.ts
- sample/24-serve-static/src/main.ts
- sample/24-serve-static/tsconfig.build.json
- sample/24-serve-static/tsconfig.json
- sample/24-serve-static/tslint.json
```
[ ] Bugfix
[ ] Feature
```
Sample of the new [@nestjs/serve-static](https://www.npmjs.com/package/@nestjs/serve-static) package.
```
[ ] Yes
[X] No
```
> docs(sample): add sample for @nestjs/serve-static

- .travis.yml
- gulpfile.js
- integration/microservices/e2e/sum-mqtt.spec.ts
- package-lock.json
- package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> ci(): Try to fix flaky CI tests

- sample/19-auth-jwt/src/app.controller.spec.ts
- sample/19-auth-jwt/src/app.service.spec.ts
- sample/19-auth-jwt/src/auth/auth.service.spec.ts
```
[x] Bugfix
[x] Feature
```
Unit tests fail.
Unit tests pass.
```
[ ] Yes
[x] No
```
> auth jwt sample Fix test cases

- sample/07-sequelize/docker-compose.yml
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: Sample fix
```
```
[ ] Yes
[x] No
```
> chore(samples): fix docker compose duplicate key

- packages/core/errors/exceptions/unknown-element.exception.ts
- packages/core/injector/container-scanner.ts
providing the element name would help you pin-point your missing provider quicker
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> refactor(core): more descriptive unknown element exception

- sample/25-dynamic-modules/.gitignore
- sample/25-dynamic-modules/.prettierrc
- sample/25-dynamic-modules/README.md
- sample/25-dynamic-modules/config/development.env
- sample/25-dynamic-modules/nest-cli.json
- sample/25-dynamic-modules/package-lock.json
- sample/25-dynamic-modules/package.json
- sample/25-dynamic-modules/src/app.controller.spec.ts
- sample/25-dynamic-modules/src/app.controller.ts
- sample/25-dynamic-modules/src/app.module.ts
- sample/25-dynamic-modules/src/app.service.ts
- sample/25-dynamic-modules/src/config/config.module.ts
- sample/25-dynamic-modules/src/config/config.service.spec.ts
- sample/25-dynamic-modules/src/config/config.service.ts
- sample/25-dynamic-modules/src/config/constants.ts
- sample/25-dynamic-modules/src/config/interfaces/config-options.interface.ts
- sample/25-dynamic-modules/src/config/interfaces/envconfig.interface.ts
- sample/25-dynamic-modules/src/config/interfaces/index.ts
- sample/25-dynamic-modules/src/main.ts
- sample/25-dynamic-modules/tsconfig.build.json
- sample/25-dynamic-modules/tsconfig.json
- sample/25-dynamic-modules/tslint.json
@kamilmysliwiec 25-dynamic-modules sample to go with new Dynamic modules chapter @nestjs/docs.nestjs.com#657
> docs(samples) add 25-dynamic-modules

- sample/01-cats-app/src/common/pipes/parse-int.pipe.ts
combine multiple imports from '@nestjs/common' into one.
- [] Tests for the changes have been added (for bug fixes / features)
- [] Docs have been added / updated (for bug fixes / features)
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> Combine multiple imports from the same module

- readme_zh.md
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: docs
```
```
[ ] Yes
[x] No
```
> docs: fix broken link

- packages/common/index.ts
- packages/common/interfaces/index.ts
```
[ ] Bugfix
[ ] Feature
```
The NestApplicationOptions interface is exported from @nestjs/common index
```
[ ] Yes
[x] No
```
> refactor(common) export NestApplicationOptions interface from index

- packages/microservices/client/client-grpc.ts
- packages/microservices/interfaces/client-grpc.interface.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(microservices) add getClientByServiceName to client grpc

- .circleci/config.yml
- tools/benchmarks/check-benchmarks.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> Fix codechecks benchmarks

- packages/core/services/reflector.service.ts
- packages/core/test/services/reflector.service.spec.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(core) add more utility reflector methods

- packages/common/interfaces/features/arguments-host.interface.ts
- packages/core/helpers/execution-context-host.ts
- packages/core/test/helpers/execution-context-host.spec.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(core) add getContext to RpcArgumentsHost

- .circleci/config.yml
- .commitlintrc.json
- package-lock.json
- package.json
```
[ ] Bugfix
[ ] Feature
[x] CI related changes
```
We have established some commit guidelines - though a lot of folks have a hard time following those rules. Thanks to this PR you'll get reminded for every commit message that we have these rules established (git hooks)
`commitlint` checks the commit message with `husky`. If this commit does not follow the Angular commit style guide, you won't be able to commit your changes locally.
If a PR gets added through the user interface or any other way, whilst disregarding the git …
> ci(): Lint commit messages

- packages/common/interfaces/external/class-transform-options.interface.ts
```
[ ] Bugfix
[X] Feature
```
Issue Number: #3274
Added `excludeExtraneousValues` flag to interface `ClassTransformOptions`. That flag was introduced in recent `class-transformer` version
```
[ ] Yes
[X] No
```
> feat(common): Added class-transformer excludeExtraneousValues flag

- packages/core/injector/module-token-factory.ts
- packages/core/test/injector/module-token-factory.spec.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #3362
```
[ ] Yes
[x] No
```
> fix(core): use module class to generate hash instead of name

- integration/scopes/e2e/inject-inquirer.spec.ts
- integration/scopes/src/inject-inquirer/hello-request/hello-request.service.ts
- integration/scopes/src/inject-inquirer/hello-request/request-logger.service.ts
- integration/scopes/src/inject-inquirer/hello-transient/hello-transient.service.ts
- integration/scopes/src/inject-inquirer/hello-transient/transient-logger.service.ts
- integration/scopes/src/inject-inquirer/hello.controller.ts
- integration/scopes/src/inject-inquirer/hello.module.ts
- packages/common/services/logger.service.ts
- packages/core/injector/index.ts
- packages/core/injector/injector.ts
- packages/core/injector/inquirer/index.ts
- packages/core/injector/inquirer/inquirer-constants.ts
- packages/core/injector/inquirer/inquirer-providers.ts
- packages/core/injector/internal-core-module.ts
- packages/core/injector/module-token-factory.ts
- packages/core/test/injector/module-token-factory.spec.ts
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: Release
```
```
[ ] Yes
[x] No
```
> chore(): 6.10.0 minor release

- packages/websockets/decorators/socket-gateway.decorator.ts
- packages/websockets/interfaces/gateway-metadata.interface.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(websockets): add missing options, improve comments, add generic

- packages/common/services/logger.service.ts
There were no existing tests, so I did not have any template to go by for adding a new test.
```
[ ] Bugfix
[x] Feature
```
Add a `setContext()` method to the `Logger` class.
```
[ ] Yes
[x] No
```
> feat(logger): Add setContext method

- packages/core/test/router/router-response-controller.spec.ts
change as toPromise returns a promise with the last value
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> test(core): change observable to have multiple values

- packages/websockets/test/web-sockets-controller.spec.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> test(websockets): fix expect that does not execute

- packages/microservices/test/exceptions/rpc-exceptions-handler.spec.ts
- packages/microservices/test/server/server-rmq.spec.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> test(microservices): fix expect that does not execute

- packages/core/test/exceptions/external-exceptions-handler.spec.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> test(core): fix expect that does not execute

- packages/common/test/utils/random-string-generator.util.spec.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> test(common): fix expect that does not execute

- packages/core/test/helpers/external-context-creator.spec.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> test(core): fix expectation in catch

- packages/common/test/decorators/cache.decorator.spec.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> test(common): remove unnecessary logical and

- packages/core/test/router/router-execution-context.spec.ts
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: test correction
```
```
[ ] Yes
[x] No
```
> test(core): correct expectation in catch

- packages/core/test/interceptors/interceptors-consumer.spec.ts
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: Missing test
```
```
[ ] Yes
[x] No
```
> test(core): add missing test

- packages/common/test/decorators/use-interceptors.decorator.spec.ts
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: Missing test
```
```
[ ] Yes
[x] No
```
> test(common): add missing test

- packages/core/test/router/router-execution-context.spec.ts
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: test correction
```
```
[ ] Yes
[x] No
```
> test(core): correct not awaiting promises

- packages/core/test/router/router-execution-context.spec.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> test(core): remove unnecessary stub

- packages/common/test/decorators/use-interceptors.decorator.spec.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> test(common): correct expectation in catch

- packages/core/router/router-execution-context.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> refactor(core): change return type annotation to be exact

- packages/common/interfaces/external/kafka-options.interface.ts
- packages/microservices/external/kafka.interface.ts
```
[x] Bugfix
[ ] Feature
```
Support ssl:true for KafkaConfig options
```
[ ] Yes
[x] No
```
> add boolean on KafkaConfig interface for easily support ssl

- integration/injector/e2e/property-injection.spec.ts
- integration/injector/src/properties/properties.module.ts
- integration/injector/src/properties/properties.service.ts
- packages/core/errors/messages.ts
- packages/core/injector/injector.ts
```
[x] Bugfix
[ ] Feature
```
Instead of UnknownDependenciesException, Symbol to string conversion error is thrown.
Issue Number: #3649 
Also mentioned here: #2260
UnknownDependenciesException is thrown instead of Symbol conversion error.
```
[ ] Yes
[x] No
```
This is my first contribution to this project, code review and quality assurance check will be appreciated!
> Fix unknown dependency exception

- packages/common/constants.ts
- packages/common/decorators/core/controller.decorator.ts
- packages/core/router/router-explorer.ts
> Revert "feat(common/core): Added useGlobalPrefix option for Controllers"

- integration/docker-compose.yml
- packages/core/hooks/on-app-bootstrap.hook.ts
- packages/core/hooks/on-app-shutdown.hook.ts
- packages/core/hooks/on-module-destroy.hook.ts
- packages/core/hooks/on-module-init.hook.ts
- packages/core/injector/module.ts
- packages/core/middleware/container.ts
- packages/core/nest-application.ts
- packages/core/test/middleware/container.spec.ts
- packages/core/test/middleware/middleware-module.spec.ts
- packages/core/test/middleware/resolver.spec.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(core): fix lifecycle hooks for middleware, injectables

- packages/common/decorators/core/set-metadata.decorator.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(core): add key to custom decorator type

- packages/common/http/http.service.ts
```
[*] Feature
```
```
[ ] Yes
[*] No
```
use case:
```
this.httpService.request(...).pipe(timeout(1000))
```
we can then cancel this request upon timeout, saving a little bit of resource, and stop axios interceptors processing the timed-out response.
> Feature PR: Add request cancellation to http service

- sample/22-graphql-prisma/database/datamodel.graphql
- sample/22-graphql-prisma/src/graphql.options.ts
- sample/22-graphql-prisma/src/graphql.schema.d.ts
- sample/22-graphql-prisma/src/prisma/prisma-types.graphql
```
[x ] Bugfix
[ ] Feature
```
Sample app is not starting. Seems that prisma has been updated and requires @id decorator.
Because of those decorators if we try to use prisma file in our app it will crash as decorators are not recognized. Thus only generated typepaths sholuld be used ` typePaths: ['./src/**/*.graphql'],`
Sample works :)
```
[ ] Yes
[x ] No
```
> update broken prisma sample

- integration/microservices/e2e/orders-grpc.spec.ts
- integration/microservices/src/grpc-advanced/advanced.grpc.controller.ts
- packages/microservices/client/client-grpc.ts
- packages/microservices/test/client/client-grpc.spec.ts
- packages/microservices/test/server/server-grpc.spec.ts
- sample/04-grpc/src/hero/hero.controller.ts
- sample/04-grpc/src/hero/hero.module.ts
- sample/04-grpc/src/hero/hero.proto
```
[ ] Bugfix
[x] Feature
```
Issue Number: https://github.com/nestjs/nest/issues/3906
```
[ ] Yes
[x] No
```
> feat(microservices): support passing upstream subject to grpc client

- packages/core/router/router-response-controller.ts
- packages/core/test/router/router-response-controller.spec.ts
also add missing tests for redirection
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(core): correct redirect decorator metadata interface

- CONTRIBUTING.md
- packages/common/exceptions/service-unavailable.exception.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> Fixed two typos in the docs

- packages/common/test/decorators/apply-decorators.spec.ts
```
[ ] Bugfix
[ ] Feature
```
Issue Number: #4039 
```
[ ] Yes
[x] No
```
> test(common): test for apply decorators for static properties

- packages/core/router/router-execution-context.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #3305
```
[ ] Yes
[ ] No
```
> bugfix(core): fix redirect decorator to handle empty strings

- integration/nest-application/get-url/package-lock.json
- integration/nest-application/get-url/package.json
```
[ ] Bugfix
[ ] Feature
```
`error TS2694: Namespace '"net"' has no exported member 'AddressInfo'` from utils.ts
Resolved the above error.
```
[ ] Yes
[ ] No
```
> chore(get-url): update @types/node

- packages/microservices/constants.ts
- packages/microservices/server/server-mqtt.ts
- packages/microservices/server/server.ts
- packages/microservices/test/server/server-mqtt.spec.ts
```
[ ] Bugfix
[x] Feature
```
Issue Number: #2948
Add wildcard support for MQTT topics and return related handlers
```
[ ] Yes
[x] No
```
> feat(microservices) add matchMqttPattern to server mqtt

- packages/common/exceptions/http-version-not-supported.exception.ts
```
[ ] Bugfix
[x] Feature
```
Adding HTTP Version Not Supported response exception indicating that the HTTP version used in the request is not supported by the server.
```
[ ] Yes
[x] No
```
> feat(common): add http version not supported exception

- packages/common/pipes/validation.pipe.ts
- packages/common/test/pipes/validation.pipe.spec.ts
```
[ ] Bugfix
[x] Feature
```
When `transform` is enabled (`ValidationPipe`), detect the primitive types (number/boolean) and parse to appropriate types for `@Query` and `@Param()`.
```
[x] Yes
[ ] No
```
> feat(common): transform primitives (number, bool) with validation pipe

- packages/common/pipes/validation.pipe.ts
- packages/common/test/pipes/validation.pipe.spec.ts
> Revert "feat(common): transform primitives (number, bool) with validation pipe"

- packages/common/pipes/index.ts
- packages/common/pipes/parse-array.pipe.ts
- packages/common/pipes/parse-bool.pipe.ts
- packages/common/test/pipes/parse-array.pipe.spec.ts
- packages/common/test/pipes/parse-bool.pipe.spec.ts
```
[ ] Bugfix
[x] Feature
```
`ParseBoolPipe` and `ParseArrayPipe`
```
[ ] Yes
[x] No
```
> feat(common): add parse bool pipe and parse array pipe

- integration/graphql-code-first/e2e/pipes.spec.ts
- integration/hello-world/e2e/fastify-adapter.spec.ts
- packages/common/exceptions/http.exception.ts
- packages/common/test/exceptions/http.exception.spec.ts
- packages/core/test/router/router-execution-context.spec.ts
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: Enhancement
```
```
[x] Yes
[ ] No
```
> refactor(core) make message property (http errors) serializable

- packages/microservices/client/client-grpc.ts
- packages/microservices/interfaces/microservice-configuration.interface.ts
https://github.com/nestjs/nest/issues/4094
https://github.com/grpc/grpc/blob/master/doc/keepalive.md
> feat(microservices): Add keepalive option in grpc clinet

- packages/microservices/client/client-grpc.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #4203 
```
[ ] Yes
[x] No
```
> fix(microservices): fix sending metadata with grpc streaming

- packages/common/decorators/core/dependencies.decorator.ts
```
[ ] Bugfix
[ ] Feature
```
just a typo fix
```
[ ] Yes
[x] No
```
> fix(common): minor typo fix in dependencies.decorator

- packages/common/pipes/validation.pipe.ts
```
[ ] Bugfix
[x] Feature
```
Validation returns nothing from objects of `ValidationError` if `@ValidateNested()`was used in dto.
<details>
<summary>Old Response</summary>
```json
{
"statusCode": 400,
"message": [
"email must be an email"
],
"error": "Bad Request"
}
```
</details>
Returns flattened children errors
<details>
<summary>New Response</summary>
```json
{
"statusCode": 400,
"message": [
"email must be an email",
"passport issuing_country_code must be a valid ISO31661 Alpha2 code",
"address …
```
> feat(common): add nested validation errors parse

- packages/common/package.json
```
[ ] Bugfix
[ ] Feature
```
Adds a missing dependency to `@nestjs/common` so it doesn't throw an error if used with `@nestjs/core`.
Error: 
```
Error: Cannot find module 'iterare'
@nestjs/common/pipes/validation.pipe.js
@nestjs/common/pipes/parse-array.pipe.js
```
No more error or the need to install the dependency manually if using this package standalone.
```
[ ] Yes
[x] No
```
> chore(common): add missing iterare dependency

- package-lock.json
- package.json
**Removed not used @types package.**
Issue Number: **N/A**
N/A
**No**
> fix(deps): removed kafka-node, since that types is not used

- packages/common/pipes/default-value.pipe.ts
- packages/common/pipes/index.ts
- packages/common/test/pipes/default-value.pipe.spec.ts
```
[ ] Bugfix
[x] Feature
```
Issue Number: #4590
Described in the related issue
```
[ ] Yes
[x] No
```
> feat(common): add a default-value pipe

- packages/core/errors/exceptions/invalid-module.exception.ts
- packages/core/errors/exceptions/undefined-forwardref.exception.ts
- packages/core/errors/exceptions/undefined-module.exception.ts
- packages/core/errors/messages.ts
- packages/core/injector/container.ts
- packages/core/scanner.ts
- packages/core/test/errors/test/messages.spec.ts
- packages/core/test/scanner.spec.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #4586
```
[ ] Yes
[x] No
```
> fix(core): improve error message when imported module is nil

- packages/common/index.ts
- packages/common/interfaces/index.ts
- packages/common/interfaces/microservices/nest-hybrid-application-options.interface.ts
- packages/common/interfaces/microservices/nest-hybrid-options.interface.ts
- packages/common/interfaces/nest-application.interface.ts
- packages/core/nest-application.ts
- packages/core/test/nest-application.spec.ts
```
[ ] Bugfix
[x] Feature
```
Issue Number: #4261 
```
app.connectMicroservice(transportOptions, { inheritAppConfig: true });
```
When providing `inheritAppConfig` the hybrid microservice will inherit the global configuration.
allowing use of global interceptor and such
```
[ ] Yes
[x] No
```
> feat(microservice): hybrid microservice can inherit config

- packages/microservices/server/server-rmq.ts
```
[ ] Bugfix
[ ] Feature
Some extra verbosity for debugging reasons. Refactor maybe?
```
When client is disconnected from RMQ server with any reason only `[Server] Disconnected from RMQ. Trying to reconnect.` message is logged.
Full error message is logged to console, like in rmq-client.
```
[ ] Yes
[x] No
```
> refactor(microservices): rmq connection errors are now being logged

- sample/23-graphql-code-first/src/common/scalars/date.scalar.ts
- sample/23-graphql-code-first/src/recipes/dto/recipes.args.ts
```
[ ] Bugfix
[ ] Feature
```
The following lint errors are encountered:
`date.scalar.ts` line 16: `Argument 'ast' should be typed.`
`recipes.args.ts` line 6, 10: `Type number trivially inferred from a number literal, remove type annotation`
No lint errors for those lines.
```
[ ] Yes
[x] No
```
Thanks for Nest Framework! 👍
> sample(graphql): Fix lint errors

- sample/07-sequelize/package-lock.json
- sample/07-sequelize/package.json
> Revert "fix(deps): update dependency sequelize to v6"

- packages/common/index.ts
```
[ ] Bugfix
[ ] Feature
```
The `ModuleMetadata` type is not exported.
The `ModuleMetadata` type is exported.
```
[ ] Yes
[x] No
```
> chore(common): export the ModuleMetadata type

- integration/microservices/e2e/sum-rpc.spec.ts
- integration/microservices/src/app.controller.ts
- integration/microservices/src/app.module.ts
- packages/microservices/module/clients.module.ts
- packages/microservices/module/index.ts
- packages/microservices/module/interfaces/clients-module.interface.ts
- packages/microservices/module/interfaces/index.ts
- packages/microservices/test/module/clients.module.spec.ts
```
[ ] Bugfix
[x] Feature
```
Issue Number: #4040
```
[ ] Yes
[x] No
```
> feat(microservices): ClientsModule.registerAsync

- packages/common/exceptions/index.ts
```
[ ] Bugfix
[x] Feature
```
Export http-version-not-supported.exception 
```
[ ] Yes
[x] No
```
> feat(packages/common/exception): Export http-version-not-supported

- sample/08-webpack/webpack-hmr.config.js
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: sample update
```
Issue Number: https://github.com/nestjs/nest/issues/5068
```
[ ] Yes
[x] No
```
> sample(webpack): update webpack-node-externals option property name

- packages/common/exceptions/index.ts
- packages/common/exceptions/precondition-failed.exception.ts
- packages/common/utils/http-error-by-code.util.ts
closes #5113
Add the precondition failed exception to the common package
```
[ ] Bugfix
[x] Feature
```
Exception is not present
Issue Number: #5113
The exception is there
```
[ ] Yes
[x] No
```
> feat(common): add precondition failed exception

- sample/17-mvc-fastify/package-lock.json
- sample/17-mvc-fastify/package.json
```
[x] Bugfix
[ ] Feature
```
Sample 17-mvc-fastify crash on startup
Issue: https://github.com/nestjs/nest/issues/5167
Issue Number: 5167
Sample 17-mvc-fastify start without any crash
```
[ ] Yes
[x] No
```
> fix(sample): Add missing package fastify-static

- packages/core/injector/container.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(core): add missing await when dynamic modules metadata is stored

- packages/common/exceptions/gateway-timeout.exception.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(docs): corrected spelling mistake in JSDoc

- packages/microservices/test/server/server.spec.ts
fix typo in test
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: typofix
```
```
[ ] Yes
[x] No
```
> test(microservices): fix typo Deffered -> Deferred

- packages/common/test/decorators/use-guards.decorator.spec.ts
```
[ ] Bugfix
[ ] Feature
[x] Tests
```
Some wrong test names
Correct test names 👌 
```
[ ] Yes
[x] No
```
> test: fix guard decorator test names

- packages/microservices/server/server.ts
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: typofix
```
```
[ ] Yes
[x] No
```
> refactor(microservices): typo deffered -> deferred

- packages/core/middleware/middleware-module.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #5612 
```
[ ] Yes
[x] No
```
> fix(core): fix request scoped middleware execution order #5612

- packages/common/pipes/validation.pipe.ts
```
[ ] Bugfix
[ ] Feature
```
Issue Number: #5497 
Any of these methods inside the core validation pipe can't be overwritten when extending the class.
Make every method `protected` rather than `private` to allow the methods to be overwritten.
```
[ ] Yes
[x] No
```
> feat(validation pipe): use protected methods instead of private

- packages/microservices/external/kafka-options.interface.ts
```
[ ] Bugfix
[x] Feature
```
Issue Number: #5442 
https://github.com/nestjs/nest/issues/5442
Updates the consumer configuration options.
```
[ ] Yes
[x] No
```
> feat(microservices): Updates Kafka options interface

- packages/common/interfaces/nest-application-context-options.interface.ts
- packages/core/helpers/rethrow.ts
- packages/core/nest-factory.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> Princechauhan1992 added abort on error in nestapplication context options

- packages/common/package.json
- packages/common/services/logger.service.ts
- packages/common/utils/cli-colors.util.ts
```
[ ] Bugfix
[x] Feature
```
Issue Number: #5469 
```
[ ] Yes
[x] No
```
> feat(common): remove cli-color dependency

- packages/microservices/client/client-rmq.ts
- packages/microservices/external/rmq-url.interface.ts
- packages/microservices/interfaces/microservice-configuration.interface.ts
- packages/microservices/server/server-rmq.ts
```
[ ] Bugfix
[x] Feature
```
Issue Number: 5587
```
[ ] Yes
[x ] No
```
> feature(microservices): update acceptable types in RabbitMq urls

- sample/19-auth-jwt/e2e/app/app.e2e-spec.ts
- sample/19-auth-jwt/e2e/jest-e2e.json
- sample/19-auth-jwt/package.json
- sample/19-auth-jwt/src/users/users.service.spec.ts
```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe:
```
Adds tests for the JWT example, number 19
No tests
Issue Number: #5472 
There's tests!
```
[ ] Yes
[X] No
```
> test(jwt-sample): adds tests to the jwt to show e2e flow works

- sample/28-file-upload/.eslintrc.js
- sample/28-file-upload/.gitignore
- sample/28-file-upload/README.md
- sample/28-file-upload/e2e/app/app.e2e-spec.ts
- sample/28-file-upload/e2e/jest-e2e.json
- sample/28-file-upload/jest.json
- sample/28-file-upload/package-lock.json
- sample/28-file-upload/package.json
- sample/28-file-upload/src/app.controller.ts
- sample/28-file-upload/src/app.module.ts
- sample/28-file-upload/src/app.service.ts
- sample/28-file-upload/src/main.ts
- sample/28-file-upload/src/sample.dto.ts
- sample/28-file-upload/tsconfig.build.json
- sample/28-file-upload/tsconfig.json
```
[ ] Bugfix
[ ] Feature
[X ] Other... Please describe:
```
Samples and tests for file-upload
There's no sample for file-upload
There's a sample for file upload :smile_cat: 
```
[ ] Yes
[X] No
```
> test(file-upload): creates an example and test for file uploading

- packages/core/nest-application-context.ts
```
[ x] Bugfix
[ ] Feature
```
Issue Number: #5669 
Added a non-null assertion to the logger function causing the error
```
[ ] Yes
[x] No
```
> fix: verify err variable is defined in catch block

- packages/core/nest-application-context.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #5586
```
[ ] Yes
[x] No
```
> fix(core): add abstract option to resolve method

- packages/common/pipes/validation.pipe.ts
allow the usage of asychronouse code in exception factory
fixes #5718
```
[ ] Bugfix
[x] Feature
```
Asynchronous Code not possible in custom exceptionFactory in Validation Pipe
Issue Number: #5718 
Asynchronous Code now possible in custom exceptionFactory in Validation Pipe
```
[ ] Yes
[x] No
```
> feat(common): await for exception factory in validation pipe

- packages/core/test/injector/instance-wrapper.spec.ts
```
[ ] Bugfix
[ ] Feature
[ v ] Code style update (formatting, local variables)
```
```
[ ] Yes
[ v ] No
```
> style: typo

- CONTRIBUTING.md
```
[ ] Bugfix
[ ] Feature
```
N/A
```
[ ] Yes
[x] No
```
This PR, update sample for fix
> docs(contribuiting):update sample for fix

- packages/common/enums/http-status.enum.ts
```
[ ] Bugfix
[x] Feature
```
Add  EARLYHINTS status code
```
[ ] Yes
[x] No
```
> feat(packages/common/enums): Add EARLYHINTS status code

- packages/core/scanner.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #5774 
```
[ ] Yes
[x] No
```
> fix(core): await dynamic module imports #5774

- packages/microservices/server/server.ts
A descriptive error message tells user exactly what event pattern is missing a handler.
```
[ ] Bugfix
[x] Feature
```
Issue Number: Fixes #5812
A more descriptive error message. See the discussion on issue.
```
[ ] Yes
[x] No
```
> feat(microservices): log event name w/o handler

- packages/core/nest-factory.ts
- [NA] Tests for the changes have been added (for bug fixes / features)
- [NA] Docs have been added / updated (for bug fixes / features)
```
[x] Bugfix
[ ] Feature
```
method `applyLogger` inside nest-factory.ts method is checking for `logger` attribute existence and not it's passed value.
Issue Number: #5816 
method `applyLogger` inside nest-factory.ts method will now check for `logger` attribute value.
```
[ ] Yes
[X] No
```
> Fix for #5816

- packages/common/services/logger.service.ts
```
[ ] Bugfix
[x] Feature
```
Issue Number: #5952 
Use `stderr` on common logger's error log
```
[ ] Yes
[x] No
```
Reopen of #5961
> feat(common): change error log to use stderr

- packages/microservices/interfaces/microservice-configuration.interface.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(microservices): fix kafka config field typo

- packages/common/serializer/class-serializer.interceptor.ts
```
[ ] Bugfix
[ ] Feature
```
N/A
```
[ ] Yes
[x] No
```
This PR, visibility indicator changed to protected in getContextOptions method
> chore(serializer): changed visibility indicator

- packages/microservices/interfaces/microservice-configuration.interface.ts
```
[ ] Bugfix
[ ] Feature
```
Issue Number:  #6054
N/A
```
[ ] Yes
[x] No
```
This PR, updated nats options
> chore(microservice): updated nats options

- integration/cors/e2e/express.spec.ts
- integration/cors/e2e/fastify.spec.ts
- integration/cors/src/app.controller.ts
- integration/cors/src/app.module.ts
- integration/cors/tsconfig.json
- integration/microservices/src/kafka/kafka.controller.ts
- packages/common/exceptions/http.exception.ts
- packages/common/interfaces/external/cors-options.interface.ts
- packages/common/interfaces/http/http-server.interface.ts
- packages/common/interfaces/nest-application-options.interface.ts
- packages/common/interfaces/nest-application.interface.ts
- packages/core/adapters/http-adapter.ts
- packages/core/application-config.ts
- packages/core/helpers/external-context-creator.ts
- packages/core/nest-application.ts
- packages/microservices/context/rpc-context-creator.ts
- packages/platform-express/adapters/express-adapter.ts
- packages/platform-fastify/adapters/fastify-adapter.ts
- packages/websockets/context/ws-context-creator.ts
- sample/22-graphql-prisma/src/graphql.schema.d.ts
- tools/gulp/tasks/samples.ts
Bump version of the fastify-cors.
Add CorsOptionsDelegate interface.
Add CorsOptionsDelegate as an acceptable type
for every enableCors usage.
Closes #6118
```
[ ] Bugfix
[x] Feature
```
Issue Number: #6118
```
[] Yes
[X] No
```
> feat: allow to config cors async

- integration/hooks/e2e/before-app-shutdown.spec.ts
- integration/hooks/e2e/on-app-boostrap.spec.ts
- integration/hooks/e2e/on-app-shutdown.spec.ts
- integration/hooks/e2e/on-module-destroy.spec.ts
- integration/hooks/e2e/on-module-init.spec.ts
- packages/core/nest-application-context.ts
- packages/core/scanner.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(core): use topological sort for lifecycle hooks

- packages/common/interfaces/nest-application.interface.ts
- packages/common/interfaces/nest-microservice.interface.ts
- packages/core/adapters/http-adapter.ts
- packages/core/middleware/middleware-module.ts
- packages/core/nest-application.ts
- packages/microservices/client/client-mqtt.ts
- packages/microservices/client/client-nats.ts
- packages/microservices/client/client-proxy-factory.ts
- packages/microservices/client/client-redis.ts
- packages/microservices/client/client-tcp.ts
- packages/microservices/client/constants.ts
- packages/microservices/constants.ts
- packages/microservices/interfaces/custom-transport-strategy.interface.ts
- packages/microservices/nest-microservice.ts
- packages/microservices/server/server-grpc.ts
- packages/microservices/server/server-kafka.ts
- packages/microservices/server/server-mqtt.ts
- packages/microservices/server/server-nats.ts
- packages/microservices/server/server-redis.ts
- packages/microservices/server/server-rmq.ts
- packages/microservices/server/server-tcp.ts
- packages/microservices/test/server/server-grpc.spec.ts
- packages/microservices/test/server/server-kafka.spec.ts
- packages/microservices/test/server/server-mqtt.spec.ts
- packages/microservices/test/server/server-nats.spec.ts
- packages/microservices/test/server/server-redis.spec.ts
- packages/microservices/test/server/server-rmq.spec.ts
- packages/microservices/test/server/server-tcp.spec.ts
- sample/03-microservices/src/main.ts
- sample/04-grpc/src/main.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #2777
```
[x] Yes
[ ] No
```
> fix(microservices): reject on error (on listen method call)

- readme_jp.md
Hi. I'm Takuto. A software engineer in Japan with 2 cats.
I'm trying to get nestjs more popular in Japan!
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: create readme for Japanese
```
```
[ ] Yes
[x] No
```
We've started a Japanese user group for NestJS!
I'd like to create Japanese documentation from now on.
Are there any rules for creating documentation?
(The nestjs.jp domain has been acquired!)
> docs(readme): Create Readme for "Japanese"!

- packages/common/interfaces/external/class-transform-options.interface.ts
```
[ ] Bugfix
[ ] Feature
```
Issue Number: #6256
Add option `exposeDefaultValues?: boolean` in `class-transform-options.interface.ts`
```
[ ] Yes
[x] No
```
This PR, update interface for trasform options.  Add option `exposeDefaultValues?: boolean` in `class-transform-options.interface.ts`
> chore(): update interface for transform options 

- sample/19-auth-jwt/src/auth/auth.service.spec.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> test: 💍 add test

- packages/websockets/test/web-sockets-controller.spec.ts
```
[ ] Bugfix
[ ] Feature
```
N/A
```
[ ] Yes
[x] No
```
This PR, fix websockets controller unit tests (see screenshot)
> test(websockets): fix websockets controller unit tests

- packages/microservices/test/client/client-redis.spec.ts
```
[ ] Bugfix
[ ] Feature
```
N/A
```
[ ] Yes
[x] No
```
This PR, change `new Buffer()` in `Buffer.from ` as it is deprecated (see screenshot)
> test(microservice): fix client redis unit tests

- packages/microservices/test/client/client-mqtt.spec.ts
```
[ ] Bugfix
[ ] Feature
```
N/A
```
[ ] Yes
[x] No
```
This PR, change `new Buffer()` in `Buffer.from ` as it is deprecated (see screenshot)
> test(microservice): fix client mqtt unit tests

- packages/common/interfaces/http/http-server.interface.ts
```
[x] Bugfix
[ ] Feature
```
incorrect typings at HttpServer.getRequestUrl at @nestjs/common
6338
getRequestUrl param type changed to TRequest
```
[ ] Yes
[x] No
```
at least at FastifyAdapter we can see:
public getRequestUrl(request: FastifyRequest): string
> HttpServer.getRequestUrl typings fixed

- packages/core/nest-factory.ts
Closes: #6365
```
[x] Bugfix
[ ] Feature
```
Issue Number: #6365
```
[ ] Yes
[x] No
```
> fix(core): app methods chain invocation crash

- sample/30-event-emitter/.eslintrc.js
- sample/30-event-emitter/.gitignore
- sample/30-event-emitter/.prettierrc
- sample/30-event-emitter/nest-cli.json
- sample/30-event-emitter/package-lock.json
- sample/30-event-emitter/package.json
- sample/30-event-emitter/src/app.controller.spec.ts
- sample/30-event-emitter/src/app.controller.ts
- sample/30-event-emitter/src/app.module.ts
- sample/30-event-emitter/src/app.service.ts
- sample/30-event-emitter/src/main.ts
- sample/30-event-emitter/src/orders/dto/create-order.dto.ts
- sample/30-event-emitter/src/orders/entities/order.entity.ts
- sample/30-event-emitter/src/orders/events/order-created.event.ts
- sample/30-event-emitter/src/orders/listeners/order-created.listener.ts
- sample/30-event-emitter/src/orders/orders.controller.ts
- sample/30-event-emitter/src/orders/orders.module.ts
- sample/30-event-emitter/src/orders/orders.service.ts
- sample/30-event-emitter/test/app.e2e-spec.ts
- sample/30-event-emitter/test/jest-e2e.json
- sample/30-event-emitter/tsconfig.build.json
- sample/30-event-emitter/tsconfig.json
```
[ ] Bugfix
[ ] Feature
```
N/A
```
[ ] Yes
[x] No
```
This PR, Added sample for event emitter with nestjs
> chore(sample): Added sample for event emitter with nestjs

- integration/microservices/e2e/sum-kafka.spec.ts
- package.json
- packages/core/exceptions/base-exception-filter.ts
- packages/core/injector/container.ts
- packages/core/injector/index.ts
- packages/core/injector/instance-loader.ts
- packages/core/injector/internal-core-module-factory.ts
- packages/core/injector/internal-core-module.ts
- packages/core/injector/internal-providers-storage.ts
- packages/core/injector/lazy-module-loader.ts
- packages/core/injector/module.ts
- packages/core/middleware/container.ts
- packages/core/nest-application-context.ts
- packages/core/router/router-module.ts
- packages/core/scanner.ts
- packages/core/test/injector/container.spec.ts
- packages/core/test/injector/internal-core-module-factory.spec.ts
- packages/core/test/injector/lazy-module-loader.spec.ts
- packages/core/test/injector/module.spec.ts
- packages/core/test/nest-application.spec.ts
- packages/core/test/scanner.spec.ts
- packages/microservices/ctx-host/tcp.context.ts
```
[ ] Bugfix
[x] Feature
```
Example usage:
```typescript
const { LazyModule } = await import('./lazy.module');
const moduleRef = await this.lazyModuleLoader.load(() => LazyModule);
```
Webpack (to enable code splitting and generate chunks):
```
[ ] Yes
[x] No
```
> feat(core): add lazy module loader class

- sample/30-event-emitter/src/orders/listeners/order-created.listener.ts
```
[ ] Bugfix
[ ] Feature
```
In the EventEmitter example, there isn't Injectable decorator in the `OrderCreatedListener` class.
Added Injectable decorator, so we can inject other injectables to the listener.
```
[ ] Yes
[x] No
```
> chore(sample/30): add Injectable decorator to OrderCreatedListener

- readme_kr.md
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: add korean document
```
add korean document
```
[ ] Yes
[x] No
```
> add korean document

- readme_kr.md
```
[ ] Bugfix
[ ] Feature
[o] Other... Please describe: fix translation error
```
fix translation error
```
[ ] Yes
[o] No
```
> Fix Korean document translation error

- packages/common/pipes/default-value.pipe.ts
- packages/common/pipes/parse-array.pipe.ts
- packages/common/pipes/parse-bool.pipe.ts
- packages/common/pipes/parse-int.pipe.ts
- packages/common/pipes/parse-uuid.pipe.ts
- packages/common/pipes/validation.pipe.ts
```
[ ] Bugfix
[ ] Feature
[X] Refactoring (no functional changes, no api changes)
```
Some pipes had circular dependencies resulting in errors when bundling via rollup
Removed the circular dependencies
```
[ ] Yes
[X] No
```
> refactor(common): Removed circular dependencies in pipes

- Readme.md
- readme_jp.md
- readme_kr.md
Hi.I'm Japanese engineer.
```
[ ] Bugfix
[ ] Feature
[x ] Other... Please describe:add japanese to Getteing started
```
Japanese ReadMe is exist.
But Japanese isn't display at Getting started.
```
[ ] Yes
[x ] No
```
> chore: add japanese to Getteing started

- readme_jp.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
delete unnecessary string.
```
連絡する -> 連絡する
```
> chore: fix readme_jp.md

- packages/microservices/server/server.ts
allow set different logger implementation
```
[ ] Bugfix
[x] Feature
```
Now server's logger is set as `Logger` class instead of `LoggerService` interface.
Now it's possible to change logger to custom implementation.
```
[ ] Yes
[x] No
```
> feat(microservices): change server logger to interface

- package-lock.json
- package.json
> Revert "chore(deps): update dependency markdown-table to v3"

- .mocharc.js
Test script defined in package.json for 'npm run test' specifies that reflect-metadata/Reflect.js
is required by --require switch. This is however insufficient way to require external module
which can be verified by removing first 3 .spec files from test run (by alphabet -
apply-decorators.spec.ts, bind.decorator.spec.ts, cache.decorator.spec.ts) and running
'npm run test'. In such case the error is thrown saying Reflect was not loaded. The reason why
'npm run test' works without this commit is because of very first .spec file that runs which
imports reflect-metadata from common/index.js for the entire test run. Oddly enough the Reflect
has to be imported in both places - via --require switch and in .mocharc.js (alternatively
to .mocharc the root hook can be defined by introducing another …
> chore: added mocha config to properly include Reflect via root hooks

- package-lock.json
- packages/microservices/client/client-kafka.ts
- packages/microservices/helpers/kafka-parser.ts
- packages/microservices/interfaces/microservice-configuration.interface.ts
- packages/microservices/server/server-kafka.ts
- packages/microservices/test/helpers/kafka-parser.spec.ts
```
[ ] Bugfix
[x] Feature
```
Issue Number: #3726 
```
[ ] Yes
[x] No
```
> KafkaParser options to keep binary payloads without utf8 encoding

- sample/01-cats-app/.eslintrc.js
- sample/02-gateways/.eslintrc.js
- sample/03-microservices/.eslintrc.js
- sample/04-grpc/.eslintrc.js
- sample/05-sql-typeorm/.eslintrc.js
- sample/06-mongoose/.eslintrc.js
- sample/07-sequelize/.eslintrc.js
- sample/08-webpack/.eslintrc.js
- sample/10-fastify/.eslintrc.js
- sample/11-swagger/.eslintrc.js
- sample/12-graphql-schema-first/.eslintrc.js
- sample/13-mongo-typeorm/.eslintrc.js
- sample/14-mongoose-base/.eslintrc.js
- sample/15-mvc/.eslintrc.js
- sample/16-gateways-ws/.eslintrc.js
- sample/17-mvc-fastify/.eslintrc.js
- sample/18-context/.eslintrc.js
- sample/19-auth-jwt/.eslintrc.js
- sample/20-cache/.eslintrc.js
- sample/21-serializer/.eslintrc.js
- sample/22-graphql-prisma/.eslintrc.js
- sample/23-graphql-code-first/.eslintrc.js
- sample/24-serve-static/.eslintrc.js
- sample/25-dynamic-modules/.eslintrc.js
- sample/26-queues/.eslintrc.js
- sample/27-scheduling/.eslintrc.js
- sample/28-sse/.eslintrc.js
- sample/29-file-upload/.eslintrc.js
- sample/30-event-emitter/.eslintrc.js
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: fix for lint configuration
```
`npm run lint` fails as of the upgrade of `eslint-config-prettier`.
By following [this change log](https://github.com/prettier/eslint-config-prettier/blob/main/CHANGELOG.md#version-800-2021-02-21), fixing configuration solved the fail of lint command.
```
[ ] Yes
[x] No
```
> chore(sample): fix extends configuration by following upgrade eslint-config-prettier

- packages/platform-express/adapters/express-adapter.ts
> fix(platform-express): only set Content-Type if not done for StramableFiles

- packages/core/injector/injector.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: https://github.com/nestjs/nest/issues/7381
```
[] Yes
[x] No
```
> fix(core): fallback to parent inquirer when transient dep chain #7381

- sample/13-mongo-typeorm/docker-compose.yml
- sample/13-mongo-typeorm/package-lock.json
- sample/13-mongo-typeorm/package.json
Issue Number: [#7799](https://github.com/nestjs/nest/issues/7799)
docker image also set to use mongodb image v3.6
> downgrade mongodb to v3

- integration/versioning/e2e/header-versioning-fastify.spec.ts
- integration/versioning/e2e/media-type-versioning-fastify.spec.ts
- integration/versioning/e2e/uri-versioning-fastify.spec.ts
- packages/common/interfaces/http/http-server.interface.ts
- packages/core/adapters/http-adapter.ts
- packages/core/router/router-explorer.ts
- packages/core/test/router/router-explorer.spec.ts
- packages/platform-express/adapters/express-adapter.ts
- packages/platform-fastify/adapters/fastify-adapter.ts
> fix(platform-fastify): fix versioning (media type and header)

- package-lock.json
- package.json
> Revert "chore(deps-dev): bump typescript from 4.3.5 to 4.4.3"

- packages/common/cache/cache.module.ts
- packages/common/cache/interfaces/cache-module.interface.ts
- packages/core/helpers/external-context-creator.ts
- packages/core/interceptors/interceptors-consumer.ts
- packages/core/pipes/pipes-consumer.ts
- packages/core/test/helpers/external-context-creator.spec.ts
- packages/core/test/interceptors/interceptors-consumer.spec.ts
- packages/core/test/router/router-response-controller.spec.ts
- packages/microservices/test/listeners-controller.spec.ts
- packages/websockets/test/web-sockets-controller.spec.ts
- packages/websockets/web-sockets-controller.ts
> feat(cache): Add cache option isGlobal

- sample/14-mongoose-base/src/database/database.providers.ts
update database providers for mongodb
This PR, update database providers for mongodb(see screenshot)
> sample(14-mongoose): update name database mongodb

- integration/hello-world/e2e/middleware-class.spec.ts
- integration/hello-world/e2e/middleware-fastify.spec.ts
- packages/core/middleware/routes-mapper.ts
- packages/core/test/middleware/builder.spec.ts
- packages/core/test/middleware/routes-mapper.spec.ts
- packages/platform-fastify/adapters/fastify-adapter.ts
```js
@Controller()
export class AppController {
@Get('/')
homepage(): string {
return 'hit /';
}
@Get('/test/app')
username(): string {
return 'hit /test/app';
}
@Get('/:username')
users(): string {
return 'hit /:username';
}
}
```
forRoutes({ path: '/' }, { path: '/test/app' }, { path: '/:username' }) === forRoutes(AppController)
Issue Number: #7737 #8108
forRoutes(AppController) should be equal to [{ path: '/$' }, { path: '/test/app$' }, { path: '/:username$' }]
forRoutes({ path: '/' }, { path: '/test/app' }, { path: '/:username' }) should be not equal to forRoutes(AppController)
> fix(core): middlewareConsumer forRoutes controller

- integration/hello-world/e2e/middleware-class.spec.ts
- integration/hello-world/e2e/middleware-fastify.spec.ts
- packages/core/middleware/routes-mapper.ts
- packages/core/test/middleware/builder.spec.ts
- packages/core/test/middleware/routes-mapper.spec.ts
- packages/platform-fastify/adapters/fastify-adapter.ts
> Revert "fix(core): middlewareConsumer forRoutes controller"

- packages/platform-express/adapters/express-adapter.ts
> fix: ExpressAdapter createMiddlewareFactory

- packages/common/exceptions/im-a-teapot.exception.ts
> Fix typo in ImATeapotException doc :D

- packages/microservices/client/client-grpc.ts
- packages/microservices/interfaces/microservice-configuration.interface.ts
Closes #8457
Issue Number: #8457 
I for now did not add any tests, as it only introduces a new option field and as i did not find the right place to add documentation i could not add the new option field to the documentation.
> feat(microservices): adds packageDefinition option to ClientGrpc

- packages/core/injector/injector.ts
Currently when there is an `undefined` dependency, we just throw an error about `Nest cannot resolve dependency of <provider>. Please make sure "dependency" is available". While we might be aware that this means it's probably a circular dependency, newcomers might not. 
issue: #8555 
We add a log about the fact that the dependency is `undefined` and what the usual causes are.
_Technically_ it's a breaking change cause it's a new log line but as this is during bootstrap and only arises when there's an error it shouldn't be a problem. There's no functionality change
> feat: add a log for undefined dependencies

- .husky/commit-msg
- .husky/pre-commit
- package.json
Husky hooks are not run since the upgrade to v5.
Husky hooks are run again using the new syntax of v5 and up.
See https://typicode.github.io/husky/#/?id=migrate-from-v4-to-v7
> build(common): fix husky scripts

- sample/05-sql-typeorm/package-lock.json
- sample/05-sql-typeorm/package.json
- sample/05-sql-typeorm/src/main.ts
Update dependecie for mysql 8.x: remove package `mysql` and added `mysql2`, because the example does not work due to an error (see screenshot)
This PR, Update dependecie for mysql 8.x: remove package `mysql` and added `mysql2`, because the example does not work due to an error (see screenshot)
> sample(05-sql-typeorm): update dependecie for mysql 8.x and some improvements

- .github/ISSUE_TEMPLATE/Bug_report.yml
- .github/ISSUE_TEMPLATE/Feature_request.yml
- .github/ISSUE_TEMPLATE/Regression.yml
- .github/ISSUE_TEMPLATE/Suggestion_improve_performance.yml
- .github/ISSUE_TEMPLATE/config.yml
- packages/common/test/utils/shared.utils.spec.ts
- packages/core/test/exceptions/exceptions-handler.spec.ts
- packages/core/test/injector/module-token-factory.spec.ts
- packages/core/test/services/reflector.service.spec.ts
https://github.com/nestjs/nest/blob/28516d739df350564eceea546dd1f58b5e9c9800/packages/core/test/exceptions/exceptions-handler.spec.ts#L105-L108
the above test nothing. I've fixed it.
---
I've add links to the FAQ page on GH issue templates. See the results [here](https://github.com/micalevisk/nest/issues/new/choose)
> Minor improvements on issue templates, and add tests to cover few missing cases

- sample/10-fastify/package-lock.json
- sample/10-fastify/package.json
Removed unused dependencies ( dependencies dev `@types/ws`)
This PR, Removed dev `@types/ws` dependency as the use of websockets is not used.
> sample(10-fastify): removed unused dependencies

- sample/17-mvc-fastify/package-lock.json
- sample/17-mvc-fastify/package.json
Removed unused dependencies ( dependencies dev `@types/ws`, `@types/socket.io`, `@types/socket.io-redis`)
This PR, Removed `@types/ws`, `@types/socket.io`, `@types/socket.io-redis` dependencies  dev as the use of websockets is not used.
> sample(17-mvc-fastify): removed unused dependencies

- sample/06-mongoose/src/cats/cats.controller.ts
- sample/06-mongoose/src/cats/cats.service.ts
I was looking at your examples and in the Mongoose category you had no choice but to add and get the information in the database. That's why I added get detailed information with _id and delete it at the same time. This I think is better to make users better aware of the work of Nest + Mongoose
> Add new Feature for Crud Application in Mongoose

- packages/common/decorators/modules/module.decorator.ts
> Removed extra space

- packages/microservices/client/client-mqtt.ts
- packages/microservices/client/client-rmq.ts
Issue Number: https://github.com/nestjs/nest/issues/9272
> fix(microservices): remove options object from packets (rmq and mqtt)

- sample/02-gateways/package.json
> fix(gateways): add the socket.io types dependency

- .gitignore
It convenient for developer who use vscode with remote-container extension. Please see [here](https://code.visualstudio.com/docs/remote/containers).
> chore: add .devcontainer to gitignore

- packages/core/injector/injector.ts
> fix(core): use context module for nested transient providers

- packages/microservices/client/client-tcp.ts
> fix(microservices): tcp client parallel connections issue

- packages/common/utils/cli-colors.util.ts
> Revert "feat(common): do not use colors in CLI if not supported"

- .github/workflows/codeql-analysis.yml
- Enhanced the codeql enhanced security scanning.
https://github.blog/2022-02-17-code-scanning-finds-vulnerabilities-using-machine-learning/
Signed-off-by: naveensrinivasan <172697+naveensrinivasan@users.noreply.github.com>
> Enhanced codeql security scanning

- packages/common/index.ts
- packages/core/index.ts
- packages/microservices/index.ts
- packages/platform-express/index.ts
- packages/platform-fastify/index.ts
- packages/platform-socket.io/index.ts
- packages/platform-ws/index.ts
- packages/testing/index.ts
- packages/websockets/index.ts
> fix(platform-fastify): fix typo

- packages/common/decorators/http/render.decorator.ts
- packages/common/exceptions/bad-gateway.exception.ts
- packages/common/exceptions/bad-request.exception.ts
- packages/common/exceptions/conflict.exception.ts
- packages/common/exceptions/forbidden.exception.ts
- packages/common/exceptions/gateway-timeout.exception.ts
- packages/common/exceptions/gone.exception.ts
- packages/common/exceptions/http-version-not-supported.exception.ts
- packages/common/exceptions/http.exception.ts
- packages/common/exceptions/im-a-teapot.exception.ts
- packages/common/exceptions/internal-server-error.exception.ts
- packages/common/exceptions/method-not-allowed.exception.ts
- packages/common/exceptions/misdirected.exception.ts
- packages/common/exceptions/not-acceptable.exception.ts
- packages/common/exceptions/not-found.exception.ts
- packages/common/exceptions/not-implemented.exception.ts
- packages/common/exceptions/payload-too-large.exception.ts
- packages/common/exceptions/precondition-failed.exception.ts
- packages/common/exceptions/request-timeout.exception.ts
- packages/common/exceptions/service-unavailable.exception.ts
- packages/common/exceptions/unauthorized.exception.ts
- packages/common/exceptions/unprocessable-entity.exception.ts
- packages/common/exceptions/unsupported-media-type.exception.ts
- packages/common/interfaces/modules/provider.interface.ts
Few hyperlinks on `@see` tag are out of date. I've update all of them.
> docs(common): update hyperlinks on `@see` tag comments

- package-lock.json
- packages/microservices/decorators/event-pattern.decorator.ts
- packages/microservices/decorators/message-pattern.decorator.ts
- packages/microservices/listener-metadata-explorer.ts
- packages/microservices/listeners-controller.ts
- packages/microservices/test/decorators/event-pattern.decorator.spec.ts
- packages/microservices/test/decorators/message-pattern.decorator.spec.ts
- packages/microservices/test/listeners-controller.spec.ts
- packages/microservices/test/listeners-metadata-explorer.spec.ts
Issue Number: https://github.com/nestjs/nest/issues/9222
Many MessagePatterns / EventPatterns can be applied to single method
> feat(microservices): add support for multiple message pattern decorator

- packages/microservices/external/grpc-options.interface.ts
- packages/microservices/interfaces/microservice-configuration.interface.ts
Issue Number: https://github.com/nestjs/nest/issues/9079
More details in this issue https://github.com/nestjs/nest/issues/9079
> fix(microservices): revert grpc client interceptors (grpc-specific)

- packages/core/nest-application-context.ts
> Fix typo in docs

- packages/core/services/reflector.service.ts
> perf(core): use find instead of filter

- packages/common/cache/interfaces/cache-module.interface.ts
- packages/common/interfaces/nest-application-context.interface.ts
- packages/common/interfaces/version-options.interface.ts
- packages/common/services/console-logger.service.ts
- packages/common/test/file-stream/streamable-file.spec.ts
- packages/core/injector/lazy-module-loader.ts
- packages/core/test/injector/injector.spec.ts
- packages/core/test/injector/internal-core-module-factory.spec.ts
- packages/core/test/router/router-response-controller.spec.ts
- packages/microservices/ctx-host/mqtt.context.ts
- packages/microservices/test/client/client-mqtt.spec.ts
- packages/microservices/test/deserializers/kafka-response.deserializer.spec.ts
- packages/microservices/test/listeners-controller.spec.ts
- packages/microservices/test/serializers/mqtt-record.serializer.spec.ts
- packages/microservices/test/serializers/rmq-record.serializer.spec.ts
- packages/microservices/test/server/server-mqtt.spec.ts
- [ x ] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [ x ] Code style update (formatting, local variables)
Just random typo fixes. Please review.
N/A
- [ x ] No
> chore: typo fix

- integration/repl/e2e/repl.spec.ts
- packages/core/repl/repl-context.ts
No integration tests for the alias `$` of `get` function from REPL feature.
The alias `$` was not registered as it should.
> fix(integration,core): register native function aliases on repl feature

- packages/common/services/logger.service.ts
> docs(common): replace 'v8' by 'v9' on error message

- package.json
Fixes package.json test script to the previous version.
When executing `npm run test` only `injector.spec.ts` files are executed.
All unit tests are executed.
> chore(): fix test script

- packages/platform-fastify/adapters/fastify-adapter.ts
- packages/platform-fastify/package.json
Issue Number: 
https://github.com/nestjs/nest/issues/9899
The dependencie `point-of-view@6.3.0` has been deprecated  see [here](https://www.npmjs.com/package/point-of-view)
replaced with `@fastify/view@7.0.0` link repo: https://github.com/fastify/point-of-view
> chore(): update deps platform fastify

- packages/core/router/router-explorer.ts
Remove unused declarations ( see screenshot)
In this file [ws-context-creator.ts](https://github.com/nestjs/nest/blob/master/packages/websockets/context/ws-context-creator.ts)  ( see screenshot )
gives an export error.
Question: Is it correct that it is written like this: `CUSTOM_ROUTE_AGRS_METADATA` in this [constants.ts](https://github.com/nestjs/nest/blob/master/packages/common/constants.ts#L18-L22) file ?  or it must be written like this: `CUSTOM_ROUTE_ARGS_METADATA`
> chore(router-explorer): remove unused declarations

- Readme.md
- readme_jp.md
- readme_kr.md
This PR fixes Readme.md translation(Korean, Japanese) to improve readability.
> chore: fix Readme.md translation

- tools/gulp/tasks/packages.ts
Remove unused declarations ( see screenshot )
> chore(tools-gulp-task): remove unused declarations 

- packages/common/serializer/class-serializer.interceptor.ts
> refactor(common): optimize `ClassSerializerInterceptor`

- packages/common/interfaces/nest-application-context-options.interface.ts
> chore(): fix typo in docs

- packages/core/test/repl/assign-to-object.util.spec.ts
> test(core): fix unresolved import

- packages/microservices/serializers/mqtt-record.serializer.ts
Update import in mqtt record serializer
> chore(microservice): update import in mqtt record serializer

- packages/microservices/deserializers/index.ts
- packages/microservices/serializers/index.ts
Added file `index.ts` in  folders deserializers and serializers
> chore(microservices): added file index in deserializers and serializers

- packages/common/module-utils/configurable-module.builder.ts
- packages/common/module-utils/utils/index.ts
Update import in module utils and added file `index.ts` for to improve the import.
> chore(common): update import in module utils

- packages/microservices/client/client-grpc.ts
- packages/microservices/errors/invalid-grpc-package.exception.ts
- packages/microservices/errors/invalid-grpc-service.exception.ts
- packages/microservices/errors/invalid-proto-definition.exception.ts
- packages/microservices/server/server-grpc.ts
Error messages: 
- The invalid .proto definition (file not found)
- The invalid gRPC service (service not found)
- The invalid gRPC package (package not found)
Error messages: 
- The invalid .proto definition (file at ${path} not found)
- The invalid gRPC service (service ${name} not found)
- The invalid gRPC package (package ${name} not found)
> feat(microservices): path, package and service names added to exceptions

- packages/common/cache/interceptors/cache.interceptor.ts
handle unhandledRejection by overriding CacheInterceptor#setCache
without this change, caching undefined in async envrionment will
create unhandledRejection which will cause app to shutdown.
closes #10225
Issue Number: [https://github.com/nestjs/nest/issues/10225](https://github.com/nestjs/nest/issues/10225)
handle unhandledRejection by overriding CacheInterceptor#setCache
without this change, caching undefined in async envrionment will
create unhandledRejection which will cause app to shutdown.
If someone is using setCache name in their extended CacheInterceptor already, it might break their code.
Users will have to change method name to something else to avoid side effects
1. I had …
> feat(common): wrap cacheManager.set in try..catch blocks

- packages/microservices/client/client-tcp.ts
- packages/microservices/test/client/client-tcp.spec.ts
Issue Number: #10286
no memory leaks by clearing the routing map and calling all outstanding callbacks
> fix: tcp client memory leaks #10286

- .eslintrc.js
This change does not affect the operation.
In preparing this PR, I checked the typescript-eslint source code.
I referred to the recommends in [plugin:@typescript-eslint/recommended](https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/src/configs/recommended.ts), and [/configs/eslint-recommended](https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/src/configs/eslint-recommended.ts) was extended and after checking the contents, I thought I was seeing the same settings as `plugin:@typescript-eslint/eslint-recommended`.
Since these would be duplicate descriptions, I removed the unwanted description.
> refactor(common): remove .eslintrc typescript-eslint/eslint-recommended

- .github/workflows/codeql-analysis.yml
Upgrade `actions/checkout` to `v3` in `codeql-analysis.yml` 
> ci(codeql-analysis): upgrade actions/checkout to v3

- package-lock.json
- package.json
> Revert "chore(deps-dev): bump cache-manager from 4.1.0 to 5.0.0"

- packages/core/middleware/middleware-module.ts
- packages/core/nest-application.ts
- packages/core/router/router-explorer.ts
- packages/core/router/routes-resolver.ts
Updated imports in:
- `packages/core/nest-application.ts` 
- `packages/core/router/routes-resolver.ts`
- `packages/core/middleware/middleware-module.ts`
- `packages/core/router/router-explorer.ts`
> chore(core): updated imports

- packages/common/services/console-logger.service.ts
- packages/core/helpers/handler-metadata-storage.ts
- packages/core/injector/injector.ts
- packages/core/injector/module.ts
- packages/core/middleware/builder.ts
- packages/core/nest-application-context.ts
- packages/platform-express/multer/interfaces/files-upload-module.interface.ts
Updated imports in:
- `packages/common/services/console-logger.service.ts`
- `packages/core/helpers/handler-metadata-storage.ts`
- `packages/core/injector/injector.ts`
- `packages/core/injector/module.ts`
- `packages/core/middleware/builder.ts`
- `packages/core/nest-application-context.ts`
- `packages/platform-express/multer/interfaces/files-upload-module.interface.ts`
An example in the file `packages/core/injector/injector.ts`: 
Before:
After:
Updated the following `index.ts` files
- `packages/core/errors/exceptions/index.ts`
A proposal to further improve imports in various files of the `core`, `common` and `platform-express`,
> chore(common,core,express): update imports

- packages/core/router/router-execution-context.ts
> fix(core): return response required for fastify v4

- packages/platform-fastify/adapters/fastify-adapter.ts
> fix: fastify-adapter register func sign #10604

- sample/15-mvc/package.json
> chore: remove unneeded pug dependency from sample (15-mvc)

- Readme.md
Please update Readme.md as Nord has rebranded.
url: https://nordbot.app
Please update our new logo as well.
> docs(readme): update Readme.md

- packages/common/decorators/core/controller.decorator.ts
- packages/common/exceptions/bad-gateway.exception.ts
- packages/common/exceptions/bad-request.exception.ts
- packages/core/helpers/external-context-creator.ts
- packages/core/injector/container.ts
- packages/microservices/listener-metadata-explorer.ts
- packages/microservices/microservices-module.ts
- packages/platform-fastify/interfaces/external/fastify-static-options.interface.ts
- packages/platform-fastify/interfaces/external/point-of-view-options.interface.ts
Proposals:
- Updated imports in the following files: 
`packages/common/decorators/core/controller.decorator.ts`
`packages/core/injector/container.ts`
`packages/microservices/listener-metadata-explorer.ts`
`packages/microservices/microservices-module.ts`
- Renamed link for `fastify-static` for options, why the attached link in the comments doesn't work, in the following file:
`packages/platform-fastify/interfaces/external/fastify-static-options.interface.ts`
- Renamed link for `point-of-view` (package `fastify`) for options, why the attached link in the comments doesn't work, in the following file:
`packages/platform-fastify/interfaces/external/point-of-view-options.int …
> refactor(): improvements and update imports

- packages/platform-fastify/adapters/fastify-adapter.ts
- packages/platform-fastify/interfaces/external/fastify-view-options.interface.ts
- packages/platform-fastify/interfaces/external/index.ts
- packages/platform-fastify/interfaces/nest-fastify-application.interface.ts
Proposal:
Following some changes and the renaming of the `fastify/point-to-view` package to `fastify/view`, the interface inside the adapter for `fastify` should also be updated with the new name 🙌 (see [here](https://github.com/fastify/point-of-view/blob/master/types/index.d.ts#L50))
> refactor(fastify): renamed point-of-view interface

- LICENSE
- [x ] Refactoring (no functional changes, no api changes)
> Updated License Year

- packages/platform-fastify/adapters/fastify-adapter.ts
Proposal:
- Replaced `FastifyLoggerInstance` method with `FastifyBaseLogger` because it is deprecated ( see screenshot)
> chore(fastify-adapter): updated the method for fastify logger

- packages/microservices/server/server-kafka.ts
Fix the one liner
- [ x] Bugfix
Issue Number:
[10379](https://github.com/nestjs/nest/pull/10379)
[10113](https://github.com/nestjs/nest/issues/10113)
Pull request mentioned remove lines. Not needed to fix this bug.
Other information is in issue
- [x ] No
> fix: kafka rpc exception not resolved

- packages/core/middleware/middleware-module.ts
- packages/core/router/router-explorer.ts
- packages/microservices/listeners-controller.ts
> Revert "fix(core,microservices): inject the context when the tree is not durable"

- packages/core/middleware/middleware-module.ts
- packages/core/router/router-explorer.ts
- packages/microservices/listeners-controller.ts
> Revert "Revert "fix(core,microservices): inject the context when the tree is not durable""

- packages/core/injector/compiler.ts
Issue Number: https://github.com/nestjs/nest/issues/10347
> fix(core): unwrap forward ref in module compiler

- packages/core/injector/instance-wrapper.ts
- packages/core/test/injector/instance-wrapper.spec.ts
Issue Number: #11002
Providers are correctly scoped.
> fix(core): :ambulance: Fix for calculating durability of a provider

- integration/inspector/e2e/fixtures/post-init-graph.json
- integration/inspector/e2e/fixtures/pre-init-graph.json
- packages/core/injector/modules-container.ts
- packages/core/inspector/deterministic-uuid-registry.ts
- packages/core/middleware/utils.ts
- packages/core/package.json
- packages/microservices/listener-metadata-explorer.ts
- packages/websockets/gateway-metadata-explorer.ts
> chore(core): remove uuid dependency

- .github/ISSUE_TEMPLATE/Bug_report.yml
> docs: fix typo

- packages/common/pipes/file/parse-file.pipe.ts
- packages/common/utils/shared.utils.ts
> refactor(common): satisfy function quality in parse-file.pipe.ts

- integration/inspector/e2e/graph-inspector.spec.ts
- integration/microservices/e2e/broadcast-mqtt.spec.ts
- integration/microservices/e2e/broadcast-nats.spec.ts
- integration/microservices/e2e/broadcast-redis.spec.ts
- integration/microservices/e2e/concurrent-kafka.spec.ts
- integration/microservices/e2e/mqtt-record-builder.spec.ts
- integration/microservices/e2e/orders-grpc.spec.ts
- integration/microservices/e2e/sum-grpc.spec.ts
- integration/microservices/e2e/sum-kafka.spec.ts
- integration/microservices/e2e/sum-mqtt.spec.ts
- integration/microservices/e2e/sum-nats.spec.ts
- integration/microservices/e2e/sum-redis.spec.ts
- integration/microservices/e2e/sum-rmq.spec.ts
- integration/microservices/e2e/sum-rpc.spec.ts
- integration/scopes/e2e/msvc-request-scope.spec.ts
- packages/core/test/nest-application.spec.ts
- provide `MicroserviceOptions` type to `connectMicroservice` method in tests
- fix redis connection options in tests
> test: add microservice generic type explicitly

- packages/common/decorators/core/controller.decorator.ts
- packages/common/pipes/file/file-validator.interface.ts
- packages/common/pipes/file/max-file-size.validator.ts
- packages/common/pipes/file/parse-file.pipe.ts
- packages/core/metadata-scanner.ts
- packages/microservices/external/mqtt-client.interface.ts
- packages/microservices/server/server-redis.ts
- packages/websockets/interfaces/gateway-metadata.interface.ts
Proposals:
- Updated JSDoc annotations in comments In the following files:
- `packages/common/decorators/core/controller.decorator.ts`
- `packages/common/pipes/file/file-validator.interface.ts`
-  `packages/common/pipes/file/max-file-size.validator.ts`
-  `packages/common/pipes/file/parse-file.pipe.ts`
- `packages/core/metadata-scanner.ts`
- `packages/microservices/external/mqtt-client.interface.ts`
-  `packages/websockets/interfaces/gateway-metadata.interface.ts`
- Removed import not used in `packages/microservices/server/server-redis.ts` (see screenshot) 
I have collected some things in this PR so as not to create too many PRs 😄 I hope it will be okay  🙌
> chore(): update comment jsdoc and others update

- sample/13-mongo-typeorm/package.json
> Revert "fix(deps): update dependency mongodb to v5"

- packages/common/cache/cache.constants.ts
- packages/common/cache/cache.module.ts
- packages/common/cache/decorators/cache-key.decorator.ts
- packages/common/cache/decorators/cache-ttl.decorator.ts
- packages/common/cache/interceptors/cache.interceptor.ts
Use this package instead https://github.com/nestjs/cache-manager
> chore(common): deprecate cache module

- readme_zh.md
> docs: update zh readme headers

- sample/13-mongo-typeorm/README.md
The readme title is wrong because this sample doesn't use `mongoose`.
The title changed to "Mongo TypeORM sample".
N/A
> sample/13: change readme title

- packages/common/pipes/file/max-file-size.validator.ts
> chore(validation): add ability to pass custom message in file size validator

- packages/core/scanner.ts
Issue Number: #11586 
Modules will now have the distance of the longest path if the module is used in multiple places
This fix should only make obsolete any work arounds projects have used to fix initialization order
> fix(core): Only update module distance if greater

- packages/microservices/server/server-grpc.ts
- packages/microservices/test/server/server-grpc.spec.ts
https://github.com/nestjs/nest/issues/11429
Issue Number: 11429
- subscriber now `await` the data passed to the callback.
> fix(microservices): grpc-server handle async interceptors

- packages/common/pipes/parse-enum.pipe.ts
Issue Number: fixes extra stuff https://github.com/nestjs/nest/issues/11602
instead of importing Injectable and Optional decorators from packages/common/index.ts, we now import them from packages/common/decorators/core.ts to avoid a circular import
> refactor(common): remove barrel import in parse enum pipe file

- packages/microservices/client/client-kafka.ts
- packages/microservices/test/client/client-kafka.spec.ts
Issue Number: [11688](https://github.com/nestjs/nest/issues/11688)
partitions are reassigned correctly
> fix(microservices): check length of member partitions on group join

- packages/microservices/interfaces/microservice-configuration.interface.ts
Issue Number:  #11819
Remove the correct field from the type
> fix: kafka subscribe bad type - v10 regression

- packages/common/pipes/file/file-type.validator.ts
- packages/common/pipes/file/max-file-size.validator.ts
- packages/common/test/pipes/file/file-type.validator.spec.ts
- packages/common/test/pipes/file/max-file-size.validator.spec.ts
Issue Number: #11803
Fix the implementations to support undefined input
> fix(common): type errors in file validator implementations

- packages/platform-express/multer/interceptors/any-files.interceptor.ts
- packages/platform-express/multer/interceptors/file-fields.interceptor.ts
- packages/platform-express/multer/interceptors/file.interceptor.ts
- packages/platform-express/multer/interceptors/files.interceptor.ts
- packages/platform-express/multer/interceptors/no-files.interceptor.ts
- packages/platform-express/multer/interfaces/files-upload-module.interface.ts
- packages/platform-express/multer/interfaces/multer-options.interface.ts
- packages/platform-express/multer/multer.module.ts
Proposal:
- mark api public in multer module inside platform-express
> chore(): mark api public in multer module inside platform-express

- packages/core/interceptors/interceptors-consumer.ts
- packages/core/test/interceptors/interceptors-consumer.spec.ts
> fix(nest): Support RxJS retries and Async Context tracking

- packages/platform-express/adapters/express-adapter.ts
Warning when Content-Type header has already defined 'application/json', but including specific charset.
The condition will check for content-type, skipping the charset.
> fix(express): improve error reply content-type check

- packages/core/test/interceptors/interceptors-consumer.spec.ts
> test: remove redundant await

- sample/19-auth-jwt/src/auth/auth.service.ts
> docs: add missing types for username and password

- .circleci/config.yml
Test are only running on node 16. Unit tests also on node 18
Issue Number: #12215
unit tests and integration tests will run on node 16, 18 and 20
> ci: add NodeJS 20 to CI matrix

- integration/discovery/e2e/discover-by-meta.spec.ts
- integration/discovery/src/app.module.ts
- integration/discovery/src/decorators/webhook.decorators.ts
- integration/discovery/src/my-webhook/cleanup.webhook.ts
- integration/discovery/src/my-webhook/flush.webhook.ts
- integration/discovery/src/my-webhook/my-webhook.module.ts
- integration/discovery/src/webhooks.explorer.ts
- integration/discovery/tsconfig.json
- packages/core/discovery/discoverable-meta-host-collection.ts
- packages/core/discovery/discovery-service.ts
- packages/core/injector/container.ts
- packages/core/injector/module.ts
- packages/core/test/injector/container.spec.ts
Issue Number: https://github.com/nestjs/nest/issues/10629
```typescript
const WebhookHandler = DiscoveryService.createDecorator<{ name: string }>();
@WebhookHandler({ name: 'my-webhook' })
export class MyWebhook {}
```
and then in the explorer class:
```typescript
const webhooks = discoveryService.getProviders({
metadataKey: WebhookHandler.KEY,
});
webhooks.forEach(wrapper => {
// type-safe
const { name } = discoveryService.getMetadataByDecorator(
WebhookHandler,
wrapper,
);
console.log(name);
});
```
> feat(core): discover by decorator, explorer pattern

- .circleci/config.yml
PR #12218 caused a regression
unit tests and integration tests will run on node 16, 18 and 20
> fix: CI config is failing

- packages/microservices/server/server-grpc.ts
- packages/microservices/test/server/server-grpc.spec.ts
fixes #12330
Issue Number: #12330
The code now checks the return value of `write` to ensure that it's only waiting for a drain event when it must.
My fault. :(
> fix(grpc): will properly write to streams

- packages/common/index.ts
- packages/common/interfaces/http/http-redirect-response.interface.ts
- packages/common/interfaces/http/index.ts
When sending a redirect URL on response, you must return an object with a shape as explained in the documentation.
Created an interface that anyone can use directly from the framework.
> feat: implement http redirect response interface

- packages/platform-fastify/decorators/route-config.decorator.ts
Proposal:
- Marked as API public the decorator `@RouteConfig` in `platform-fastify`
> chore(platform-fastify): marked the api public in route config decorator

- Readme.md
> docs: update readme, use X instead of twitter

- packages/common/decorators/http/request-mapping.decorator.ts
> fix(http): change description for Search decorator

- packages/common/test/decorators/route-params.decorator.spec.ts
Couldn't find a test that tests the @Param decorator.
Tests the metadata that @Param sets
I just wanted to understand what's going on behind the scenes, so I figured I might as well try to write a test as a means to learn more about it.
> test(common): added a test for the @param decorator metadata

- packages/common/module-utils/utils/get-injection-providers.util.ts
- packages/core/middleware/routes-mapper.ts
I did a little optimization. `map`+`flat` can be replaced by single `flatMap`.
> utils: simplify map + flat in injections providers

- packages/microservices/external/mqtt-options.interface.ts
https://github.com/nestjs/nest/issues/12470
Issue Number: 12470
With these changes, developers using NestJs can utilize properties from the MQTT 5.0 protocol version.
> feat(microservices): Added properties for MQTT protocol version 5.0

- readme_jp.md
translate not fully translated
> docs: more translate readme ja

- packages/microservices/server/server-grpc.ts
- packages/microservices/test/server/server-grpc.spec.ts
+ Ensures all values that are buffered while the stream is unwritable are written when the drain event fires.
+ Ensures that if the stream becomes unwritable while draining, it will wait for another drain event.
+ Ensures that if the observable completes while draining, it will wait for the entire buffer to be drained before resolving.
+ Ensures that if the observable errors while draining, it will wait for the entire buffer to be drained before rejecting.
+ Fixes tests that had some incorrect assumptions around stream write returns and the order of events.
+ Adds a more comprehensive set of tests for writing the observable to the stream.
Fixes #12751
It was dropping values due to poor …
> fix(grpc): ensure all buffered values drain

- LICENSE
> chore(license): update year to 2024

- packages/common/decorators/http/header.decorator.ts
- packages/core/middleware/builder.ts
- packages/core/middleware/route-info-path-extractor.ts
- packages/core/router/router-response-controller.ts
- packages/core/test/middleware/route-info-path-extractor.spec.ts
> fix(core): when having multiple versions on middleware routes builder

- packages/microservices/server/server-grpc.ts
If an error occurs, it is send to grpc after unsubscribing.
Issue Number: #13187 
Emit an error to grpc stream before unsubscribe
> fix(microservices): emit an error to grpc stream before unsubscribe

- .gitignore
- [ ✅] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [ ✅] Tests for the changes have been added (for bug fixes / features)
- [✅ ] Docs have been added / updated (for bug fixes / features)
- [ ✅] Refactoring (no functional changes, no api changes)
- [ ✅] No
> Adding eclipse IDE files to gitignore

- packages/core/test/injector/injector.spec.ts
Changed the instance creation in the injector test from DependencyOne to DependencyTwo. This ensures that the right prototype object is used when creating an instance for testing purposes.
Fixed a small inconsistency in the test code.
> test(core): Update instance creation in injector test

- sample/04-grpc/src/hero/hero.controller.ts
- sample/04-grpc/src/hero/hero.proto
Synchronize changed docs and sample code at https://github.com/nestjs/docs.nestjs.com/pull/1179.
Launch the server of the sample code,
When executing the client code in docs,
In particular, there is confusion over the pluralization service name of hero.proto.
> sample(04-grpc): synchronize pluralisation docs

- packages/common/decorators/http/create-route-param-metadata.decorator.ts
- packages/core/hooks/on-app-shutdown.hook.ts
- packages/microservices/server/server-grpc.ts
Change mismatched JSDoc
I hope it helps.
> chore(common, core, microservices): Change mismatched JSDoc

- packages/common/module-utils/configurable-module.builder.ts
> doc: fix typos

- integration/nest-application/global-prefix/e2e/global-prefix.spec.ts
- integration/nest-application/global-prefix/src/app.controller.ts
- integration/nest-application/global-prefix/src/app.module.ts
- packages/core/middleware/builder.ts
- packages/core/middleware/middleware-module.ts
> Fix middleware global prefix exclude

- packages/microservices/server/server-grpc.ts
> Revert "fix(microservices): fix redundant code to emit error"

- packages/microservices/server/server-grpc.ts
- packages/microservices/test/server/server-grpc.spec.ts
> Revert "fix(microservice) Delete unnecessary call of grpcClient.start"

- integration/microservices/src/kafka-concurrent/kafka-concurrent.controller.ts
- integration/mosquitto.conf
- packages/core/test/interceptors/interceptors-consumer.spec.ts
> chore: fix some typos in comments

- package-lock.json
- package.json
> Revert "chore(deps-dev): bump mqtt from 5.6.0 to 5.7.0"

- packages/microservices/client/client-nats.ts
- packages/microservices/test/client/client-nats.spec.ts
> fix(microservices): hold nats client connection promise ref 

- package-lock.json
- package.json
> Revert "chore(deps-dev): bump @typescript-eslint/eslint-plugin from 7.18.0 to 8.2.0"

- packages/core/scanner.ts
- packages/core/test/router/router-response-controller.spec.ts
- sample/18-context/src/main.ts
> chore: fix some comments

- .gitignore
- packages/core/package.json
- packages/platform-express/package.json
- packages/platform-fastify/package.json
@kamilmysliwiec 
I just merged the changes made on PRs #13963 #13961 #13964
To address the security issues at `@nestjs/core`, `@nestjs/platform-express` and `@nestjs/platform-fastify` packages without introducing any breaking change
- closes #13959
- closes #13960 
- closes #13955
- closes #13965
> chore(core,express,fastify): fix hard dependencies with security issues

- Readme.md
> docs(): fix CircleCI badge url typo

- package-lock.json
- package.json
> Revert "chore(deps-dev): bump @typescript-eslint/eslint-plugin from 7.18.0 to 8.6.0"

- integration/hello-world/e2e/express-instance.spec.ts
- integration/hello-world/e2e/fastify-adapter.spec.ts
- packages/platform-fastify/adapters/fastify-adapter.ts
N/A fix was already merged
N/A
> test: add coverage for Fastify HEAD regression

- packages/core/injector/internal-core-module/internal-core-module-factory.ts
> fix(core): initialize internal core module on preview

- packages/platform-fastify/interfaces/nest-fastify-application.interface.ts
Issue Number: https://github.com/nestjs/nest/issues/14102
> chore(fastify): undeprecate listen method

- packages/microservices/server/server-grpc.ts
- packages/microservices/test/server/server-grpc.spec.ts
Original PR https://github.com/nestjs/nest/pull/13283
> fix(microservices): delete unnecessary call of grpcClient.start

- packages/microservices/listener-metadata-explorer.ts
- packages/microservices/test/listeners-metadata-explorer.spec.ts
> fix(microservices): use instance refs for target handler callbacks

- packages/platform-fastify/interfaces/external/fastify-view-options.interface.ts
Proposal:
- Updated `fastify-view-options.interface.ts`, added property `asyncProperyName`( see here for other info: https://github.com/fastify/point-of-view/blob/master/types/index.d.ts#L49)
> chore(fastify): update fastify view options interface

- packages/microservices/errors/max-packet-length-exceeded.exception.ts
- packages/microservices/helpers/json-socket.ts
Issue Number: https://github.com/nestjs/nest/issues/13145
> feat(microservices): add max tcp packet buffer length

- packages/common/exceptions/http.exception.ts
- packages/common/interfaces/http/http-exception-body.interface.ts
Issue Number: https://github.com/nestjs/nest/issues/12787
> feat(common): allow passing number to http error createBody

- packages/core/nest-factory.ts
we can supply anything to `NestFactory.create` and `NestFactory.createMicroservice` as the entry/root module
make `NestFactory.create` and `NestFactory.createMicroservice` a little more type-safe.
> feat(core)!: type narrowing valid entry module for nestjs factories

- packages/microservices/client/client-mqtt.ts
> fix(microservices): no messages emitted with mqtt when qos set

- packages/common/file-stream/streamable-file.ts
- packages/common/services/console-logger.service.ts
- packages/common/test/services/logger.service.spec.ts
- packages/core/errors/exception-handler.ts
- packages/core/exceptions/base-exception-filter.ts
- packages/core/exceptions/external-exception-filter.ts
- packages/core/test/errors/test/exception-handler.spec.ts
- packages/microservices/exceptions/base-rpc-exception-filter.ts
- packages/microservices/server/server-grpc.ts
- packages/websockets/exceptions/base-ws-exception-filter.ts
Issue Number: https://github.com/nestjs/nest/issues/11189 https://github.com/nestjs/nest/issues/10342 https://github.com/nestjs/nest/issues/13841
Default settings:
JSON:
```ts
const app = await NestFactory.create(AppModule, {
logger: new ConsoleLogger({
json: true
}),
});
```
JSON + colors:
JSON + colors + compact mode disabled:
> feat(common): json logger and a few other improvements

- packages/microservices/decorators/message-pattern.decorator.ts
- packages/microservices/server/server-grpc.ts
> fix(microservices): grpc client streaming bugs

- LICENSE
- packages/common/index.ts
- packages/core/index.ts
- packages/index.ts
- packages/microservices/index.ts
- packages/platform-express/index.ts
- packages/platform-fastify/index.ts
- packages/platform-socket.io/index.ts
- packages/platform-ws/index.ts
- packages/testing/index.ts
- packages/websockets/index.ts
> chore: update copyright years 2025

- packages/common/test/utils/shared.utils.spec.ts
- packages/common/utils/shared.utils.ts
Issue Number: #14545
Correctly support route with optional first parameter
> fix(common): addLeadingSlash optional group support

- packages/common/pipes/validation.pipe.ts
> fix(common): revert to original value (swc builders regression)

- packages/microservices/server/server.ts
- [X ] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [ X] Bugfix
Issue Number: #14583
- No values are lost in emission
- The last message is guaranteed to have isDisposed: true
- FIFO order is preserved preventing race conditions
- [ X] No
> fix(microservices): server send drops emitted value

- sample/10-fastify/package.json
Remove useless devDependency, which is not used because another platform (fastify instead of express) is selected.
> chore(sample): remove `@types/express` useless dev deps from sample 10

- packages/core/injector/instance-wrapper.ts
> fix(core): infinite loop on broken circular reference

- packages/microservices/client/client-rmq.ts
- packages/microservices/interfaces/microservice-configuration.interface.ts
- packages/microservices/server/server-rmq.ts
We cannot specify additional arguments when creating the exchange, which is necessary for various purposes. One of them is compatibility with the `rabbitmq-delayed-message-exchange` plugin.
Now we can specify additional arguments when creating the exchange
> feat(microservices): Add exchange arguments to RabbitMQ

- packages/core/injector/module.ts
> refactor: improve module typings

- readme_kr.md
Minor documentation update (readme_kr.md)
The contact section in the Korean README (README.ko.md) refers to the social media platform as 'Twitter'.
1. It replaces 'Twitter' with 'X' to reflect the platform's rebranding.
2. It translates the English labels (e.g., "Author", "Website") into Korean for better readability for the Korean-speaking community.
> docs(readme): update 'Twitter' to 'X' in Korean contact section

- integration/scopes/e2e/transient-scope.spec.ts
- packages/core/injector/injector.ts
- packages/core/injector/instance-wrapper.ts
> fix(core): attach root inquirer for nested transient providers
